// Code generated by wacogo-witgen from maybe.wit. DO NOT EDIT.

// Package maybe provides Go bindings for the example:demo/maybe interface.
package maybe

import (
	"context"
)

// InterfaceName is the canonical WIT id of the interface this binding
// was generated from.
const InterfaceName = "example:demo/maybe"

// Maybe is the Go binding for the example:demo/maybe interface.
// Implement it to provide a host-side component, or pass an exported wasm
// instance to WrapInstance to obtain a Maybe that calls into wasm.
// Resource-typed parameters and results appear as *<R>Handle values that can
// be passed across component boundaries.
type Maybe interface {
	Find(ctx context.Context, key uint32) (OptionString, error)
}

// OptionString corresponds to a WIT option<...> type.
type OptionString struct {
	IsSome bool
	Value  string
}

func SomeString(v string) OptionString {
	return OptionString{IsSome: true, Value: v}
}

func NoneString() OptionString {
	return OptionString{}
}
