// Code generated by wacogo-witgen from maybe.wit. DO NOT EDIT.

// Package maybe provides Go bindings for the example:demo/maybe interface.
package maybe

import (
	"context"
	"fmt"

	"github.com/partite-ai/wacogo"
	"github.com/partite-ai/wacogo/host"
)

// Factory builds host-side instances of the Maybe interface
// from a Go implementation.
type Factory struct {
	engine *wacogo.Engine
	comp   *host.Component
}

type instanceState struct {
	impl Maybe
}

// Deps groups the cross-component dependencies required to instantiate
// Maybe. Pass a populated value via NewInstance.
type Deps struct {
}

// NewFactory creates a Factory bound to e. A single Factory may be
// reused to build multiple instances backed by different implementations.
func NewFactory(ctx context.Context, e *wacogo.Engine) (*Factory, error) {
	f_ := &Factory{engine: e}
	b_ := e.NewHostBuilder("example_demo_maybe")

	b_.AddFunction("find", &host.FuncType{
		Params:  []host.Param{{Name: "key", Type: host.U32}},
		Results: []host.ResultDecl{{Name: "", Type: host.Option{Inner: host.String}}},
	}, wrapFind(f_))

	comp_, err_ := b_.Build(ctx)
	if err_ != nil {
		return nil, err_
	}
	f_.comp = comp_
	return f_, nil
}

// NewInstance creates a fresh component instance backed by impl. Pass
// inst.Core() to wacogo.WithInstanceImport to wire the instance into a
// composite world. deps may be nil only when Maybe has no
// imports.
func (f *Factory) NewInstance(ctx context.Context, impl Maybe, deps *Deps, opts ...host.InstantiateOption) (*host.ComponentInstance, error) {
	_ = deps
	state_ := &instanceState{impl: impl}
	opts = append(opts, host.WithUserState(state_))
	inst_, err_ := f.comp.Instantiate(ctx, opts...)
	if err_ != nil {
		return nil, err_
	}
	return inst_, nil
}

// Close releases resources shared by the Factory. Existing instances
// remain callable until each is closed individually.
func (f *Factory) Close(ctx context.Context) error { return f.comp.Close(ctx) }

func toGoFlatOptionString(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, stack []uint64) (OptionString, error) {
	optT_ := ty.(wacogo.TypeOption)
	_ = optT_
	disc_ := uint32(stack[0])
	var out_ OptionString
	if disc_ != 0 {
		out_.IsSome = true
		if tmp_, err_ := toGoFlatString(ctx, cc, h, optT_.Inner, stack[1:3]); err_ != nil {
			return OptionString{}, err_
		} else {
			out_.Value = tmp_
		}
	}
	return out_, nil
}

func toGoMemOptionString(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, ptr uint32) (OptionString, error) {
	optT_ := ty.(wacogo.TypeOption)
	_ = optT_
	var disc_ uint8
	if tmp_, ok_ := cc.Memory().ReadByte(ptr); !ok_ {
		return OptionString{}, fmt.Errorf("wacogo/witgen: toGoMemOptionString: discriminant: bad memory read")
	} else {
		disc_ = tmp_
	}
	var out_ OptionString
	if disc_ != 0 {
		out_.IsSome = true
		if tmp_, err_ := toGoMemString(ctx, cc, h, optT_.Inner, ptr+4); err_ != nil {
			return OptionString{}, err_
		} else {
			out_.Value = tmp_
		}
	}
	return out_, nil
}

func fromGoFlatOptionString(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, stack []uint64, v OptionString) error {
	if v.IsSome {
		stack[0] = 1
		if err_ := fromGoFlatString(ctx, cc, h, stack[1:3], v.Value); err_ != nil {
			return err_
		}
	} else {
		stack[0] = 0
		stack[1] = 0
		stack[2] = 0
	}
	return nil
}

func fromGoMemOptionString(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, ptr uint32, v OptionString) error {
	if v.IsSome {
		if ok_ := cc.Memory().WriteByte(ptr, 1); !ok_ {
			return fmt.Errorf("wacogo/witgen: fromGoMemOptionString: discriminant: bad memory write")
		}
		if err_ := fromGoMemString(ctx, cc, h, ptr+4, v.Value); err_ != nil {
			return err_
		}
	} else {
		if ok_ := cc.Memory().WriteByte(ptr, 0); !ok_ {
			return fmt.Errorf("wacogo/witgen: fromGoMemOptionString: discriminant: bad memory write")
		}
	}
	return nil
}

func liftFlatOptionString(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, stack []uint64) (OptionString, error) {
	optT_ := ty.(wacogo.TypeOption)
	_ = optT_
	disc_ := uint32(stack[0])
	var out_ OptionString
	if disc_ != 0 {
		out_.IsSome = true
		if tmp_, err_ := liftFlatString(ctx, caller, callee, h, optT_.Inner, stack[1:3]); err_ != nil {
			return OptionString{}, err_
		} else {
			out_.Value = tmp_
		}
	}
	return out_, nil
}

func liftMemOptionString(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, ptr uint32) (OptionString, error) {
	optT_ := ty.(wacogo.TypeOption)
	_ = optT_
	var disc_ uint8
	if tmp_, ok_ := callee.Memory().ReadByte(ptr); !ok_ {
		return OptionString{}, fmt.Errorf("wacogo/witgen: liftMemOptionString: discriminant: bad memory read")
	} else {
		disc_ = tmp_
	}
	var out_ OptionString
	if disc_ != 0 {
		out_.IsSome = true
		if tmp_, err_ := liftMemString(ctx, caller, callee, h, optT_.Inner, ptr+4); err_ != nil {
			return OptionString{}, err_
		} else {
			out_.Value = tmp_
		}
	}
	return out_, nil
}

func lowerFlatOptionString(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, stack []uint64, v OptionString) error {
	optT_ := ty.(wacogo.TypeOption)
	_ = optT_
	if v.IsSome {
		stack[0] = 1
		if err_ := lowerFlatString(ctx, caller, callee, h, optT_.Inner, stack[1:3], v.Value); err_ != nil {
			return err_
		}
	} else {
		_ = optT_
		stack[0] = 0
		stack[1] = 0
		stack[2] = 0
	}
	return nil
}

func lowerMemOptionString(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, ptr uint32, v OptionString) error {
	optT_ := ty.(wacogo.TypeOption)
	_ = optT_
	if v.IsSome {
		if ok_ := callee.Memory().WriteByte(ptr, 1); !ok_ {
			return fmt.Errorf("wacogo/witgen: lowerMemOptionString: discriminant: bad memory write")
		}
		if err_ := lowerMemString(ctx, caller, callee, h, optT_.Inner, ptr+4, v.Value); err_ != nil {
			return err_
		}
	} else {
		_ = optT_
		if ok_ := callee.Memory().WriteByte(ptr, 0); !ok_ {
			return fmt.Errorf("wacogo/witgen: lowerMemOptionString: discriminant: bad memory write")
		}
	}
	return nil
}

func toGoFlatString(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, stack []uint64) (string, error) {
	_ = ty
	ptr_ := uint32(stack[0])
	ln_ := uint32(stack[1])
	bs_, ok_ := cc.Memory().Read(ptr_, ln_)
	if !ok_ {
		return "", fmt.Errorf("wacogo/witgen: toGoFlatString: bad memory read")
	}
	return string(bs_), nil
}

func toGoMemString(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, ptr uint32) (string, error) {
	_ = ty
	var sptr_ uint32
	if tmp_, ok_ := cc.Memory().ReadUint32Le(ptr); !ok_ {
		return "", fmt.Errorf("wacogo/witgen: toGoMemString: string ptr: bad memory read")
	} else {
		sptr_ = tmp_
	}
	var ln_ uint32
	if tmp_, ok_ := cc.Memory().ReadUint32Le(ptr + 4); !ok_ {
		return "", fmt.Errorf("wacogo/witgen: toGoMemString: string len: bad memory read")
	} else {
		ln_ = tmp_
	}
	bs_, ok_ := cc.Memory().Read(sptr_, ln_)
	if !ok_ {
		return "", fmt.Errorf("wacogo/witgen: toGoMemString: bad memory read")
	}
	return string(bs_), nil
}

func fromGoFlatString(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, stack []uint64, v string) error {
	bs_ := []byte(v)
	ptr_, err_ := cc.Realloc(ctx, 0, 0, 1, uint32(len(bs_)))
	if err_ != nil {
		return fmt.Errorf("wacogo/witgen: fromGoFlatString: realloc failed: %w", err_)
	}
	if ok_ := cc.Memory().Write(ptr_, bs_); !ok_ {
		return fmt.Errorf("wacogo/witgen: fromGoFlatString: bad memory write")
	}
	stack[0] = uint64(ptr_)
	stack[1] = uint64(len(bs_))
	return nil
}

func fromGoMemString(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, ptr uint32, v string) error {
	bs_ := []byte(v)
	sptr_, err_ := cc.Realloc(ctx, 0, 0, 1, uint32(len(bs_)))
	if err_ != nil {
		return fmt.Errorf("wacogo/witgen: fromGoMemString: realloc failed: %w", err_)
	}
	if ok_ := cc.Memory().Write(sptr_, bs_); !ok_ {
		return fmt.Errorf("wacogo/witgen: fromGoMemString: bad memory write")
	}
	if ok_ := cc.Memory().WriteUint32Le(ptr, sptr_); !ok_ {
		return fmt.Errorf("wacogo/witgen: fromGoMemString: string ptr: bad memory write")
	}
	if ok_ := cc.Memory().WriteUint32Le(ptr+4, uint32(len(bs_))); !ok_ {
		return fmt.Errorf("wacogo/witgen: fromGoMemString: string len: bad memory write")
	}
	return nil
}

func liftFlatString(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, stack []uint64) (string, error) {
	ptr_ := uint32(stack[0])
	ln_ := uint32(stack[1])
	bs_, ok_ := callee.Memory().Read(ptr_, ln_)
	if !ok_ {
		return "", fmt.Errorf("wacogo/witgen: liftFlatString: bad memory read")
	}
	return string(bs_), nil
}

func liftMemString(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, ptr uint32) (string, error) {
	var sptr_ uint32
	if tmp_, ok_ := callee.Memory().ReadUint32Le(ptr); !ok_ {
		return "", fmt.Errorf("wacogo/witgen: liftMemString: string ptr: bad memory read")
	} else {
		sptr_ = tmp_
	}
	var ln_ uint32
	if tmp_, ok_ := callee.Memory().ReadUint32Le(ptr + 4); !ok_ {
		return "", fmt.Errorf("wacogo/witgen: liftMemString: string len: bad memory read")
	} else {
		ln_ = tmp_
	}
	bs_, ok_ := callee.Memory().Read(sptr_, ln_)
	if !ok_ {
		return "", fmt.Errorf("wacogo/witgen: liftMemString: bad memory read")
	}
	return string(bs_), nil
}

func lowerFlatString(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, stack []uint64, v string) error {
	bs_ := []byte(v)
	ptr_, err_ := callee.Realloc(ctx, 0, 0, 1, uint32(len(bs_)))
	if err_ != nil {
		return fmt.Errorf("wacogo/witgen: lowerFlatString: realloc failed: %w", err_)
	}
	if ok_ := callee.Memory().Write(ptr_, bs_); !ok_ {
		return fmt.Errorf("wacogo/witgen: lowerFlatString: bad memory write")
	}
	stack[0] = uint64(ptr_)
	stack[1] = uint64(len(bs_))
	return nil
}

func lowerMemString(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, ptr uint32, v string) error {
	bs_ := []byte(v)
	sptr_, err_ := callee.Realloc(ctx, 0, 0, 1, uint32(len(bs_)))
	if err_ != nil {
		return fmt.Errorf("wacogo/witgen: lowerMemString: realloc failed: %w", err_)
	}
	if ok_ := callee.Memory().Write(sptr_, bs_); !ok_ {
		return fmt.Errorf("wacogo/witgen: lowerMemString: bad memory write")
	}
	if ok_ := callee.Memory().WriteUint32Le(ptr, sptr_); !ok_ {
		return fmt.Errorf("wacogo/witgen: lowerMemString: string ptr: bad memory write")
	}
	if ok_ := callee.Memory().WriteUint32Le(ptr+4, uint32(len(bs_))); !ok_ {
		return fmt.Errorf("wacogo/witgen: lowerMemString: string len: bad memory write")
	}
	return nil
}

func wrapFind(f *Factory) host.Func {
	return func(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, stack []uint64) error {
		state_ := h.UserState().(*instanceState)
		fnType_ := cc.Instance().ExportedFunc("find").Type()
		_ = fnType_
		key := uint32(stack[0])
		result_, implErr_ := state_.impl.Find(ctx, key)
		if implErr_ != nil {
			return fmt.Errorf("wacogo/witgen: find: impl returned error: %w", implErr_)
		}
		outPtr_, rerr_ := cc.Realloc(ctx, 0, 0, 4, 12)
		if rerr_ != nil {
			return fmt.Errorf("wacogo/witgen: find: realloc failed: %w", rerr_)
		}
		if err_ := fromGoMemOptionString(ctx, cc, h, outPtr_, result_); err_ != nil {
			return err_
		}
		stack[0] = uint64(outPtr_)
		return nil
	}
}
