// Code generated by wacogo-witgen from maybe.wit. DO NOT EDIT.

// Package maybe provides Go bindings for the example:demo/maybe interface.
package maybe

import (
	"context"
	"fmt"

	"github.com/partite-ai/wacogo"
	"github.com/partite-ai/wacogo/host"
)

// maybeWrapper is the concrete type returned by WrapInstance
// as a Maybe. Held internally; users hold it via the Maybe
// interface.
type maybeWrapper struct {
	callerInst *host.ComponentInstance
	fnFind     *host.ExportedFunc
}

// WrapInstance returns a Maybe that forwards method calls to
// callee. caller is a Factory-built host instance whose state hosts any
// handles minted by callee during those calls.
func WrapInstance(caller *host.ComponentInstance, callee *wacogo.ComponentInstance) Maybe {
	w_ := &maybeWrapper{callerInst: caller}
	w_.fnFind = host.WrapExportedFunc(callee.ExportedFunc("find"))
	return w_
}
func (w *maybeWrapper) Find(ctx context.Context, key uint32) (OptionString, error) {
	var resVal_ OptionString
	var resErr_ error
	arg0_ := key
	{
		callErr_ := w.fnFind.CallRaw(ctx, w.callerInst,
			func(caller, callee *host.CallContext, stack []uint64) {
				stack[0] = uint64(arg0_)
			},
			func(caller, callee *host.CallContext, stack []uint64) {
				if v_, err_ := liftMemOptionString(ctx, caller, callee, w.callerInst, w.fnFind.ResultType(0), uint32(stack[0])); err_ != nil {
					resErr_ = err_
					return
				} else {
					resVal_ = v_
				}
			},
		)
		if callErr_ != nil {
			return OptionString{}, fmt.Errorf("wacogo/witgen: CallRaw failed: %w", callErr_)
		}
		if resErr_ != nil {
			return OptionString{}, resErr_
		}
	}
	return resVal_, nil
}
