// Code generated by wacogo-witgen from cross_resource.wit. DO NOT EDIT.

// Package streams provides Go bindings for the example:demo/streams interface.
package streams

import (
	"context"
	"fmt"

	"github.com/partite-ai/wacogo"
	"github.com/partite-ai/wacogo/host"
)

// Factory builds host-side instances of the Streams interface
// from a Go implementation.
type Factory struct {
	engine   *wacogo.Engine
	comp     *host.Component
	handleRT *host.ResourceType
}

type instanceState struct {
	impl     Streams
	handleTR *wacogo.TypeResource
}

// Deps groups the cross-component dependencies required to instantiate
// Streams. Pass a populated value via NewInstance.
type Deps struct {
}

// NewFactory creates a Factory bound to e. A single Factory may be
// reused to build multiple instances backed by different implementations.
func NewFactory(ctx context.Context, e *wacogo.Engine) (*Factory, error) {
	f_ := &Factory{engine: e}
	b_ := e.NewHostBuilder("example_demo_streams")

	f_.handleRT = b_.AddResource("handle", resourceDtor)

	b_.AddFunction("[constructor]handle", &host.FuncType{
		Params:  []host.Param{},
		Results: []host.ResultDecl{{Name: "", Type: f_.handleRT.Own()}},
	}, wrapNewHandle(f_))

	b_.AddFunction("[method]handle.read", &host.FuncType{
		Params:  []host.Param{{Name: "self", Type: f_.handleRT.Borrow()}},
		Results: []host.ResultDecl{{Name: "", Type: host.U32}},
	}, wrapHandleRead(f_))

	comp_, err_ := b_.Build(ctx)
	if err_ != nil {
		return nil, err_
	}
	f_.comp = comp_
	return f_, nil
}

// NewInstance creates a fresh component instance backed by impl. Pass
// inst.Core() to wacogo.WithInstanceImport to wire the instance into a
// composite world. deps may be nil only when Streams has no
// imports.
func (f *Factory) NewInstance(ctx context.Context, impl Streams, deps *Deps, opts ...host.InstantiateOption) (*host.ComponentInstance, error) {
	_ = deps
	state_ := &instanceState{impl: impl}
	opts = append(opts, host.WithUserState(state_))
	inst_, err_ := f.comp.Instantiate(ctx, opts...)
	if err_ != nil {
		return nil, err_
	}
	state_.handleTR = inst_.Core().ExportedType("handle").(*wacogo.TypeResource)
	return inst_, nil
}

// Close releases resources shared by the Factory. Existing instances
// remain callable until each is closed individually.
func (f *Factory) Close(ctx context.Context) error { return f.comp.Close(ctx) }

// resourceDtor is the generic destructor invoked when canon orchestrates
// terminal-drop on a host-defined resource handle. Type-asserts the
// underlying Go object for an optional Drop(ctx) error method and
// calls it.
func resourceDtor(ctx context.Context, _ *host.ComponentInstance, obj any) error {
	if d_, ok_ := obj.(interface{ Drop(context.Context) error }); ok_ {
		return d_.Drop(ctx)
	}
	return nil
}

func wrapNewHandle(f *Factory) host.Func {
	return func(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, stack []uint64) error {
		state_ := h.UserState().(*instanceState)
		fnType_ := cc.Instance().ExportedFunc("[constructor]handle").Type()
		_ = fnType_
		result_, err_ := state_.impl.NewHandle(ctx)
		if err_ != nil {
			return fmt.Errorf("wacogo/witgen: [constructor]handle: impl returned error: %w", err_)
		}
		oh_, err_ := result_.bind(cc, h)
		if err_ != nil {
			return fmt.Errorf("wacogo/witgen: [constructor]handle: bind failed: %w", err_)
		}
		result_.Invalidate()
		stack[0] = uint64(oh_)
		return nil
	}
}

func wrapHandleRead(f *Factory) host.Func {
	return func(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, stack []uint64) error {
		fnType_ := cc.Instance().ExportedFunc("[method]handle.read").Type()
		_ = fnType_
		selfObj_, ok_ := h.LookupResource(host.ExternHandle(uint32(stack[0])))
		if !ok_ {
			return fmt.Errorf("wacogo/witgen: [method]handle.read: missing rep")
		}
		self_ := selfObj_.(Handle)
		result_, implErr_ := self_.Read(ctx)
		if implErr_ != nil {
			return fmt.Errorf("wacogo/witgen: [method]handle.read: impl returned error: %w", implErr_)
		}
		stack[0] = uint64(result_)
		return nil
	}
}
