// Code generated by wacogo-witgen from cross_resource.wit. DO NOT EDIT.

// Package streams provides Go bindings for the example:demo/streams interface.
package streams

import (
	"context"
	"fmt"

	"github.com/partite-ai/wacogo"
	"github.com/partite-ai/wacogo/host"
)

// streamsWrapper is the concrete type returned by WrapInstance
// as a Streams. Held internally; users hold it via the Streams
// interface.
type streamsWrapper struct {
	callerInst   *host.ComponentInstance
	fnNewHandle  *host.ExportedFunc
	fnHandleRead *host.ExportedFunc
}

// WrapInstance returns a Streams that forwards method calls to
// callee. caller is a Factory-built host instance whose state hosts any
// handles minted by callee during those calls.
func WrapInstance(caller *host.ComponentInstance, callee *wacogo.ComponentInstance) Streams {
	w_ := &streamsWrapper{callerInst: caller}
	w_.fnNewHandle = host.WrapExportedFunc(callee.ExportedFunc("[constructor]handle"))
	w_.fnHandleRead = host.WrapExportedFunc(callee.ExportedFunc("[method]handle.read"))
	return w_
}
func (w *streamsWrapper) NewHandle(ctx context.Context) (*HandleHandle, error) {
	var resVal_ *HandleHandle
	var resErr_ error
	{
		callErr_ := w.fnNewHandle.CallRaw(ctx, w.callerInst,
			func(caller, callee *host.CallContext, stack []uint64) {
			},
			func(caller, callee *host.CallContext, stack []uint64) {
				{
					tr_ := w.fnNewHandle.ResultType(0).(wacogo.TypeOwn).ResourceType
					calleeH_ := uint32(stack[0])
					srcH_, srcErr_ := callee.LookupOwn(tr_, calleeH_)
					if srcErr_ != nil {
						resErr_ = srcErr_
						return
					}
					dstH_, dstErr_ := srcH_.TransferOwn(caller.TransferTarget())
					if dstErr_ != nil {
						resErr_ = dstErr_
						return
					}
					var impl_ Handle
					if obj_, ok_ := dstH_.Type().Instance().LookupExtern(dstH_.Rep()); ok_ {
						if typed_, ok2_ := obj_.(Handle); ok2_ {
							impl_ = typed_
						}
					}
					resVal_ = NewHandleHandleFrom(dstH_, impl_)
				}
			},
		)
		if callErr_ != nil {
			return nil, fmt.Errorf("wacogo/witgen: CallRaw failed: %w", callErr_)
		}
		if resErr_ != nil {
			return nil, resErr_
		}
	}
	return resVal_, nil
}
