// Code generated by wacogo-witgen from divide.wit. DO NOT EDIT.

// Package divide provides Go bindings for the example:demo/divide interface.
package divide

import (
	"context"
	"fmt"

	"github.com/partite-ai/wacogo"
	"github.com/partite-ai/wacogo/host"
)

// Factory builds host-side instances of the Divide interface
// from a Go implementation.
type Factory struct {
	engine *wacogo.Engine
	comp   *host.Component
}

type instanceState struct {
	impl Divide
}

// Deps groups the cross-component dependencies required to instantiate
// Divide. Pass a populated value via NewInstance.
type Deps struct {
}

// NewFactory creates a Factory bound to e. A single Factory may be
// reused to build multiple instances backed by different implementations.
func NewFactory(ctx context.Context, e *wacogo.Engine) (*Factory, error) {
	f_ := &Factory{engine: e}
	b_ := e.NewHostBuilder("example_demo_divide")

	b_.AddFunction("divide", &host.FuncType{
		Params:  []host.Param{{Name: "a", Type: host.U32}, {Name: "b", Type: host.U32}},
		Results: []host.ResultDecl{{Name: "", Type: host.Result{Ok: host.U32, Err: host.String}}},
	}, wrapDivide(f_))

	comp_, err_ := b_.Build(ctx)
	if err_ != nil {
		return nil, err_
	}
	f_.comp = comp_
	return f_, nil
}

// NewInstance creates a fresh component instance backed by impl. Pass
// inst.Core() to wacogo.WithInstanceImport to wire the instance into a
// composite world. deps may be nil only when Divide has no
// imports.
func (f *Factory) NewInstance(ctx context.Context, impl Divide, deps *Deps, opts ...host.InstantiateOption) (*host.ComponentInstance, error) {
	_ = deps
	state_ := &instanceState{impl: impl}
	opts = append(opts, host.WithUserState(state_))
	inst_, err_ := f.comp.Instantiate(ctx, opts...)
	if err_ != nil {
		return nil, err_
	}
	return inst_, nil
}

// Close releases resources shared by the Factory. Existing instances
// remain callable until each is closed individually.
func (f *Factory) Close(ctx context.Context) error { return f.comp.Close(ctx) }

func toGoFlatResultU32String(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, stack []uint64) (ResultU32String, error) {
	resT_ := ty.(wacogo.TypeResult)
	_ = resT_
	disc_ := uint32(stack[0])
	if disc_ == 0 {
		var okVal_ uint32
		okVal_ = uint32(stack[1])
		return ResultU32StringOk{Value: okVal_}, nil
	}
	var errVal_ string
	if tmp_, err_ := toGoFlatString(ctx, cc, h, resT_.Err, stack[1:3]); err_ != nil {
		return nil, err_
	} else {
		errVal_ = tmp_
	}
	return ResultU32StringErr{Value: errVal_}, nil
}

func toGoMemResultU32String(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, ptr uint32) (ResultU32String, error) {
	resT_ := ty.(wacogo.TypeResult)
	_ = resT_
	var disc_ uint8
	if tmp_, ok_ := cc.Memory().ReadByte(ptr); !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: toGoMemResultU32String: discriminant: bad memory read")
	} else {
		disc_ = tmp_
	}
	if disc_ == 0 {
		var okVal_ uint32
		if tmp_, ok_ := cc.Memory().ReadUint32Le(ptr + 4); !ok_ {
			return nil, fmt.Errorf("wacogo/witgen: toGoMemResultU32String: OK arm: bad memory read")
		} else {
			okVal_ = tmp_
		}
		return ResultU32StringOk{Value: okVal_}, nil
	}
	var errVal_ string
	if tmp_, err_ := toGoMemString(ctx, cc, h, resT_.Err, ptr+4); err_ != nil {
		return nil, err_
	} else {
		errVal_ = tmp_
	}
	return ResultU32StringErr{Value: errVal_}, nil
}

func fromGoFlatResultU32String(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, stack []uint64, v ResultU32String) error {
	switch x := v.(type) {
	case ResultU32StringOk:
		stack[0] = 0
		stack[1] = uint64(x.Value)
		stack[2] = 0
	case ResultU32StringErr:
		stack[0] = 1
		if err_ := fromGoFlatString(ctx, cc, h, stack[1:3], x.Value); err_ != nil {
			return err_
		}
	default:
		return fmt.Errorf("wacogo/witgen: fromGoFlatResultU32String: unknown result case")
	}
	return nil
}

func fromGoMemResultU32String(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, ptr uint32, v ResultU32String) error {
	switch x := v.(type) {
	case ResultU32StringOk:
		if ok_ := cc.Memory().WriteByte(ptr, 0); !ok_ {
			return fmt.Errorf("wacogo/witgen: fromGoMemResultU32String: discriminant: bad memory write")
		}
		if ok_ := cc.Memory().WriteUint32Le(ptr+4, x.Value); !ok_ {
			return fmt.Errorf("wacogo/witgen: fromGoMemResultU32String: OK arm: bad memory write")
		}
	case ResultU32StringErr:
		if ok_ := cc.Memory().WriteByte(ptr, 1); !ok_ {
			return fmt.Errorf("wacogo/witgen: fromGoMemResultU32String: discriminant: bad memory write")
		}
		if err_ := fromGoMemString(ctx, cc, h, ptr+4, x.Value); err_ != nil {
			return err_
		}
	default:
		return fmt.Errorf("wacogo/witgen: fromGoMemResultU32String: unknown result case")
	}
	return nil
}

func liftFlatResultU32String(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, stack []uint64) (ResultU32String, error) {
	resT_ := ty.(wacogo.TypeResult)
	_ = resT_
	disc_ := uint32(stack[0])
	if disc_ == 0 {
		var okVal_ uint32
		okVal_ = uint32(stack[1])
		return ResultU32StringOk{Value: okVal_}, nil
	}
	var errVal_ string
	if tmp_, err_ := liftFlatString(ctx, caller, callee, h, resT_.Err, stack[1:3]); err_ != nil {
		return nil, err_
	} else {
		errVal_ = tmp_
	}
	return ResultU32StringErr{Value: errVal_}, nil
}

func liftMemResultU32String(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, ptr uint32) (ResultU32String, error) {
	resT_ := ty.(wacogo.TypeResult)
	_ = resT_
	var disc_ uint8
	if tmp_, ok_ := callee.Memory().ReadByte(ptr); !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: liftMemResultU32String: discriminant: bad memory read")
	} else {
		disc_ = tmp_
	}
	if disc_ == 0 {
		var okVal_ uint32
		if tmp_, ok_ := callee.Memory().ReadUint32Le(ptr + 4); !ok_ {
			return nil, fmt.Errorf("wacogo/witgen: liftMemResultU32String: OK arm: bad memory read")
		} else {
			okVal_ = tmp_
		}
		return ResultU32StringOk{Value: okVal_}, nil
	}
	var errVal_ string
	if tmp_, err_ := liftMemString(ctx, caller, callee, h, resT_.Err, ptr+4); err_ != nil {
		return nil, err_
	} else {
		errVal_ = tmp_
	}
	return ResultU32StringErr{Value: errVal_}, nil
}

func lowerFlatResultU32String(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, stack []uint64, v ResultU32String) error {
	resT_ := ty.(wacogo.TypeResult)
	_ = resT_
	switch x := v.(type) {
	case ResultU32StringOk:
		stack[0] = 0
		stack[1] = uint64(x.Value)
		stack[2] = 0
	case ResultU32StringErr:
		stack[0] = 1
		if err_ := lowerFlatString(ctx, caller, callee, h, resT_.Err, stack[1:3], x.Value); err_ != nil {
			return err_
		}
	default:
		return fmt.Errorf("wacogo/witgen: lowerFlatResultU32String: unknown result case")
	}
	return nil
}

func lowerMemResultU32String(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, ptr uint32, v ResultU32String) error {
	resT_ := ty.(wacogo.TypeResult)
	_ = resT_
	switch x := v.(type) {
	case ResultU32StringOk:
		if ok_ := callee.Memory().WriteByte(ptr, 0); !ok_ {
			return fmt.Errorf("wacogo/witgen: lowerMemResultU32String: discriminant: bad memory write")
		}
		if ok_ := callee.Memory().WriteUint32Le(ptr+4, x.Value); !ok_ {
			return fmt.Errorf("wacogo/witgen: lowerMemResultU32String: OK arm: bad memory write")
		}
	case ResultU32StringErr:
		if ok_ := callee.Memory().WriteByte(ptr, 1); !ok_ {
			return fmt.Errorf("wacogo/witgen: lowerMemResultU32String: discriminant: bad memory write")
		}
		if err_ := lowerMemString(ctx, caller, callee, h, resT_.Err, ptr+4, x.Value); err_ != nil {
			return err_
		}
	default:
		return fmt.Errorf("wacogo/witgen: lowerMemResultU32String: unknown result case")
	}
	return nil
}

func toGoFlatString(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, stack []uint64) (string, error) {
	_ = ty
	ptr_ := uint32(stack[0])
	ln_ := uint32(stack[1])
	bs_, ok_ := cc.Memory().Read(ptr_, ln_)
	if !ok_ {
		return "", fmt.Errorf("wacogo/witgen: toGoFlatString: bad memory read")
	}
	return string(bs_), nil
}

func toGoMemString(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, ptr uint32) (string, error) {
	_ = ty
	var sptr_ uint32
	if tmp_, ok_ := cc.Memory().ReadUint32Le(ptr); !ok_ {
		return "", fmt.Errorf("wacogo/witgen: toGoMemString: string ptr: bad memory read")
	} else {
		sptr_ = tmp_
	}
	var ln_ uint32
	if tmp_, ok_ := cc.Memory().ReadUint32Le(ptr + 4); !ok_ {
		return "", fmt.Errorf("wacogo/witgen: toGoMemString: string len: bad memory read")
	} else {
		ln_ = tmp_
	}
	bs_, ok_ := cc.Memory().Read(sptr_, ln_)
	if !ok_ {
		return "", fmt.Errorf("wacogo/witgen: toGoMemString: bad memory read")
	}
	return string(bs_), nil
}

func fromGoFlatString(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, stack []uint64, v string) error {
	bs_ := []byte(v)
	ptr_, err_ := cc.Realloc(ctx, 0, 0, 1, uint32(len(bs_)))
	if err_ != nil {
		return fmt.Errorf("wacogo/witgen: fromGoFlatString: realloc failed: %w", err_)
	}
	if ok_ := cc.Memory().Write(ptr_, bs_); !ok_ {
		return fmt.Errorf("wacogo/witgen: fromGoFlatString: bad memory write")
	}
	stack[0] = uint64(ptr_)
	stack[1] = uint64(len(bs_))
	return nil
}

func fromGoMemString(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, ptr uint32, v string) error {
	bs_ := []byte(v)
	sptr_, err_ := cc.Realloc(ctx, 0, 0, 1, uint32(len(bs_)))
	if err_ != nil {
		return fmt.Errorf("wacogo/witgen: fromGoMemString: realloc failed: %w", err_)
	}
	if ok_ := cc.Memory().Write(sptr_, bs_); !ok_ {
		return fmt.Errorf("wacogo/witgen: fromGoMemString: bad memory write")
	}
	if ok_ := cc.Memory().WriteUint32Le(ptr, sptr_); !ok_ {
		return fmt.Errorf("wacogo/witgen: fromGoMemString: string ptr: bad memory write")
	}
	if ok_ := cc.Memory().WriteUint32Le(ptr+4, uint32(len(bs_))); !ok_ {
		return fmt.Errorf("wacogo/witgen: fromGoMemString: string len: bad memory write")
	}
	return nil
}

func liftFlatString(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, stack []uint64) (string, error) {
	ptr_ := uint32(stack[0])
	ln_ := uint32(stack[1])
	bs_, ok_ := callee.Memory().Read(ptr_, ln_)
	if !ok_ {
		return "", fmt.Errorf("wacogo/witgen: liftFlatString: bad memory read")
	}
	return string(bs_), nil
}

func liftMemString(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, ptr uint32) (string, error) {
	var sptr_ uint32
	if tmp_, ok_ := callee.Memory().ReadUint32Le(ptr); !ok_ {
		return "", fmt.Errorf("wacogo/witgen: liftMemString: string ptr: bad memory read")
	} else {
		sptr_ = tmp_
	}
	var ln_ uint32
	if tmp_, ok_ := callee.Memory().ReadUint32Le(ptr + 4); !ok_ {
		return "", fmt.Errorf("wacogo/witgen: liftMemString: string len: bad memory read")
	} else {
		ln_ = tmp_
	}
	bs_, ok_ := callee.Memory().Read(sptr_, ln_)
	if !ok_ {
		return "", fmt.Errorf("wacogo/witgen: liftMemString: bad memory read")
	}
	return string(bs_), nil
}

func lowerFlatString(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, stack []uint64, v string) error {
	bs_ := []byte(v)
	ptr_, err_ := callee.Realloc(ctx, 0, 0, 1, uint32(len(bs_)))
	if err_ != nil {
		return fmt.Errorf("wacogo/witgen: lowerFlatString: realloc failed: %w", err_)
	}
	if ok_ := callee.Memory().Write(ptr_, bs_); !ok_ {
		return fmt.Errorf("wacogo/witgen: lowerFlatString: bad memory write")
	}
	stack[0] = uint64(ptr_)
	stack[1] = uint64(len(bs_))
	return nil
}

func lowerMemString(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, ptr uint32, v string) error {
	bs_ := []byte(v)
	sptr_, err_ := callee.Realloc(ctx, 0, 0, 1, uint32(len(bs_)))
	if err_ != nil {
		return fmt.Errorf("wacogo/witgen: lowerMemString: realloc failed: %w", err_)
	}
	if ok_ := callee.Memory().Write(sptr_, bs_); !ok_ {
		return fmt.Errorf("wacogo/witgen: lowerMemString: bad memory write")
	}
	if ok_ := callee.Memory().WriteUint32Le(ptr, sptr_); !ok_ {
		return fmt.Errorf("wacogo/witgen: lowerMemString: string ptr: bad memory write")
	}
	if ok_ := callee.Memory().WriteUint32Le(ptr+4, uint32(len(bs_))); !ok_ {
		return fmt.Errorf("wacogo/witgen: lowerMemString: string len: bad memory write")
	}
	return nil
}

func wrapDivide(f *Factory) host.Func {
	return func(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, stack []uint64) error {
		state_ := h.UserState().(*instanceState)
		fnType_ := cc.Instance().ExportedFunc("divide").Type()
		_ = fnType_
		a := uint32(stack[0])
		b := uint32(stack[1])
		result_, implErr_ := state_.impl.Divide(ctx, a, b)
		if implErr_ != nil {
			return fmt.Errorf("wacogo/witgen: divide: impl returned error: %w", implErr_)
		}
		outPtr_, rerr_ := cc.Realloc(ctx, 0, 0, 4, 12)
		if rerr_ != nil {
			return fmt.Errorf("wacogo/witgen: divide: realloc failed: %w", rerr_)
		}
		if err_ := fromGoMemResultU32String(ctx, cc, h, outPtr_, result_); err_ != nil {
			return err_
		}
		stack[0] = uint64(outPtr_)
		return nil
	}
}
