// Code generated by wacogo-witgen from divide.wit. DO NOT EDIT.

// Package divide provides Go bindings for the example:demo/divide interface.
package divide

import (
	"context"
	"fmt"

	"github.com/partite-ai/wacogo"
	"github.com/partite-ai/wacogo/host"
)

// divideWrapper is the concrete type returned by WrapInstance
// as a Divide. Held internally; users hold it via the Divide
// interface.
type divideWrapper struct {
	callerInst *host.ComponentInstance
	fnDivide   *host.ExportedFunc
}

// WrapInstance returns a Divide that forwards method calls to
// callee. caller is a Factory-built host instance whose state hosts any
// handles minted by callee during those calls.
func WrapInstance(caller *host.ComponentInstance, callee *wacogo.ComponentInstance) Divide {
	w_ := &divideWrapper{callerInst: caller}
	w_.fnDivide = host.WrapExportedFunc(callee.ExportedFunc("divide"))
	return w_
}
func (w *divideWrapper) Divide(ctx context.Context, a uint32, b uint32) (ResultU32String, error) {
	var resVal_ ResultU32String
	var resErr_ error
	arg0_ := a
	arg1_ := b
	{
		callErr_ := w.fnDivide.CallRaw(ctx, w.callerInst,
			func(caller, callee *host.CallContext, stack []uint64) {
				stack[0] = uint64(arg0_)
				stack[1] = uint64(arg1_)
			},
			func(caller, callee *host.CallContext, stack []uint64) {
				if v_, err_ := liftMemResultU32String(ctx, caller, callee, w.callerInst, w.fnDivide.ResultType(0), uint32(stack[0])); err_ != nil {
					resErr_ = err_
					return
				} else {
					resVal_ = v_
				}
			},
		)
		if callErr_ != nil {
			return nil, fmt.Errorf("wacogo/witgen: CallRaw failed: %w", callErr_)
		}
		if resErr_ != nil {
			return nil, resErr_
		}
	}
	return resVal_, nil
}
