// Code generated by wacogo-witgen from divide.wit. DO NOT EDIT.

// Package divide provides Go bindings for the example:demo/divide interface.
package divide

import (
	"context"
)

// InterfaceName is the canonical WIT id of the interface this binding
// was generated from.
const InterfaceName = "example:demo/divide"

// Divide is the Go binding for the example:demo/divide interface.
// Implement it to provide a host-side component, or pass an exported wasm
// instance to WrapInstance to obtain a Divide that calls into wasm.
// Resource-typed parameters and results appear as *<R>Handle values that can
// be passed across component boundaries.
type Divide interface {
	Divide(ctx context.Context, a uint32, b uint32) (ResultU32String, error)
}

// ResultU32String corresponds to a WIT result<...> type.
type ResultU32String interface{ isResultU32String() }
type ResultU32StringOk struct{ Value uint32 }
type ResultU32StringErr struct{ Value string }

func (ResultU32StringOk) isResultU32String()  {}
func (ResultU32StringErr) isResultU32String() {}
