// Code generated by wacogo-witgen from shape.wit. DO NOT EDIT.

// Package shape provides Go bindings for the example:demo/shape interface.
package shape

import (
	"context"
	"fmt"

	"github.com/partite-ai/wacogo"
	"github.com/partite-ai/wacogo/host"
)

// Factory builds host-side instances of the Shape interface
// from a Go implementation.
type Factory struct {
	engine *wacogo.Engine
	comp   *host.Component
}

type instanceState struct {
	impl Shape
}

// Deps groups the cross-component dependencies required to instantiate
// Shape. Pass a populated value via NewInstance.
type Deps struct {
}

// NewFactory creates a Factory bound to e. A single Factory may be
// reused to build multiple instances backed by different implementations.
func NewFactory(ctx context.Context, e *wacogo.Engine) (*Factory, error) {
	f_ := &Factory{engine: e}
	b_ := e.NewHostBuilder("example_demo_shape")

	typPoint_ := b_.AddType("point", host.Record{Fields: []host.Field{{Name: "x", Type: host.U32}, {Name: "y", Type: host.U32}}})
	_ = typPoint_

	typShapeKind_ := b_.AddType("shape-kind", host.Variant{Cases: []host.Case{{Name: "circle", Payload: host.U32}, {Name: "rect", Payload: typPoint_}, {Name: "none", Payload: nil}}})
	_ = typShapeKind_

	b_.AddFunction("describe", &host.FuncType{
		Params:  []host.Param{{Name: "s", Type: typShapeKind_}},
		Results: []host.ResultDecl{{Name: "", Type: host.String}},
	}, wrapDescribe(f_))

	comp_, err_ := b_.Build(ctx)
	if err_ != nil {
		return nil, err_
	}
	f_.comp = comp_
	return f_, nil
}

// NewInstance creates a fresh component instance backed by impl. Pass
// inst.Core() to wacogo.WithInstanceImport to wire the instance into a
// composite world. deps may be nil only when Shape has no
// imports.
func (f *Factory) NewInstance(ctx context.Context, impl Shape, deps *Deps, opts ...host.InstantiateOption) (*host.ComponentInstance, error) {
	_ = deps
	state_ := &instanceState{impl: impl}
	opts = append(opts, host.WithUserState(state_))
	inst_, err_ := f.comp.Instantiate(ctx, opts...)
	if err_ != nil {
		return nil, err_
	}
	return inst_, nil
}

// Close releases resources shared by the Factory. Existing instances
// remain callable until each is closed individually.
func (f *Factory) Close(ctx context.Context) error { return f.comp.Close(ctx) }

func toGoFlatPoint(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, stack []uint64) (Point, error) {
	var v_ Point
	recT_ := ty.(wacogo.TypeRecord)
	_ = recT_
	v_.X = uint32(stack[0])
	v_.Y = uint32(stack[1])
	return v_, nil
}

func toGoMemPoint(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, ptr uint32) (Point, error) {
	var v_ Point
	recT_ := ty.(wacogo.TypeRecord)
	_ = recT_
	if tmp_, ok_ := cc.Memory().ReadUint32Le(ptr); !ok_ {
		return Point{}, fmt.Errorf("wacogo/witgen: toGoMemPoint: field X: bad memory read")
	} else {
		v_.X = tmp_
	}
	if tmp_, ok_ := cc.Memory().ReadUint32Le(ptr + 4); !ok_ {
		return Point{}, fmt.Errorf("wacogo/witgen: toGoMemPoint: field Y: bad memory read")
	} else {
		v_.Y = tmp_
	}
	return v_, nil
}

func fromGoFlatPoint(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, stack []uint64, v Point) error {
	stack[0] = uint64(v.X)
	stack[1] = uint64(v.Y)
	return nil
}

func fromGoMemPoint(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, ptr uint32, v Point) error {
	if ok_ := cc.Memory().WriteUint32Le(ptr, v.X); !ok_ {
		return fmt.Errorf("wacogo/witgen: fromGoMemPoint: field X: bad memory write")
	}
	if ok_ := cc.Memory().WriteUint32Le(ptr+4, v.Y); !ok_ {
		return fmt.Errorf("wacogo/witgen: fromGoMemPoint: field Y: bad memory write")
	}
	return nil
}

func liftFlatPoint(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, stack []uint64) (Point, error) {
	var v_ Point
	recT_ := ty.(wacogo.TypeRecord)
	_ = recT_
	v_.X = uint32(stack[0])
	v_.Y = uint32(stack[1])
	return v_, nil
}

func liftMemPoint(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, ptr uint32) (Point, error) {
	var v_ Point
	recT_ := ty.(wacogo.TypeRecord)
	_ = recT_
	if tmp_, ok_ := callee.Memory().ReadUint32Le(ptr); !ok_ {
		return Point{}, fmt.Errorf("wacogo/witgen: liftMemPoint: field X: bad memory read")
	} else {
		v_.X = tmp_
	}
	if tmp_, ok_ := callee.Memory().ReadUint32Le(ptr + 4); !ok_ {
		return Point{}, fmt.Errorf("wacogo/witgen: liftMemPoint: field Y: bad memory read")
	} else {
		v_.Y = tmp_
	}
	return v_, nil
}

func lowerFlatPoint(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, stack []uint64, v Point) error {
	recT_ := ty.(wacogo.TypeRecord)
	_ = recT_
	stack[0] = uint64(v.X)
	stack[1] = uint64(v.Y)
	return nil
}

func lowerMemPoint(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, ptr uint32, v Point) error {
	recT_ := ty.(wacogo.TypeRecord)
	_ = recT_
	if ok_ := callee.Memory().WriteUint32Le(ptr, v.X); !ok_ {
		return fmt.Errorf("wacogo/witgen: lowerMemPoint: field X: bad memory write")
	}
	if ok_ := callee.Memory().WriteUint32Le(ptr+4, v.Y); !ok_ {
		return fmt.Errorf("wacogo/witgen: lowerMemPoint: field Y: bad memory write")
	}
	return nil
}

func toGoFlatShapeKind(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, stack []uint64) (ShapeKind, error) {
	varT_ := ty.(wacogo.TypeVariant)
	_ = varT_
	disc_ := uint32(stack[0])
	switch disc_ {
	case 0:
		var val uint32
		val = uint32(stack[1])
		return ShapeKindCircle{Value: val}, nil
	case 1:
		var val Point
		if tmp_, err_ := toGoFlatPoint(ctx, cc, h, varT_.Cases[1].Payload, stack[1:3]); err_ != nil {
			return nil, err_
		} else {
			val = tmp_
		}
		return ShapeKindRect{Value: val}, nil
	case 2:
		return ShapeKindNone{}, nil
	}
	return nil, fmt.Errorf("wacogo/witgen: toGoFlatShapeKind: invalid discriminant %d", disc_)
}

func toGoMemShapeKind(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, ptr uint32) (ShapeKind, error) {
	varT_ := ty.(wacogo.TypeVariant)
	_ = varT_
	var disc_ uint8
	if tmp_, ok_ := cc.Memory().ReadByte(ptr); !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: toGoMemShapeKind: discriminant: bad memory read")
	} else {
		disc_ = tmp_
	}
	switch disc_ {
	case 0:
		var val uint32
		if tmp_, ok_ := cc.Memory().ReadUint32Le(ptr + 4); !ok_ {
			return nil, fmt.Errorf("wacogo/witgen: toGoMemShapeKind: case 0 payload: bad memory read")
		} else {
			val = tmp_
		}
		return ShapeKindCircle{Value: val}, nil
	case 1:
		var val Point
		if tmp_, err_ := toGoMemPoint(ctx, cc, h, varT_.Cases[1].Payload, ptr+4); err_ != nil {
			return nil, err_
		} else {
			val = tmp_
		}
		return ShapeKindRect{Value: val}, nil
	case 2:
		return ShapeKindNone{}, nil
	}
	return nil, fmt.Errorf("wacogo/witgen: toGoMemShapeKind: invalid discriminant %d", disc_)
}

func fromGoFlatShapeKind(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, stack []uint64, v ShapeKind) error {
	switch x := v.(type) {
	case ShapeKindCircle:
		stack[0] = 0
		stack[1] = uint64(x.Value)
		stack[2] = 0
	case ShapeKindRect:
		stack[0] = 1
		if err_ := fromGoFlatPoint(ctx, cc, h, stack[1:3], x.Value); err_ != nil {
			return err_
		}
	case ShapeKindNone:
		stack[0] = 2
		_ = x
		stack[1] = 0
		stack[2] = 0
	default:
		return fmt.Errorf("wacogo/witgen: fromGoFlatShapeKind: unknown variant case")
	}
	return nil
}

func fromGoMemShapeKind(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, ptr uint32, v ShapeKind) error {
	switch x := v.(type) {
	case ShapeKindCircle:
		if ok_ := cc.Memory().WriteByte(ptr, uint8(0)); !ok_ {
			return fmt.Errorf("wacogo/witgen: fromGoMemShapeKind: discriminant: bad memory write")
		}
		if ok_ := cc.Memory().WriteUint32Le(ptr+4, x.Value); !ok_ {
			return fmt.Errorf("wacogo/witgen: fromGoMemShapeKind: case 0 payload: bad memory write")
		}
	case ShapeKindRect:
		if ok_ := cc.Memory().WriteByte(ptr, uint8(1)); !ok_ {
			return fmt.Errorf("wacogo/witgen: fromGoMemShapeKind: discriminant: bad memory write")
		}
		if err_ := fromGoMemPoint(ctx, cc, h, ptr+4, x.Value); err_ != nil {
			return err_
		}
	case ShapeKindNone:
		if ok_ := cc.Memory().WriteByte(ptr, uint8(2)); !ok_ {
			return fmt.Errorf("wacogo/witgen: fromGoMemShapeKind: discriminant: bad memory write")
		}
		_ = x
	default:
		return fmt.Errorf("wacogo/witgen: fromGoMemShapeKind: unknown variant case")
	}
	return nil
}

func liftFlatShapeKind(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, stack []uint64) (ShapeKind, error) {
	varT_ := ty.(wacogo.TypeVariant)
	_ = varT_
	disc_ := uint32(stack[0])
	switch disc_ {
	case 0:
		var val uint32
		val = uint32(stack[1])
		return ShapeKindCircle{Value: val}, nil
	case 1:
		var val Point
		if tmp_, err_ := liftFlatPoint(ctx, caller, callee, h, varT_.Cases[1].Payload, stack[1:3]); err_ != nil {
			return nil, err_
		} else {
			val = tmp_
		}
		return ShapeKindRect{Value: val}, nil
	case 2:
		return ShapeKindNone{}, nil
	}
	return nil, fmt.Errorf("wacogo/witgen: liftFlatShapeKind: invalid discriminant %d", disc_)
}

func liftMemShapeKind(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, ptr uint32) (ShapeKind, error) {
	varT_ := ty.(wacogo.TypeVariant)
	_ = varT_
	var disc_ uint8
	if tmp_, ok_ := callee.Memory().ReadByte(ptr); !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: liftMemShapeKind: discriminant: bad memory read")
	} else {
		disc_ = tmp_
	}
	switch disc_ {
	case 0:
		var val uint32
		if tmp_, ok_ := callee.Memory().ReadUint32Le(ptr + 4); !ok_ {
			return nil, fmt.Errorf("wacogo/witgen: liftMemShapeKind: case 0 payload: bad memory read")
		} else {
			val = tmp_
		}
		return ShapeKindCircle{Value: val}, nil
	case 1:
		var val Point
		if tmp_, err_ := liftMemPoint(ctx, caller, callee, h, varT_.Cases[1].Payload, ptr+4); err_ != nil {
			return nil, err_
		} else {
			val = tmp_
		}
		return ShapeKindRect{Value: val}, nil
	case 2:
		return ShapeKindNone{}, nil
	}
	return nil, fmt.Errorf("wacogo/witgen: liftMemShapeKind: invalid discriminant %d", disc_)
}

func lowerFlatShapeKind(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, stack []uint64, v ShapeKind) error {
	varT_ := ty.(wacogo.TypeVariant)
	_ = varT_
	switch x := v.(type) {
	case ShapeKindCircle:
		stack[0] = 0
		stack[1] = uint64(x.Value)
		stack[2] = 0
	case ShapeKindRect:
		stack[0] = 1
		if err_ := lowerFlatPoint(ctx, caller, callee, h, varT_.Cases[1].Payload, stack[1:3], x.Value); err_ != nil {
			return err_
		}
	case ShapeKindNone:
		stack[0] = 2
		_ = x
		stack[1] = 0
		stack[2] = 0
	default:
		return fmt.Errorf("wacogo/witgen: lowerFlatShapeKind: unknown variant case")
	}
	return nil
}

func lowerMemShapeKind(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, ptr uint32, v ShapeKind) error {
	varT_ := ty.(wacogo.TypeVariant)
	_ = varT_
	switch x := v.(type) {
	case ShapeKindCircle:
		if ok_ := callee.Memory().WriteByte(ptr, uint8(0)); !ok_ {
			return fmt.Errorf("wacogo/witgen: lowerMemShapeKind: discriminant: bad memory write")
		}
		if ok_ := callee.Memory().WriteUint32Le(ptr+4, x.Value); !ok_ {
			return fmt.Errorf("wacogo/witgen: lowerMemShapeKind: case 0 payload: bad memory write")
		}
	case ShapeKindRect:
		if ok_ := callee.Memory().WriteByte(ptr, uint8(1)); !ok_ {
			return fmt.Errorf("wacogo/witgen: lowerMemShapeKind: discriminant: bad memory write")
		}
		if err_ := lowerMemPoint(ctx, caller, callee, h, varT_.Cases[1].Payload, ptr+4, x.Value); err_ != nil {
			return err_
		}
	case ShapeKindNone:
		if ok_ := callee.Memory().WriteByte(ptr, uint8(2)); !ok_ {
			return fmt.Errorf("wacogo/witgen: lowerMemShapeKind: discriminant: bad memory write")
		}
		_ = x
	default:
		return fmt.Errorf("wacogo/witgen: lowerMemShapeKind: unknown variant case")
	}
	return nil
}

func toGoFlatString(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, stack []uint64) (string, error) {
	_ = ty
	ptr_ := uint32(stack[0])
	ln_ := uint32(stack[1])
	bs_, ok_ := cc.Memory().Read(ptr_, ln_)
	if !ok_ {
		return "", fmt.Errorf("wacogo/witgen: toGoFlatString: bad memory read")
	}
	return string(bs_), nil
}

func toGoMemString(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, ptr uint32) (string, error) {
	_ = ty
	var sptr_ uint32
	if tmp_, ok_ := cc.Memory().ReadUint32Le(ptr); !ok_ {
		return "", fmt.Errorf("wacogo/witgen: toGoMemString: string ptr: bad memory read")
	} else {
		sptr_ = tmp_
	}
	var ln_ uint32
	if tmp_, ok_ := cc.Memory().ReadUint32Le(ptr + 4); !ok_ {
		return "", fmt.Errorf("wacogo/witgen: toGoMemString: string len: bad memory read")
	} else {
		ln_ = tmp_
	}
	bs_, ok_ := cc.Memory().Read(sptr_, ln_)
	if !ok_ {
		return "", fmt.Errorf("wacogo/witgen: toGoMemString: bad memory read")
	}
	return string(bs_), nil
}

func fromGoFlatString(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, stack []uint64, v string) error {
	bs_ := []byte(v)
	ptr_, err_ := cc.Realloc(ctx, 0, 0, 1, uint32(len(bs_)))
	if err_ != nil {
		return fmt.Errorf("wacogo/witgen: fromGoFlatString: realloc failed: %w", err_)
	}
	if ok_ := cc.Memory().Write(ptr_, bs_); !ok_ {
		return fmt.Errorf("wacogo/witgen: fromGoFlatString: bad memory write")
	}
	stack[0] = uint64(ptr_)
	stack[1] = uint64(len(bs_))
	return nil
}

func fromGoMemString(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, ptr uint32, v string) error {
	bs_ := []byte(v)
	sptr_, err_ := cc.Realloc(ctx, 0, 0, 1, uint32(len(bs_)))
	if err_ != nil {
		return fmt.Errorf("wacogo/witgen: fromGoMemString: realloc failed: %w", err_)
	}
	if ok_ := cc.Memory().Write(sptr_, bs_); !ok_ {
		return fmt.Errorf("wacogo/witgen: fromGoMemString: bad memory write")
	}
	if ok_ := cc.Memory().WriteUint32Le(ptr, sptr_); !ok_ {
		return fmt.Errorf("wacogo/witgen: fromGoMemString: string ptr: bad memory write")
	}
	if ok_ := cc.Memory().WriteUint32Le(ptr+4, uint32(len(bs_))); !ok_ {
		return fmt.Errorf("wacogo/witgen: fromGoMemString: string len: bad memory write")
	}
	return nil
}

func liftFlatString(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, stack []uint64) (string, error) {
	ptr_ := uint32(stack[0])
	ln_ := uint32(stack[1])
	bs_, ok_ := callee.Memory().Read(ptr_, ln_)
	if !ok_ {
		return "", fmt.Errorf("wacogo/witgen: liftFlatString: bad memory read")
	}
	return string(bs_), nil
}

func liftMemString(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, ptr uint32) (string, error) {
	var sptr_ uint32
	if tmp_, ok_ := callee.Memory().ReadUint32Le(ptr); !ok_ {
		return "", fmt.Errorf("wacogo/witgen: liftMemString: string ptr: bad memory read")
	} else {
		sptr_ = tmp_
	}
	var ln_ uint32
	if tmp_, ok_ := callee.Memory().ReadUint32Le(ptr + 4); !ok_ {
		return "", fmt.Errorf("wacogo/witgen: liftMemString: string len: bad memory read")
	} else {
		ln_ = tmp_
	}
	bs_, ok_ := callee.Memory().Read(sptr_, ln_)
	if !ok_ {
		return "", fmt.Errorf("wacogo/witgen: liftMemString: bad memory read")
	}
	return string(bs_), nil
}

func lowerFlatString(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, stack []uint64, v string) error {
	bs_ := []byte(v)
	ptr_, err_ := callee.Realloc(ctx, 0, 0, 1, uint32(len(bs_)))
	if err_ != nil {
		return fmt.Errorf("wacogo/witgen: lowerFlatString: realloc failed: %w", err_)
	}
	if ok_ := callee.Memory().Write(ptr_, bs_); !ok_ {
		return fmt.Errorf("wacogo/witgen: lowerFlatString: bad memory write")
	}
	stack[0] = uint64(ptr_)
	stack[1] = uint64(len(bs_))
	return nil
}

func lowerMemString(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, ptr uint32, v string) error {
	bs_ := []byte(v)
	sptr_, err_ := callee.Realloc(ctx, 0, 0, 1, uint32(len(bs_)))
	if err_ != nil {
		return fmt.Errorf("wacogo/witgen: lowerMemString: realloc failed: %w", err_)
	}
	if ok_ := callee.Memory().Write(sptr_, bs_); !ok_ {
		return fmt.Errorf("wacogo/witgen: lowerMemString: bad memory write")
	}
	if ok_ := callee.Memory().WriteUint32Le(ptr, sptr_); !ok_ {
		return fmt.Errorf("wacogo/witgen: lowerMemString: string ptr: bad memory write")
	}
	if ok_ := callee.Memory().WriteUint32Le(ptr+4, uint32(len(bs_))); !ok_ {
		return fmt.Errorf("wacogo/witgen: lowerMemString: string len: bad memory write")
	}
	return nil
}

func wrapDescribe(f *Factory) host.Func {
	return func(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, stack []uint64) error {
		state_ := h.UserState().(*instanceState)
		fnType_ := cc.Instance().ExportedFunc("describe").Type()
		_ = fnType_
		var s ShapeKind
		{
			v_, err_ := toGoFlatShapeKind(ctx, cc, h, fnType_.Params[0].Type, stack[0:3])
			if err_ != nil {
				return err_
			}
			s = v_
		}
		result_, implErr_ := state_.impl.Describe(ctx, s)
		if implErr_ != nil {
			return fmt.Errorf("wacogo/witgen: describe: impl returned error: %w", implErr_)
		}
		outPtr_, rerr_ := cc.Realloc(ctx, 0, 0, 4, 8)
		if rerr_ != nil {
			return fmt.Errorf("wacogo/witgen: describe: realloc failed: %w", rerr_)
		}
		if err_ := fromGoMemString(ctx, cc, h, outPtr_, result_); err_ != nil {
			return err_
		}
		stack[0] = uint64(outPtr_)
		return nil
	}
}
