// Code generated by wacogo-witgen from shape.wit. DO NOT EDIT.

// Package shape provides Go bindings for the example:demo/shape interface.
package shape

import (
	"context"
	"fmt"

	"github.com/partite-ai/wacogo"
	"github.com/partite-ai/wacogo/host"
)

// shapeWrapper is the concrete type returned by WrapInstance
// as a Shape. Held internally; users hold it via the Shape
// interface.
type shapeWrapper struct {
	callerInst *host.ComponentInstance
	fnDescribe *host.ExportedFunc
}

// WrapInstance returns a Shape that forwards method calls to
// callee. caller is a Factory-built host instance whose state hosts any
// handles minted by callee during those calls.
func WrapInstance(caller *host.ComponentInstance, callee *wacogo.ComponentInstance) Shape {
	w_ := &shapeWrapper{callerInst: caller}
	w_.fnDescribe = host.WrapExportedFunc(callee.ExportedFunc("describe"))
	return w_
}
func (w *shapeWrapper) Describe(ctx context.Context, s ShapeKind) (string, error) {
	var resVal_ string
	var resErr_ error
	arg0_ := s
	{
		callErr_ := w.fnDescribe.CallRaw(ctx, w.callerInst,
			func(caller, callee *host.CallContext, stack []uint64) {
				if err_ := lowerFlatShapeKind(ctx, caller, callee, w.callerInst, w.fnDescribe.ParamType(0), stack[0:3], arg0_); err_ != nil {
					resErr_ = err_
					return
				}
			},
			func(caller, callee *host.CallContext, stack []uint64) {
				if v_, err_ := liftMemString(ctx, caller, callee, w.callerInst, w.fnDescribe.ResultType(0), uint32(stack[0])); err_ != nil {
					resErr_ = err_
					return
				} else {
					resVal_ = v_
				}
			},
		)
		if callErr_ != nil {
			return "", fmt.Errorf("wacogo/witgen: CallRaw failed: %w", callErr_)
		}
		if resErr_ != nil {
			return "", resErr_
		}
	}
	return resVal_, nil
}
