// Code generated by wacogo-witgen from shape.wit. DO NOT EDIT.

// Package shape provides Go bindings for the example:demo/shape interface.
package shape

import (
	"context"
)

// InterfaceName is the canonical WIT id of the interface this binding
// was generated from.
const InterfaceName = "example:demo/shape"

// Shape is the Go binding for the example:demo/shape interface.
// Implement it to provide a host-side component, or pass an exported wasm
// instance to WrapInstance to obtain a Shape that calls into wasm.
// Resource-typed parameters and results appear as *<R>Handle values that can
// be passed across component boundaries.
type Shape interface {
	Describe(ctx context.Context, s ShapeKind) (string, error)
}

// Point corresponds to the WIT record point.
type Point struct {
	X uint32
	Y uint32
}

// ShapeKind corresponds to the WIT variant shape-kind. Sealed:
// only the case structs below satisfy this interface.
type ShapeKind interface{ isShapeKind() }

// ShapeKindCircle is the "circle" case of ShapeKind.
type ShapeKindCircle struct {
	Value uint32
}

func (ShapeKindCircle) isShapeKind() {}

// ShapeKindRect is the "rect" case of ShapeKind.
type ShapeKindRect struct {
	Value Point
}

func (ShapeKindRect) isShapeKind() {}

// ShapeKindNone is the "none" case of ShapeKind.
type ShapeKindNone struct {
}

func (ShapeKindNone) isShapeKind() {}
