// Code generated by wacogo-witgen from compounds.wit. DO NOT EDIT.

// Package compounds provides Go bindings for the example:demo/compounds interface.
package compounds

import (
	"context"
	"fmt"

	"github.com/partite-ai/wacogo"
	"github.com/partite-ai/wacogo/host"
)

// Factory builds host-side instances of the Compounds interface
// from a Go implementation.
type Factory struct {
	engine    *wacogo.Engine
	comp      *host.Component
	counterRT *host.ResourceType
}

type instanceState struct {
	impl      Compounds
	counterTR *wacogo.TypeResource
}

// Deps groups the cross-component dependencies required to instantiate
// Compounds. Pass a populated value via NewInstance.
type Deps struct {
}

// NewFactory creates a Factory bound to e. A single Factory may be
// reused to build multiple instances backed by different implementations.
func NewFactory(ctx context.Context, e *wacogo.Engine) (*Factory, error) {
	f_ := &Factory{engine: e}
	b_ := e.NewHostBuilder("example_demo_compounds")

	f_.counterRT = b_.AddResource("counter", resourceDtor)

	typRecordWithCounter_ := b_.AddType("record-with-counter", host.Record{Fields: []host.Field{{Name: "c", Type: f_.counterRT.Own()}}})
	_ = typRecordWithCounter_

	b_.AddFunction("box-counter", &host.FuncType{
		Params:  []host.Param{{Name: "c", Type: f_.counterRT.Own()}},
		Results: []host.ResultDecl{{Name: "", Type: typRecordWithCounter_}},
	}, wrapBoxCounter(f_))

	b_.AddFunction("new-counters", &host.FuncType{
		Params:  []host.Param{{Name: "starts", Type: host.List{Elem: host.U32}}},
		Results: []host.ResultDecl{{Name: "", Type: host.List{Elem: f_.counterRT.Own()}}},
	}, wrapNewCounters(f_))

	b_.AddFunction("[constructor]counter", &host.FuncType{
		Params:  []host.Param{{Name: "start", Type: host.U32}},
		Results: []host.ResultDecl{{Name: "", Type: f_.counterRT.Own()}},
	}, wrapNewCounter(f_))

	b_.AddFunction("[method]counter.get", &host.FuncType{
		Params:  []host.Param{{Name: "self", Type: f_.counterRT.Borrow()}},
		Results: []host.ResultDecl{{Name: "", Type: host.U32}},
	}, wrapCounterGet(f_))

	comp_, err_ := b_.Build(ctx)
	if err_ != nil {
		return nil, err_
	}
	f_.comp = comp_
	return f_, nil
}

// NewInstance creates a fresh component instance backed by impl. Pass
// inst.Core() to wacogo.WithInstanceImport to wire the instance into a
// composite world. deps may be nil only when Compounds has no
// imports.
func (f *Factory) NewInstance(ctx context.Context, impl Compounds, deps *Deps, opts ...host.InstantiateOption) (*host.ComponentInstance, error) {
	_ = deps
	state_ := &instanceState{impl: impl}
	opts = append(opts, host.WithUserState(state_))
	inst_, err_ := f.comp.Instantiate(ctx, opts...)
	if err_ != nil {
		return nil, err_
	}
	state_.counterTR = inst_.Core().ExportedType("counter").(*wacogo.TypeResource)
	return inst_, nil
}

// Close releases resources shared by the Factory. Existing instances
// remain callable until each is closed individually.
func (f *Factory) Close(ctx context.Context) error { return f.comp.Close(ctx) }

// resourceDtor is the generic destructor invoked when canon orchestrates
// terminal-drop on a host-defined resource handle. Type-asserts the
// underlying Go object for an optional Drop(ctx) error method and
// calls it.
func resourceDtor(ctx context.Context, _ *host.ComponentInstance, obj any) error {
	if d_, ok_ := obj.(interface{ Drop(context.Context) error }); ok_ {
		return d_.Drop(ctx)
	}
	return nil
}

func toGoFlatListCounter(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, stack []uint64) ([]*CounterHandle, error) {
	lstT_ := ty.(wacogo.TypeList)
	_ = lstT_
	ptr_ := uint32(stack[0])
	ln_ := uint32(stack[1])
	out_ := make([]*CounterHandle, ln_)
	for i_ := uint32(0); i_ < ln_; i_++ {
		{
			var oh_ uint32
			if tmp_, ok_ := cc.Memory().ReadUint32Le(ptr_ + i_*4); !ok_ {
				return nil, fmt.Errorf("wacogo/witgen: toGoFlatListCounter: elem: handle: bad memory read")
			} else {
				oh_ = tmp_
			}
			tbl_ := lstT_.Elem.(wacogo.TypeOwn).ResourceType
			rh_, lookupErr_ := cc.LookupBorrowable(tbl_, oh_)
			if lookupErr_ != nil {
				return nil, lookupErr_
			}
			var impl_ Counter
			if obj_, ok_ := rh_.Type().Instance().LookupExtern(rh_.Rep()); ok_ {
				if typed_, ok2_ := obj_.(Counter); ok2_ {
					impl_ = typed_
				}
			}
			out_[i_] = NewCounterHandleFrom(rh_, impl_)
		}
	}
	return out_, nil
}

func toGoMemListCounter(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, ptr uint32) ([]*CounterHandle, error) {
	lstT_ := ty.(wacogo.TypeList)
	_ = lstT_
	var lptr_ uint32
	if tmp_, ok_ := cc.Memory().ReadUint32Le(ptr); !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: toGoMemListCounter: list ptr: bad memory read")
	} else {
		lptr_ = tmp_
	}
	var ln_ uint32
	if tmp_, ok_ := cc.Memory().ReadUint32Le(ptr + 4); !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: toGoMemListCounter: list len: bad memory read")
	} else {
		ln_ = tmp_
	}
	out_ := make([]*CounterHandle, ln_)
	for i_ := uint32(0); i_ < ln_; i_++ {
		{
			var oh_ uint32
			if tmp_, ok_ := cc.Memory().ReadUint32Le(lptr_ + i_*4); !ok_ {
				return nil, fmt.Errorf("wacogo/witgen: toGoMemListCounter: list elem: handle: bad memory read")
			} else {
				oh_ = tmp_
			}
			tbl_ := lstT_.Elem.(wacogo.TypeOwn).ResourceType
			rh_, lookupErr_ := cc.LookupBorrowable(tbl_, oh_)
			if lookupErr_ != nil {
				return nil, lookupErr_
			}
			var impl_ Counter
			if obj_, ok_ := rh_.Type().Instance().LookupExtern(rh_.Rep()); ok_ {
				if typed_, ok2_ := obj_.(Counter); ok2_ {
					impl_ = typed_
				}
			}
			out_[i_] = NewCounterHandleFrom(rh_, impl_)
		}
	}
	return out_, nil
}

func fromGoFlatListCounter(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, stack []uint64, v []*CounterHandle) error {
	ln_ := uint32(len(v))
	ptr_, err_ := cc.Realloc(ctx, 0, 0, 4, ln_*4)
	if err_ != nil {
		return fmt.Errorf("wacogo/witgen: fromGoFlatListCounter: realloc failed: %w", err_)
	}
	for i_ := uint32(0); i_ < ln_; i_++ {
		{
			oh_, err_ := v[i_].bind(cc, h)
			if err_ != nil {
				return err_
			}
			v[i_].Invalidate()
			if ok_ := cc.Memory().WriteUint32Le(ptr_+i_*4, oh_); !ok_ {
				return fmt.Errorf("wacogo/witgen: fromGoFlatListCounter: list elem: handle: bad memory write")
			}
		}
	}
	stack[0] = uint64(ptr_)
	stack[1] = uint64(ln_)
	return nil
}

func fromGoMemListCounter(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, ptr uint32, v []*CounterHandle) error {
	ln_ := uint32(len(v))
	lptr_, err_ := cc.Realloc(ctx, 0, 0, 4, ln_*4)
	if err_ != nil {
		return fmt.Errorf("wacogo/witgen: fromGoMemListCounter: realloc failed: %w", err_)
	}
	for i_ := uint32(0); i_ < ln_; i_++ {
		{
			oh_, err_ := v[i_].bind(cc, h)
			if err_ != nil {
				return err_
			}
			v[i_].Invalidate()
			if ok_ := cc.Memory().WriteUint32Le(lptr_+i_*4, oh_); !ok_ {
				return fmt.Errorf("wacogo/witgen: fromGoMemListCounter: list elem: handle: bad memory write")
			}
		}
	}
	if ok_ := cc.Memory().WriteUint32Le(ptr, lptr_); !ok_ {
		return fmt.Errorf("wacogo/witgen: fromGoMemListCounter: list ptr: bad memory write")
	}
	if ok_ := cc.Memory().WriteUint32Le(ptr+4, ln_); !ok_ {
		return fmt.Errorf("wacogo/witgen: fromGoMemListCounter: list len: bad memory write")
	}
	return nil
}

func liftFlatListCounter(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, stack []uint64) ([]*CounterHandle, error) {
	lstT_ := ty.(wacogo.TypeList)
	_ = lstT_
	ptr_ := uint32(stack[0])
	ln_ := uint32(stack[1])
	out_ := make([]*CounterHandle, ln_)
	for i_ := uint32(0); i_ < ln_; i_++ {
		{
			var calleeOh_ uint32
			if tmp_, ok_ := callee.Memory().ReadUint32Le(ptr_ + i_*4); !ok_ {
				return nil, fmt.Errorf("wacogo/witgen: liftFlatListCounter: elem: handle: bad memory read")
			} else {
				calleeOh_ = tmp_
			}
			tr_ := lstT_.Elem.(wacogo.TypeOwn).ResourceType
			srcH_, srcErr_ := callee.LookupOwn(tr_, calleeOh_)
			if srcErr_ != nil {
				return nil, srcErr_
			}
			dstH_, dstErr_ := srcH_.TransferOwn(caller.TransferTarget())
			if dstErr_ != nil {
				return nil, dstErr_
			}
			var impl_ Counter
			if obj_, ok_ := dstH_.Type().Instance().LookupExtern(dstH_.Rep()); ok_ {
				if typed_, ok2_ := obj_.(Counter); ok2_ {
					impl_ = typed_
				}
			}
			out_[i_] = NewCounterHandleFrom(dstH_, impl_)
		}
	}
	return out_, nil
}

func liftMemListCounter(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, ptr uint32) ([]*CounterHandle, error) {
	lstT_ := ty.(wacogo.TypeList)
	_ = lstT_
	var lptr_ uint32
	if tmp_, ok_ := callee.Memory().ReadUint32Le(ptr); !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: liftMemListCounter: list ptr: bad memory read")
	} else {
		lptr_ = tmp_
	}
	var ln_ uint32
	if tmp_, ok_ := callee.Memory().ReadUint32Le(ptr + 4); !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: liftMemListCounter: list len: bad memory read")
	} else {
		ln_ = tmp_
	}
	out_ := make([]*CounterHandle, ln_)
	for i_ := uint32(0); i_ < ln_; i_++ {
		{
			var calleeOh_ uint32
			if tmp_, ok_ := callee.Memory().ReadUint32Le(lptr_ + i_*4); !ok_ {
				return nil, fmt.Errorf("wacogo/witgen: liftMemListCounter: list elem: handle: bad memory read")
			} else {
				calleeOh_ = tmp_
			}
			tr_ := lstT_.Elem.(wacogo.TypeOwn).ResourceType
			srcH_, srcErr_ := callee.LookupOwn(tr_, calleeOh_)
			if srcErr_ != nil {
				return nil, srcErr_
			}
			dstH_, dstErr_ := srcH_.TransferOwn(caller.TransferTarget())
			if dstErr_ != nil {
				return nil, dstErr_
			}
			var impl_ Counter
			if obj_, ok_ := dstH_.Type().Instance().LookupExtern(dstH_.Rep()); ok_ {
				if typed_, ok2_ := obj_.(Counter); ok2_ {
					impl_ = typed_
				}
			}
			out_[i_] = NewCounterHandleFrom(dstH_, impl_)
		}
	}
	return out_, nil
}

func lowerFlatListCounter(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, stack []uint64, v []*CounterHandle) error {
	lstT_ := ty.(wacogo.TypeList)
	_ = lstT_
	ln_ := uint32(len(v))
	ptr_, err_ := callee.Realloc(ctx, 0, 0, 4, ln_*4)
	if err_ != nil {
		return fmt.Errorf("wacogo/witgen: lowerFlatListCounter: realloc failed: %w", err_)
	}
	for i_ := uint32(0); i_ < ln_; i_++ {
		{
			callerH_, err_ := v[i_].bind(caller, h)
			if err_ != nil {
				return err_
			}
			tr_ := lstT_.Elem.(wacogo.TypeOwn).ResourceType
			srcH_, err2_ := caller.LookupOwn(tr_, callerH_)
			if err2_ != nil {
				return err2_
			}
			dstH_, err3_ := srcH_.TransferOwn(callee.TransferTarget())
			if err3_ != nil {
				return err3_
			}
			v[i_].Invalidate()
			if ok_ := callee.Memory().WriteUint32Le(ptr_+i_*4, dstH_.HandleID()); !ok_ {
				return fmt.Errorf("wacogo/witgen: lowerFlatListCounter: list elem: handle: bad memory write")
			}
		}
	}
	stack[0] = uint64(ptr_)
	stack[1] = uint64(ln_)
	return nil
}

func lowerMemListCounter(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, ptr uint32, v []*CounterHandle) error {
	lstT_ := ty.(wacogo.TypeList)
	_ = lstT_
	ln_ := uint32(len(v))
	lptr_, err_ := callee.Realloc(ctx, 0, 0, 4, ln_*4)
	if err_ != nil {
		return fmt.Errorf("wacogo/witgen: lowerMemListCounter: realloc failed: %w", err_)
	}
	for i_ := uint32(0); i_ < ln_; i_++ {
		{
			callerH_, err_ := v[i_].bind(caller, h)
			if err_ != nil {
				return err_
			}
			tr_ := lstT_.Elem.(wacogo.TypeOwn).ResourceType
			srcH_, err2_ := caller.LookupOwn(tr_, callerH_)
			if err2_ != nil {
				return err2_
			}
			dstH_, err3_ := srcH_.TransferOwn(callee.TransferTarget())
			if err3_ != nil {
				return err3_
			}
			v[i_].Invalidate()
			if ok_ := callee.Memory().WriteUint32Le(lptr_+i_*4, dstH_.HandleID()); !ok_ {
				return fmt.Errorf("wacogo/witgen: lowerMemListCounter: list elem: handle: bad memory write")
			}
		}
	}
	if ok_ := callee.Memory().WriteUint32Le(ptr, lptr_); !ok_ {
		return fmt.Errorf("wacogo/witgen: lowerMemListCounter: list ptr: bad memory write")
	}
	if ok_ := callee.Memory().WriteUint32Le(ptr+4, ln_); !ok_ {
		return fmt.Errorf("wacogo/witgen: lowerMemListCounter: list len: bad memory write")
	}
	return nil
}

func toGoFlatListU32(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, stack []uint64) ([]uint32, error) {
	lstT_ := ty.(wacogo.TypeList)
	_ = lstT_
	ptr_ := uint32(stack[0])
	ln_ := uint32(stack[1])
	out_ := make([]uint32, ln_)
	for i_ := uint32(0); i_ < ln_; i_++ {
		if tmp_, ok_ := cc.Memory().ReadUint32Le(ptr_ + i_*4); !ok_ {
			return nil, fmt.Errorf("wacogo/witgen: toGoFlatListU32: elem: bad memory read")
		} else {
			out_[i_] = tmp_
		}
	}
	return out_, nil
}

func toGoMemListU32(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, ptr uint32) ([]uint32, error) {
	lstT_ := ty.(wacogo.TypeList)
	_ = lstT_
	var lptr_ uint32
	if tmp_, ok_ := cc.Memory().ReadUint32Le(ptr); !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: toGoMemListU32: list ptr: bad memory read")
	} else {
		lptr_ = tmp_
	}
	var ln_ uint32
	if tmp_, ok_ := cc.Memory().ReadUint32Le(ptr + 4); !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: toGoMemListU32: list len: bad memory read")
	} else {
		ln_ = tmp_
	}
	out_ := make([]uint32, ln_)
	for i_ := uint32(0); i_ < ln_; i_++ {
		if tmp_, ok_ := cc.Memory().ReadUint32Le(lptr_ + i_*4); !ok_ {
			return nil, fmt.Errorf("wacogo/witgen: toGoMemListU32: list elem: bad memory read")
		} else {
			out_[i_] = tmp_
		}
	}
	return out_, nil
}

func fromGoFlatListU32(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, stack []uint64, v []uint32) error {
	ln_ := uint32(len(v))
	ptr_, err_ := cc.Realloc(ctx, 0, 0, 4, ln_*4)
	if err_ != nil {
		return fmt.Errorf("wacogo/witgen: fromGoFlatListU32: realloc failed: %w", err_)
	}
	for i_ := uint32(0); i_ < ln_; i_++ {
		if ok_ := cc.Memory().WriteUint32Le(ptr_+i_*4, v[i_]); !ok_ {
			return fmt.Errorf("wacogo/witgen: fromGoFlatListU32: list elem: bad memory write")
		}
	}
	stack[0] = uint64(ptr_)
	stack[1] = uint64(ln_)
	return nil
}

func fromGoMemListU32(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, ptr uint32, v []uint32) error {
	ln_ := uint32(len(v))
	lptr_, err_ := cc.Realloc(ctx, 0, 0, 4, ln_*4)
	if err_ != nil {
		return fmt.Errorf("wacogo/witgen: fromGoMemListU32: realloc failed: %w", err_)
	}
	for i_ := uint32(0); i_ < ln_; i_++ {
		if ok_ := cc.Memory().WriteUint32Le(lptr_+i_*4, v[i_]); !ok_ {
			return fmt.Errorf("wacogo/witgen: fromGoMemListU32: list elem: bad memory write")
		}
	}
	if ok_ := cc.Memory().WriteUint32Le(ptr, lptr_); !ok_ {
		return fmt.Errorf("wacogo/witgen: fromGoMemListU32: list ptr: bad memory write")
	}
	if ok_ := cc.Memory().WriteUint32Le(ptr+4, ln_); !ok_ {
		return fmt.Errorf("wacogo/witgen: fromGoMemListU32: list len: bad memory write")
	}
	return nil
}

func liftFlatListU32(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, stack []uint64) ([]uint32, error) {
	lstT_ := ty.(wacogo.TypeList)
	_ = lstT_
	ptr_ := uint32(stack[0])
	ln_ := uint32(stack[1])
	out_ := make([]uint32, ln_)
	for i_ := uint32(0); i_ < ln_; i_++ {
		if tmp_, ok_ := callee.Memory().ReadUint32Le(ptr_ + i_*4); !ok_ {
			return nil, fmt.Errorf("wacogo/witgen: liftFlatListU32: elem: bad memory read")
		} else {
			out_[i_] = tmp_
		}
	}
	return out_, nil
}

func liftMemListU32(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, ptr uint32) ([]uint32, error) {
	lstT_ := ty.(wacogo.TypeList)
	_ = lstT_
	var lptr_ uint32
	if tmp_, ok_ := callee.Memory().ReadUint32Le(ptr); !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: liftMemListU32: list ptr: bad memory read")
	} else {
		lptr_ = tmp_
	}
	var ln_ uint32
	if tmp_, ok_ := callee.Memory().ReadUint32Le(ptr + 4); !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: liftMemListU32: list len: bad memory read")
	} else {
		ln_ = tmp_
	}
	out_ := make([]uint32, ln_)
	for i_ := uint32(0); i_ < ln_; i_++ {
		if tmp_, ok_ := callee.Memory().ReadUint32Le(lptr_ + i_*4); !ok_ {
			return nil, fmt.Errorf("wacogo/witgen: liftMemListU32: list elem: bad memory read")
		} else {
			out_[i_] = tmp_
		}
	}
	return out_, nil
}

func lowerFlatListU32(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, stack []uint64, v []uint32) error {
	lstT_ := ty.(wacogo.TypeList)
	_ = lstT_
	ln_ := uint32(len(v))
	ptr_, err_ := callee.Realloc(ctx, 0, 0, 4, ln_*4)
	if err_ != nil {
		return fmt.Errorf("wacogo/witgen: lowerFlatListU32: realloc failed: %w", err_)
	}
	for i_ := uint32(0); i_ < ln_; i_++ {
		if ok_ := callee.Memory().WriteUint32Le(ptr_+i_*4, v[i_]); !ok_ {
			return fmt.Errorf("wacogo/witgen: lowerFlatListU32: list elem: bad memory write")
		}
	}
	stack[0] = uint64(ptr_)
	stack[1] = uint64(ln_)
	return nil
}

func lowerMemListU32(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, ptr uint32, v []uint32) error {
	lstT_ := ty.(wacogo.TypeList)
	_ = lstT_
	ln_ := uint32(len(v))
	lptr_, err_ := callee.Realloc(ctx, 0, 0, 4, ln_*4)
	if err_ != nil {
		return fmt.Errorf("wacogo/witgen: lowerMemListU32: realloc failed: %w", err_)
	}
	for i_ := uint32(0); i_ < ln_; i_++ {
		if ok_ := callee.Memory().WriteUint32Le(lptr_+i_*4, v[i_]); !ok_ {
			return fmt.Errorf("wacogo/witgen: lowerMemListU32: list elem: bad memory write")
		}
	}
	if ok_ := callee.Memory().WriteUint32Le(ptr, lptr_); !ok_ {
		return fmt.Errorf("wacogo/witgen: lowerMemListU32: list ptr: bad memory write")
	}
	if ok_ := callee.Memory().WriteUint32Le(ptr+4, ln_); !ok_ {
		return fmt.Errorf("wacogo/witgen: lowerMemListU32: list len: bad memory write")
	}
	return nil
}

func toGoFlatRecordWithCounter(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, stack []uint64) (RecordWithCounter, error) {
	var v_ RecordWithCounter
	recT_ := ty.(wacogo.TypeRecord)
	_ = recT_
	{
		oh_ := uint32(stack[0])
		tbl_ := recT_.Fields[0].Type.(wacogo.TypeOwn).ResourceType
		rh_, lookupErr_ := cc.LookupBorrowable(tbl_, oh_)
		if lookupErr_ != nil {
			return RecordWithCounter{}, lookupErr_
		}
		var impl_ Counter
		if obj_, ok_ := rh_.Type().Instance().LookupExtern(rh_.Rep()); ok_ {
			if typed_, ok2_ := obj_.(Counter); ok2_ {
				impl_ = typed_
			}
		}
		v_.C = NewCounterHandleFrom(rh_, impl_)
	}
	return v_, nil
}

func toGoMemRecordWithCounter(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, ptr uint32) (RecordWithCounter, error) {
	var v_ RecordWithCounter
	recT_ := ty.(wacogo.TypeRecord)
	_ = recT_
	{
		var oh_ uint32
		if tmp_, ok_ := cc.Memory().ReadUint32Le(ptr); !ok_ {
			return RecordWithCounter{}, fmt.Errorf("wacogo/witgen: toGoMemRecordWithCounter: field C: handle: bad memory read")
		} else {
			oh_ = tmp_
		}
		tbl_ := recT_.Fields[0].Type.(wacogo.TypeOwn).ResourceType
		rh_, lookupErr_ := cc.LookupBorrowable(tbl_, oh_)
		if lookupErr_ != nil {
			return RecordWithCounter{}, lookupErr_
		}
		var impl_ Counter
		if obj_, ok_ := rh_.Type().Instance().LookupExtern(rh_.Rep()); ok_ {
			if typed_, ok2_ := obj_.(Counter); ok2_ {
				impl_ = typed_
			}
		}
		v_.C = NewCounterHandleFrom(rh_, impl_)
	}
	return v_, nil
}

func fromGoFlatRecordWithCounter(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, stack []uint64, v RecordWithCounter) error {
	{
		oh_, err_ := v.C.bind(cc, h)
		if err_ != nil {
			return err_
		}
		v.C.Invalidate()
		stack[0] = uint64(oh_)
	}
	return nil
}

func fromGoMemRecordWithCounter(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, ptr uint32, v RecordWithCounter) error {
	{
		oh_, err_ := v.C.bind(cc, h)
		if err_ != nil {
			return err_
		}
		v.C.Invalidate()
		if ok_ := cc.Memory().WriteUint32Le(ptr, oh_); !ok_ {
			return fmt.Errorf("wacogo/witgen: fromGoMemRecordWithCounter: field C: handle: bad memory write")
		}
	}
	return nil
}

func liftFlatRecordWithCounter(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, stack []uint64) (RecordWithCounter, error) {
	var v_ RecordWithCounter
	recT_ := ty.(wacogo.TypeRecord)
	_ = recT_
	{
		calleeOh_ := uint32(stack[0])
		tr_ := recT_.Fields[0].Type.(wacogo.TypeOwn).ResourceType
		srcH_, srcErr_ := callee.LookupOwn(tr_, calleeOh_)
		if srcErr_ != nil {
			return RecordWithCounter{}, srcErr_
		}
		dstH_, dstErr_ := srcH_.TransferOwn(caller.TransferTarget())
		if dstErr_ != nil {
			return RecordWithCounter{}, dstErr_
		}
		var impl_ Counter
		if obj_, ok_ := dstH_.Type().Instance().LookupExtern(dstH_.Rep()); ok_ {
			if typed_, ok2_ := obj_.(Counter); ok2_ {
				impl_ = typed_
			}
		}
		v_.C = NewCounterHandleFrom(dstH_, impl_)
	}
	return v_, nil
}

func liftMemRecordWithCounter(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, ptr uint32) (RecordWithCounter, error) {
	var v_ RecordWithCounter
	recT_ := ty.(wacogo.TypeRecord)
	_ = recT_
	{
		var calleeOh_ uint32
		if tmp_, ok_ := callee.Memory().ReadUint32Le(ptr); !ok_ {
			return RecordWithCounter{}, fmt.Errorf("wacogo/witgen: liftMemRecordWithCounter: field C: handle: bad memory read")
		} else {
			calleeOh_ = tmp_
		}
		tr_ := recT_.Fields[0].Type.(wacogo.TypeOwn).ResourceType
		srcH_, srcErr_ := callee.LookupOwn(tr_, calleeOh_)
		if srcErr_ != nil {
			return RecordWithCounter{}, srcErr_
		}
		dstH_, dstErr_ := srcH_.TransferOwn(caller.TransferTarget())
		if dstErr_ != nil {
			return RecordWithCounter{}, dstErr_
		}
		var impl_ Counter
		if obj_, ok_ := dstH_.Type().Instance().LookupExtern(dstH_.Rep()); ok_ {
			if typed_, ok2_ := obj_.(Counter); ok2_ {
				impl_ = typed_
			}
		}
		v_.C = NewCounterHandleFrom(dstH_, impl_)
	}
	return v_, nil
}

func lowerFlatRecordWithCounter(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, stack []uint64, v RecordWithCounter) error {
	recT_ := ty.(wacogo.TypeRecord)
	_ = recT_
	{
		callerH_, err_ := v.C.bind(caller, h)
		if err_ != nil {
			return err_
		}
		tr_ := recT_.Fields[0].Type.(wacogo.TypeOwn).ResourceType
		srcH_, err2_ := caller.LookupOwn(tr_, callerH_)
		if err2_ != nil {
			return err2_
		}
		dstH_, err3_ := srcH_.TransferOwn(callee.TransferTarget())
		if err3_ != nil {
			return err3_
		}
		stack[0] = uint64(dstH_.HandleID())
		v.C.Invalidate()
	}
	return nil
}

func lowerMemRecordWithCounter(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, ptr uint32, v RecordWithCounter) error {
	recT_ := ty.(wacogo.TypeRecord)
	_ = recT_
	{
		callerH_, err_ := v.C.bind(caller, h)
		if err_ != nil {
			return err_
		}
		tr_ := recT_.Fields[0].Type.(wacogo.TypeOwn).ResourceType
		srcH_, err2_ := caller.LookupOwn(tr_, callerH_)
		if err2_ != nil {
			return err2_
		}
		dstH_, err3_ := srcH_.TransferOwn(callee.TransferTarget())
		if err3_ != nil {
			return err3_
		}
		v.C.Invalidate()
		if ok_ := callee.Memory().WriteUint32Le(ptr, dstH_.HandleID()); !ok_ {
			return fmt.Errorf("wacogo/witgen: lowerMemRecordWithCounter: field C: handle: bad memory write")
		}
	}
	return nil
}

func wrapBoxCounter(f *Factory) host.Func {
	return func(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, stack []uint64) error {
		state_ := h.UserState().(*instanceState)
		fnType_ := cc.Instance().ExportedFunc("box-counter").Type()
		_ = fnType_
		var c *CounterHandle
		{
			oh_ := uint32(stack[0])
			tr_ := fnType_.Params[0].Type.(wacogo.TypeOwn).ResourceType
			rh_, lookupErr_ := cc.LookupBorrowable(tr_, oh_)
			if lookupErr_ != nil {
				return lookupErr_
			}
			var impl_ Counter
			if obj_, ok_ := rh_.Type().Instance().LookupExtern(rh_.Rep()); ok_ {
				if typed_, ok2_ := obj_.(Counter); ok2_ {
					impl_ = typed_
				}
			}
			c = NewCounterHandleFrom(rh_, impl_)
		}
		result_, implErr_ := state_.impl.BoxCounter(ctx, c)
		if implErr_ != nil {
			return fmt.Errorf("wacogo/witgen: box-counter: impl returned error: %w", implErr_)
		}
		if err_ := fromGoFlatRecordWithCounter(ctx, cc, h, stack[0:1], result_); err_ != nil {
			return err_
		}
		return nil
	}
}

func wrapNewCounters(f *Factory) host.Func {
	return func(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, stack []uint64) error {
		state_ := h.UserState().(*instanceState)
		fnType_ := cc.Instance().ExportedFunc("new-counters").Type()
		_ = fnType_
		var starts []uint32
		{
			v_, err_ := toGoFlatListU32(ctx, cc, h, fnType_.Params[0].Type, stack[0:2])
			if err_ != nil {
				return err_
			}
			starts = v_
		}
		result_, implErr_ := state_.impl.NewCounters(ctx, starts)
		if implErr_ != nil {
			return fmt.Errorf("wacogo/witgen: new-counters: impl returned error: %w", implErr_)
		}
		outPtr_, rerr_ := cc.Realloc(ctx, 0, 0, 4, 8)
		if rerr_ != nil {
			return fmt.Errorf("wacogo/witgen: new-counters: realloc failed: %w", rerr_)
		}
		if err_ := fromGoMemListCounter(ctx, cc, h, outPtr_, result_); err_ != nil {
			return err_
		}
		stack[0] = uint64(outPtr_)
		return nil
	}
}

func wrapNewCounter(f *Factory) host.Func {
	return func(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, stack []uint64) error {
		state_ := h.UserState().(*instanceState)
		fnType_ := cc.Instance().ExportedFunc("[constructor]counter").Type()
		_ = fnType_
		start := uint32(stack[0])
		result_, err_ := state_.impl.NewCounter(ctx, start)
		if err_ != nil {
			return fmt.Errorf("wacogo/witgen: [constructor]counter: impl returned error: %w", err_)
		}
		oh_, err_ := result_.bind(cc, h)
		if err_ != nil {
			return fmt.Errorf("wacogo/witgen: [constructor]counter: bind failed: %w", err_)
		}
		result_.Invalidate()
		stack[0] = uint64(oh_)
		return nil
	}
}

func wrapCounterGet(f *Factory) host.Func {
	return func(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, stack []uint64) error {
		fnType_ := cc.Instance().ExportedFunc("[method]counter.get").Type()
		_ = fnType_
		selfObj_, ok_ := h.LookupResource(host.ExternHandle(uint32(stack[0])))
		if !ok_ {
			return fmt.Errorf("wacogo/witgen: [method]counter.get: missing rep")
		}
		self_ := selfObj_.(Counter)
		result_, implErr_ := self_.Get(ctx)
		if implErr_ != nil {
			return fmt.Errorf("wacogo/witgen: [method]counter.get: impl returned error: %w", implErr_)
		}
		stack[0] = uint64(result_)
		return nil
	}
}
