// Code generated by wacogo-witgen from compounds.wit. DO NOT EDIT.

// Package compounds provides Go bindings for the example:demo/compounds interface.
package compounds

import (
	"context"
	"fmt"

	"github.com/partite-ai/wacogo"
	"github.com/partite-ai/wacogo/host"
)

// compoundsWrapper is the concrete type returned by WrapInstance
// as a Compounds. Held internally; users hold it via the Compounds
// interface.
type compoundsWrapper struct {
	callerInst    *host.ComponentInstance
	fnBoxCounter  *host.ExportedFunc
	fnNewCounters *host.ExportedFunc
	fnNewCounter  *host.ExportedFunc
	fnCounterGet  *host.ExportedFunc
}

// WrapInstance returns a Compounds that forwards method calls to
// callee. caller is a Factory-built host instance whose state hosts any
// handles minted by callee during those calls.
func WrapInstance(caller *host.ComponentInstance, callee *wacogo.ComponentInstance) Compounds {
	w_ := &compoundsWrapper{callerInst: caller}
	w_.fnBoxCounter = host.WrapExportedFunc(callee.ExportedFunc("box-counter"))
	w_.fnNewCounters = host.WrapExportedFunc(callee.ExportedFunc("new-counters"))
	w_.fnNewCounter = host.WrapExportedFunc(callee.ExportedFunc("[constructor]counter"))
	w_.fnCounterGet = host.WrapExportedFunc(callee.ExportedFunc("[method]counter.get"))
	return w_
}
func (w *compoundsWrapper) BoxCounter(ctx context.Context, c *CounterHandle) (RecordWithCounter, error) {
	var resVal_ RecordWithCounter
	var resErr_ error
	arg0_ := c
	{
		callErr_ := w.fnBoxCounter.CallRaw(ctx, w.callerInst,
			func(caller, callee *host.CallContext, stack []uint64) {
				{
					tr_ := w.fnBoxCounter.ParamType(0).(wacogo.TypeOwn).ResourceType
					callerH_, err_ := arg0_.bind(caller, w.callerInst)
					if err_ != nil {
						resErr_ = err_
						return
					}
					srcH_, err_ := caller.LookupOwn(tr_, callerH_)
					if err_ != nil {
						resErr_ = err_
						return
					}
					dstH_, err_ := srcH_.TransferOwn(callee.TransferTarget())
					if err_ != nil {
						resErr_ = err_
						return
					}
					stack[0] = uint64(dstH_.HandleID())
					arg0_.Invalidate()
				}
			},
			func(caller, callee *host.CallContext, stack []uint64) {
				if v_, err_ := liftFlatRecordWithCounter(ctx, caller, callee, w.callerInst, w.fnBoxCounter.ResultType(0), stack[0:1]); err_ != nil {
					resErr_ = err_
					return
				} else {
					resVal_ = v_
				}
			},
		)
		if callErr_ != nil {
			return RecordWithCounter{}, fmt.Errorf("wacogo/witgen: CallRaw failed: %w", callErr_)
		}
		if resErr_ != nil {
			return RecordWithCounter{}, resErr_
		}
	}
	return resVal_, nil
}

func (w *compoundsWrapper) NewCounters(ctx context.Context, starts []uint32) ([]*CounterHandle, error) {
	var resVal_ []*CounterHandle
	var resErr_ error
	arg0_ := starts
	{
		callErr_ := w.fnNewCounters.CallRaw(ctx, w.callerInst,
			func(caller, callee *host.CallContext, stack []uint64) {
				if err_ := lowerFlatListU32(ctx, caller, callee, w.callerInst, w.fnNewCounters.ParamType(0), stack[0:2], arg0_); err_ != nil {
					resErr_ = err_
					return
				}
			},
			func(caller, callee *host.CallContext, stack []uint64) {
				if v_, err_ := liftMemListCounter(ctx, caller, callee, w.callerInst, w.fnNewCounters.ResultType(0), uint32(stack[0])); err_ != nil {
					resErr_ = err_
					return
				} else {
					resVal_ = v_
				}
			},
		)
		if callErr_ != nil {
			return nil, fmt.Errorf("wacogo/witgen: CallRaw failed: %w", callErr_)
		}
		if resErr_ != nil {
			return nil, resErr_
		}
	}
	return resVal_, nil
}

func (w *compoundsWrapper) NewCounter(ctx context.Context, start uint32) (*CounterHandle, error) {
	var resVal_ *CounterHandle
	var resErr_ error
	arg0_ := start
	{
		callErr_ := w.fnNewCounter.CallRaw(ctx, w.callerInst,
			func(caller, callee *host.CallContext, stack []uint64) {
				stack[0] = uint64(arg0_)
			},
			func(caller, callee *host.CallContext, stack []uint64) {
				{
					tr_ := w.fnNewCounter.ResultType(0).(wacogo.TypeOwn).ResourceType
					calleeH_ := uint32(stack[0])
					srcH_, srcErr_ := callee.LookupOwn(tr_, calleeH_)
					if srcErr_ != nil {
						resErr_ = srcErr_
						return
					}
					dstH_, dstErr_ := srcH_.TransferOwn(caller.TransferTarget())
					if dstErr_ != nil {
						resErr_ = dstErr_
						return
					}
					var impl_ Counter
					if obj_, ok_ := dstH_.Type().Instance().LookupExtern(dstH_.Rep()); ok_ {
						if typed_, ok2_ := obj_.(Counter); ok2_ {
							impl_ = typed_
						}
					}
					resVal_ = NewCounterHandleFrom(dstH_, impl_)
				}
			},
		)
		if callErr_ != nil {
			return nil, fmt.Errorf("wacogo/witgen: CallRaw failed: %w", callErr_)
		}
		if resErr_ != nil {
			return nil, resErr_
		}
	}
	return resVal_, nil
}
