// Code generated by wacogo-witgen from counter.wit. DO NOT EDIT.

// Package counterhost provides Go bindings for the example:demo/counterhost interface.
package counterhost

import (
	"context"
	"fmt"

	"github.com/partite-ai/wacogo"
	"github.com/partite-ai/wacogo/host"
)

// counterhostWrapper is the concrete type returned by WrapInstance
// as a Counterhost. Held internally; users hold it via the Counterhost
// interface.
type counterhostWrapper struct {
	callerInst         *host.ComponentInstance
	fnNewCounter       *host.ExportedFunc
	fnCounterCurrent   *host.ExportedFunc
	fnCounterIncrement *host.ExportedFunc
}

// WrapInstance returns a Counterhost that forwards method calls to
// callee. caller is a Factory-built host instance whose state hosts any
// handles minted by callee during those calls.
func WrapInstance(caller *host.ComponentInstance, callee *wacogo.ComponentInstance) Counterhost {
	w_ := &counterhostWrapper{callerInst: caller}
	w_.fnNewCounter = host.WrapExportedFunc(callee.ExportedFunc("[constructor]counter"))
	w_.fnCounterCurrent = host.WrapExportedFunc(callee.ExportedFunc("[method]counter.current"))
	w_.fnCounterIncrement = host.WrapExportedFunc(callee.ExportedFunc("[method]counter.increment"))
	return w_
}
func (w *counterhostWrapper) NewCounter(ctx context.Context, initial uint32) (*CounterHandle, error) {
	var resVal_ *CounterHandle
	var resErr_ error
	arg0_ := initial
	{
		callErr_ := w.fnNewCounter.CallRaw(ctx, w.callerInst,
			func(caller, callee *host.CallContext, stack []uint64) {
				stack[0] = uint64(arg0_)
			},
			func(caller, callee *host.CallContext, stack []uint64) {
				{
					tr_ := w.fnNewCounter.ResultType(0).(wacogo.TypeOwn).ResourceType
					calleeH_ := uint32(stack[0])
					srcH_, srcErr_ := callee.LookupOwn(tr_, calleeH_)
					if srcErr_ != nil {
						resErr_ = srcErr_
						return
					}
					dstH_, dstErr_ := srcH_.TransferOwn(caller.TransferTarget())
					if dstErr_ != nil {
						resErr_ = dstErr_
						return
					}
					var impl_ Counter
					if obj_, ok_ := dstH_.Type().Instance().LookupExtern(dstH_.Rep()); ok_ {
						if typed_, ok2_ := obj_.(Counter); ok2_ {
							impl_ = typed_
						}
					}
					resVal_ = NewCounterHandleFrom(dstH_, impl_)
				}
			},
		)
		if callErr_ != nil {
			return nil, fmt.Errorf("wacogo/witgen: CallRaw failed: %w", callErr_)
		}
		if resErr_ != nil {
			return nil, resErr_
		}
	}
	return resVal_, nil
}
