// Code generated by wacogo-witgen from counter.wit. DO NOT EDIT.

// Package counterhost provides Go bindings for the example:demo/counterhost interface.
package counterhost

import (
	"context"
	"fmt"

	"github.com/partite-ai/wacogo"
	"github.com/partite-ai/wacogo/host"
)

// Factory builds host-side instances of the Counterhost interface
// from a Go implementation.
type Factory struct {
	engine    *wacogo.Engine
	comp      *host.Component
	counterRT *host.ResourceType
}

type instanceState struct {
	impl      Counterhost
	counterTR *wacogo.TypeResource
}

// Deps groups the cross-component dependencies required to instantiate
// Counterhost. Pass a populated value via NewInstance.
type Deps struct {
}

// NewFactory creates a Factory bound to e. A single Factory may be
// reused to build multiple instances backed by different implementations.
func NewFactory(ctx context.Context, e *wacogo.Engine) (*Factory, error) {
	f_ := &Factory{engine: e}
	b_ := e.NewHostBuilder("example_demo_counterhost")

	f_.counterRT = b_.AddResource("counter", resourceDtor)

	b_.AddFunction("[constructor]counter", &host.FuncType{
		Params:  []host.Param{{Name: "initial", Type: host.U32}},
		Results: []host.ResultDecl{{Name: "", Type: f_.counterRT.Own()}},
	}, wrapNewCounter(f_))

	b_.AddFunction("[method]counter.current", &host.FuncType{
		Params:  []host.Param{{Name: "self", Type: f_.counterRT.Borrow()}},
		Results: []host.ResultDecl{{Name: "", Type: host.U32}},
	}, wrapCounterCurrent(f_))

	b_.AddFunction("[method]counter.increment", &host.FuncType{
		Params:  []host.Param{{Name: "self", Type: f_.counterRT.Borrow()}},
		Results: []host.ResultDecl{},
	}, wrapCounterIncrement(f_))

	comp_, err_ := b_.Build(ctx)
	if err_ != nil {
		return nil, err_
	}
	f_.comp = comp_
	return f_, nil
}

// NewInstance creates a fresh component instance backed by impl. Pass
// inst.Core() to wacogo.WithInstanceImport to wire the instance into a
// composite world. deps may be nil only when Counterhost has no
// imports.
func (f *Factory) NewInstance(ctx context.Context, impl Counterhost, deps *Deps, opts ...host.InstantiateOption) (*host.ComponentInstance, error) {
	_ = deps
	state_ := &instanceState{impl: impl}
	opts = append(opts, host.WithUserState(state_))
	inst_, err_ := f.comp.Instantiate(ctx, opts...)
	if err_ != nil {
		return nil, err_
	}
	state_.counterTR = inst_.Core().ExportedType("counter").(*wacogo.TypeResource)
	return inst_, nil
}

// Close releases resources shared by the Factory. Existing instances
// remain callable until each is closed individually.
func (f *Factory) Close(ctx context.Context) error { return f.comp.Close(ctx) }

// resourceDtor is the generic destructor invoked when canon orchestrates
// terminal-drop on a host-defined resource handle. Type-asserts the
// underlying Go object for an optional Drop() method and calls it.
func resourceDtor(_ context.Context, _ *host.ComponentInstance, obj any) error {
	if d_, ok_ := obj.(interface{ Drop() }); ok_ {
		d_.Drop()
	}
	return nil
}

func wrapNewCounter(f *Factory) host.Func {
	return func(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, stack []uint64) error {
		state_ := h.UserState().(*instanceState)
		fnType_ := cc.Instance().ExportedFunc("[constructor]counter").Type()
		_ = fnType_
		initial := uint32(stack[0])
		result_, err_ := state_.impl.NewCounter(ctx, initial)
		if err_ != nil {
			return fmt.Errorf("wacogo/witgen: [constructor]counter: impl returned error: %w", err_)
		}
		oh_, err_ := result_.bind(cc, h)
		if err_ != nil {
			return fmt.Errorf("wacogo/witgen: [constructor]counter: bind failed: %w", err_)
		}
		result_.Invalidate()
		stack[0] = uint64(oh_)
		return nil
	}
}

func wrapCounterCurrent(f *Factory) host.Func {
	return func(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, stack []uint64) error {
		fnType_ := cc.Instance().ExportedFunc("[method]counter.current").Type()
		_ = fnType_
		selfObj_, ok_ := h.LookupResource(host.ExternHandle(uint32(stack[0])))
		if !ok_ {
			return fmt.Errorf("wacogo/witgen: [method]counter.current: missing rep")
		}
		self_ := selfObj_.(Counter)
		result_, implErr_ := self_.Current(ctx)
		if implErr_ != nil {
			return fmt.Errorf("wacogo/witgen: [method]counter.current: impl returned error: %w", implErr_)
		}
		stack[0] = uint64(result_)
		return nil
	}
}

func wrapCounterIncrement(f *Factory) host.Func {
	return func(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, stack []uint64) error {
		fnType_ := cc.Instance().ExportedFunc("[method]counter.increment").Type()
		_ = fnType_
		selfObj_, ok_ := h.LookupResource(host.ExternHandle(uint32(stack[0])))
		if !ok_ {
			return fmt.Errorf("wacogo/witgen: [method]counter.increment: missing rep")
		}
		self_ := selfObj_.(Counter)
		if err_ := self_.Increment(ctx); err_ != nil {
			return fmt.Errorf("wacogo/witgen: [method]counter.increment: impl returned error: %w", err_)
		}
		return nil
	}
}
