// Code generated by wacogo-witgen from docs.wit. DO NOT EDIT.

// Package-level documentation for the docs interface.
//
// Multi-paragraph prose that exercises blank-line handling
// in goDocComment.
package docs

import (
	"context"
	"fmt"

	"github.com/partite-ai/wacogo"
	"github.com/partite-ai/wacogo/host"
)

// Factory builds host-side instances of the Docs interface
// from a Go implementation.
type Factory struct {
	engine    *wacogo.Engine
	comp      *host.Component
	counterRT *host.ResourceType
}

type instanceState struct {
	impl      Docs
	counterTR *wacogo.TypeResource
}

// Deps groups the cross-component dependencies required to instantiate
// Docs. Pass a populated value via NewInstance.
type Deps struct {
}

// NewFactory creates a Factory bound to e. A single Factory may be
// reused to build multiple instances backed by different implementations.
func NewFactory(ctx context.Context, e *wacogo.Engine) (*Factory, error) {
	f_ := &Factory{engine: e}
	b_ := e.NewHostBuilder("example_demo_docs")

	f_.counterRT = b_.AddResource("counter", resourceDtor)

	typDirection_ := b_.AddType("direction", host.Enum{Cases: []string{"north", "east", "south", "west"}})
	_ = typDirection_

	typPerms_ := b_.AddType("perms", host.Flags{Names: []string{"read", "write"}})
	_ = typPerms_

	typPoint_ := b_.AddType("point", host.Record{Fields: []host.Field{{Name: "x", Type: host.U32}, {Name: "y", Type: host.U32}}})
	_ = typPoint_

	typShape_ := b_.AddType("shape", host.Variant{Cases: []host.Case{{Name: "circle", Payload: host.U32}, {Name: "square", Payload: nil}}})
	_ = typShape_

	b_.AddFunction("greet", &host.FuncType{
		Params:  []host.Param{{Name: "name", Type: host.String}},
		Results: []host.ResultDecl{{Name: "", Type: host.String}},
	}, wrapGreet(f_))

	b_.AddFunction("[constructor]counter", &host.FuncType{
		Params:  []host.Param{},
		Results: []host.ResultDecl{{Name: "", Type: f_.counterRT.Own()}},
	}, wrapNewCounter(f_))

	b_.AddFunction("[method]counter.current", &host.FuncType{
		Params:  []host.Param{{Name: "self", Type: f_.counterRT.Borrow()}},
		Results: []host.ResultDecl{{Name: "", Type: host.U32}},
	}, wrapCounterCurrent(f_))

	b_.AddFunction("[method]counter.increment", &host.FuncType{
		Params:  []host.Param{{Name: "self", Type: f_.counterRT.Borrow()}},
		Results: []host.ResultDecl{},
	}, wrapCounterIncrement(f_))

	b_.AddFunction("[static]counter.from-one", &host.FuncType{
		Params:  []host.Param{},
		Results: []host.ResultDecl{{Name: "", Type: f_.counterRT.Own()}},
	}, wrapCounterFromOne(f_))

	comp_, err_ := b_.Build(ctx)
	if err_ != nil {
		return nil, err_
	}
	f_.comp = comp_
	return f_, nil
}

// NewInstance creates a fresh component instance backed by impl. Pass
// inst.Core() to wacogo.WithInstanceImport to wire the instance into a
// composite world. deps may be nil only when Docs has no
// imports.
func (f *Factory) NewInstance(ctx context.Context, impl Docs, deps *Deps, opts ...host.InstantiateOption) (*host.ComponentInstance, error) {
	_ = deps
	state_ := &instanceState{impl: impl}
	opts = append(opts, host.WithUserState(state_))
	inst_, err_ := f.comp.Instantiate(ctx, opts...)
	if err_ != nil {
		return nil, err_
	}
	state_.counterTR = inst_.Core().ExportedType("counter").(*wacogo.TypeResource)
	return inst_, nil
}

// Close releases resources shared by the Factory. Existing instances
// remain callable until each is closed individually.
func (f *Factory) Close(ctx context.Context) error { return f.comp.Close(ctx) }

// resourceDtor is the generic destructor invoked when canon orchestrates
// terminal-drop on a host-defined resource handle. Type-asserts the
// underlying Go object for an optional Drop() method and calls it.
func resourceDtor(_ context.Context, _ *host.ComponentInstance, obj any) error {
	if d_, ok_ := obj.(interface{ Drop() }); ok_ {
		d_.Drop()
	}
	return nil
}

func toGoFlatString(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, stack []uint64) (string, error) {
	_ = ty
	ptr_ := uint32(stack[0])
	ln_ := uint32(stack[1])
	bs_, ok_ := cc.Memory().Read(ptr_, ln_)
	if !ok_ {
		return "", fmt.Errorf("wacogo/witgen: toGoFlatString: bad memory read")
	}
	return string(bs_), nil
}

func toGoMemString(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, ptr uint32) (string, error) {
	_ = ty
	var sptr_ uint32
	if tmp_, ok_ := cc.Memory().ReadUint32Le(ptr); !ok_ {
		return "", fmt.Errorf("wacogo/witgen: toGoMemString: string ptr: bad memory read")
	} else {
		sptr_ = tmp_
	}
	var ln_ uint32
	if tmp_, ok_ := cc.Memory().ReadUint32Le(ptr + 4); !ok_ {
		return "", fmt.Errorf("wacogo/witgen: toGoMemString: string len: bad memory read")
	} else {
		ln_ = tmp_
	}
	bs_, ok_ := cc.Memory().Read(sptr_, ln_)
	if !ok_ {
		return "", fmt.Errorf("wacogo/witgen: toGoMemString: bad memory read")
	}
	return string(bs_), nil
}

func fromGoFlatString(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, stack []uint64, v string) error {
	bs_ := []byte(v)
	ptr_, err_ := cc.Realloc(ctx, 0, 0, 1, uint32(len(bs_)))
	if err_ != nil {
		return fmt.Errorf("wacogo/witgen: fromGoFlatString: realloc failed: %w", err_)
	}
	if ok_ := cc.Memory().Write(ptr_, bs_); !ok_ {
		return fmt.Errorf("wacogo/witgen: fromGoFlatString: bad memory write")
	}
	stack[0] = uint64(ptr_)
	stack[1] = uint64(len(bs_))
	return nil
}

func fromGoMemString(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, ptr uint32, v string) error {
	bs_ := []byte(v)
	sptr_, err_ := cc.Realloc(ctx, 0, 0, 1, uint32(len(bs_)))
	if err_ != nil {
		return fmt.Errorf("wacogo/witgen: fromGoMemString: realloc failed: %w", err_)
	}
	if ok_ := cc.Memory().Write(sptr_, bs_); !ok_ {
		return fmt.Errorf("wacogo/witgen: fromGoMemString: bad memory write")
	}
	if ok_ := cc.Memory().WriteUint32Le(ptr, sptr_); !ok_ {
		return fmt.Errorf("wacogo/witgen: fromGoMemString: string ptr: bad memory write")
	}
	if ok_ := cc.Memory().WriteUint32Le(ptr+4, uint32(len(bs_))); !ok_ {
		return fmt.Errorf("wacogo/witgen: fromGoMemString: string len: bad memory write")
	}
	return nil
}

func liftFlatString(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, stack []uint64) (string, error) {
	ptr_ := uint32(stack[0])
	ln_ := uint32(stack[1])
	bs_, ok_ := callee.Memory().Read(ptr_, ln_)
	if !ok_ {
		return "", fmt.Errorf("wacogo/witgen: liftFlatString: bad memory read")
	}
	return string(bs_), nil
}

func liftMemString(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, ptr uint32) (string, error) {
	var sptr_ uint32
	if tmp_, ok_ := callee.Memory().ReadUint32Le(ptr); !ok_ {
		return "", fmt.Errorf("wacogo/witgen: liftMemString: string ptr: bad memory read")
	} else {
		sptr_ = tmp_
	}
	var ln_ uint32
	if tmp_, ok_ := callee.Memory().ReadUint32Le(ptr + 4); !ok_ {
		return "", fmt.Errorf("wacogo/witgen: liftMemString: string len: bad memory read")
	} else {
		ln_ = tmp_
	}
	bs_, ok_ := callee.Memory().Read(sptr_, ln_)
	if !ok_ {
		return "", fmt.Errorf("wacogo/witgen: liftMemString: bad memory read")
	}
	return string(bs_), nil
}

func lowerFlatString(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, stack []uint64, v string) error {
	bs_ := []byte(v)
	ptr_, err_ := callee.Realloc(ctx, 0, 0, 1, uint32(len(bs_)))
	if err_ != nil {
		return fmt.Errorf("wacogo/witgen: lowerFlatString: realloc failed: %w", err_)
	}
	if ok_ := callee.Memory().Write(ptr_, bs_); !ok_ {
		return fmt.Errorf("wacogo/witgen: lowerFlatString: bad memory write")
	}
	stack[0] = uint64(ptr_)
	stack[1] = uint64(len(bs_))
	return nil
}

func lowerMemString(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, ptr uint32, v string) error {
	bs_ := []byte(v)
	sptr_, err_ := callee.Realloc(ctx, 0, 0, 1, uint32(len(bs_)))
	if err_ != nil {
		return fmt.Errorf("wacogo/witgen: lowerMemString: realloc failed: %w", err_)
	}
	if ok_ := callee.Memory().Write(sptr_, bs_); !ok_ {
		return fmt.Errorf("wacogo/witgen: lowerMemString: bad memory write")
	}
	if ok_ := callee.Memory().WriteUint32Le(ptr, sptr_); !ok_ {
		return fmt.Errorf("wacogo/witgen: lowerMemString: string ptr: bad memory write")
	}
	if ok_ := callee.Memory().WriteUint32Le(ptr+4, uint32(len(bs_))); !ok_ {
		return fmt.Errorf("wacogo/witgen: lowerMemString: string len: bad memory write")
	}
	return nil
}

func wrapGreet(f *Factory) host.Func {
	return func(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, stack []uint64) error {
		state_ := h.UserState().(*instanceState)
		fnType_ := cc.Instance().ExportedFunc("greet").Type()
		_ = fnType_
		var name string
		{
			v_, err_ := toGoFlatString(ctx, cc, h, fnType_.Params[0].Type, stack[0:2])
			if err_ != nil {
				return err_
			}
			name = v_
		}
		result_, implErr_ := state_.impl.Greet(ctx, name)
		if implErr_ != nil {
			return fmt.Errorf("wacogo/witgen: greet: impl returned error: %w", implErr_)
		}
		outPtr_, rerr_ := cc.Realloc(ctx, 0, 0, 4, 8)
		if rerr_ != nil {
			return fmt.Errorf("wacogo/witgen: greet: realloc failed: %w", rerr_)
		}
		if err_ := fromGoMemString(ctx, cc, h, outPtr_, result_); err_ != nil {
			return err_
		}
		stack[0] = uint64(outPtr_)
		return nil
	}
}

func wrapNewCounter(f *Factory) host.Func {
	return func(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, stack []uint64) error {
		state_ := h.UserState().(*instanceState)
		fnType_ := cc.Instance().ExportedFunc("[constructor]counter").Type()
		_ = fnType_
		result_, err_ := state_.impl.NewCounter(ctx)
		if err_ != nil {
			return fmt.Errorf("wacogo/witgen: [constructor]counter: impl returned error: %w", err_)
		}
		oh_, err_ := result_.bind(cc, h)
		if err_ != nil {
			return fmt.Errorf("wacogo/witgen: [constructor]counter: bind failed: %w", err_)
		}
		result_.Invalidate()
		stack[0] = uint64(oh_)
		return nil
	}
}

func wrapCounterCurrent(f *Factory) host.Func {
	return func(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, stack []uint64) error {
		fnType_ := cc.Instance().ExportedFunc("[method]counter.current").Type()
		_ = fnType_
		selfObj_, ok_ := h.LookupResource(host.ExternHandle(uint32(stack[0])))
		if !ok_ {
			return fmt.Errorf("wacogo/witgen: [method]counter.current: missing rep")
		}
		self_ := selfObj_.(Counter)
		result_, implErr_ := self_.Current(ctx)
		if implErr_ != nil {
			return fmt.Errorf("wacogo/witgen: [method]counter.current: impl returned error: %w", implErr_)
		}
		stack[0] = uint64(result_)
		return nil
	}
}

func wrapCounterIncrement(f *Factory) host.Func {
	return func(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, stack []uint64) error {
		fnType_ := cc.Instance().ExportedFunc("[method]counter.increment").Type()
		_ = fnType_
		selfObj_, ok_ := h.LookupResource(host.ExternHandle(uint32(stack[0])))
		if !ok_ {
			return fmt.Errorf("wacogo/witgen: [method]counter.increment: missing rep")
		}
		self_ := selfObj_.(Counter)
		if err_ := self_.Increment(ctx); err_ != nil {
			return fmt.Errorf("wacogo/witgen: [method]counter.increment: impl returned error: %w", err_)
		}
		return nil
	}
}

func wrapCounterFromOne(f *Factory) host.Func {
	return func(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, stack []uint64) error {
		state_ := h.UserState().(*instanceState)
		fnType_ := cc.Instance().ExportedFunc("[static]counter.from-one").Type()
		_ = fnType_
		result_, implErr_ := state_.impl.CounterFromOne(ctx)
		if implErr_ != nil {
			return fmt.Errorf("wacogo/witgen: [static]counter.from-one: impl returned error: %w", implErr_)
		}
		{
			oh_, err_ := result_.bind(cc, h)
			if err_ != nil {
				return fmt.Errorf("wacogo/witgen: own-result bind failed: %w", err_)
			}
			result_.Invalidate()
			stack[0] = uint64(oh_)
		}
		return nil
	}
}
