// Code generated by wacogo-witgen from docs.wit. DO NOT EDIT.

// Package-level documentation for the docs interface.
//
// Multi-paragraph prose that exercises blank-line handling
// in goDocComment.
package docs

import (
	"context"
	"fmt"

	"github.com/partite-ai/wacogo"
	"github.com/partite-ai/wacogo/host"
)

// docsWrapper is the concrete type returned by WrapInstance
// as a Docs. Held internally; users hold it via the Docs
// interface.
type docsWrapper struct {
	callerInst         *host.ComponentInstance
	fnGreet            *host.ExportedFunc
	fnNewCounter       *host.ExportedFunc
	fnCounterCurrent   *host.ExportedFunc
	fnCounterIncrement *host.ExportedFunc
	fnCounterFromOne   *host.ExportedFunc
}

// WrapInstance returns a Docs that forwards method calls to
// callee. caller is a Factory-built host instance whose state hosts any
// handles minted by callee during those calls.
func WrapInstance(caller *host.ComponentInstance, callee *wacogo.ComponentInstance) Docs {
	w_ := &docsWrapper{callerInst: caller}
	w_.fnGreet = host.WrapExportedFunc(callee.ExportedFunc("greet"))
	w_.fnNewCounter = host.WrapExportedFunc(callee.ExportedFunc("[constructor]counter"))
	w_.fnCounterCurrent = host.WrapExportedFunc(callee.ExportedFunc("[method]counter.current"))
	w_.fnCounterIncrement = host.WrapExportedFunc(callee.ExportedFunc("[method]counter.increment"))
	w_.fnCounterFromOne = host.WrapExportedFunc(callee.ExportedFunc("[static]counter.from-one"))
	return w_
}
func (w *docsWrapper) Greet(ctx context.Context, name string) (string, error) {
	var resVal_ string
	var resErr_ error
	arg0_ := name
	{
		callErr_ := w.fnGreet.CallRaw(ctx, w.callerInst,
			func(caller, callee *host.CallContext, stack []uint64) {
				if err_ := lowerFlatString(ctx, caller, callee, w.callerInst, w.fnGreet.ParamType(0), stack[0:2], arg0_); err_ != nil {
					resErr_ = err_
					return
				}
			},
			func(caller, callee *host.CallContext, stack []uint64) {
				if v_, err_ := liftMemString(ctx, caller, callee, w.callerInst, w.fnGreet.ResultType(0), uint32(stack[0])); err_ != nil {
					resErr_ = err_
					return
				} else {
					resVal_ = v_
				}
			},
		)
		if callErr_ != nil {
			return "", fmt.Errorf("wacogo/witgen: CallRaw failed: %w", callErr_)
		}
		if resErr_ != nil {
			return "", resErr_
		}
	}
	return resVal_, nil
}

func (w *docsWrapper) NewCounter(ctx context.Context) (*CounterHandle, error) {
	var resVal_ *CounterHandle
	var resErr_ error
	{
		callErr_ := w.fnNewCounter.CallRaw(ctx, w.callerInst,
			func(caller, callee *host.CallContext, stack []uint64) {
			},
			func(caller, callee *host.CallContext, stack []uint64) {
				{
					tr_ := w.fnNewCounter.ResultType(0).(wacogo.TypeOwn).ResourceType
					calleeH_ := uint32(stack[0])
					srcH_, srcErr_ := callee.LookupOwn(tr_, calleeH_)
					if srcErr_ != nil {
						resErr_ = srcErr_
						return
					}
					dstH_, dstErr_ := srcH_.TransferOwn(caller.TransferTarget())
					if dstErr_ != nil {
						resErr_ = dstErr_
						return
					}
					var impl_ Counter
					if obj_, ok_ := dstH_.Type().Instance().LookupExtern(dstH_.Rep()); ok_ {
						if typed_, ok2_ := obj_.(Counter); ok2_ {
							impl_ = typed_
						}
					}
					resVal_ = NewCounterHandleFrom(dstH_, impl_)
				}
			},
		)
		if callErr_ != nil {
			return nil, fmt.Errorf("wacogo/witgen: CallRaw failed: %w", callErr_)
		}
		if resErr_ != nil {
			return nil, resErr_
		}
	}
	return resVal_, nil
}

func (w *docsWrapper) CounterFromOne(ctx context.Context) (*CounterHandle, error) {
	var resVal_ *CounterHandle
	var resErr_ error
	{
		callErr_ := w.fnCounterFromOne.CallRaw(ctx, w.callerInst,
			func(caller, callee *host.CallContext, stack []uint64) {
			},
			func(caller, callee *host.CallContext, stack []uint64) {
				{
					tr_ := w.fnCounterFromOne.ResultType(0).(wacogo.TypeOwn).ResourceType
					calleeH_ := uint32(stack[0])
					srcH_, srcErr_ := callee.LookupOwn(tr_, calleeH_)
					if srcErr_ != nil {
						resErr_ = srcErr_
						return
					}
					dstH_, dstErr_ := srcH_.TransferOwn(caller.TransferTarget())
					if dstErr_ != nil {
						resErr_ = dstErr_
						return
					}
					var impl_ Counter
					if obj_, ok_ := dstH_.Type().Instance().LookupExtern(dstH_.Rep()); ok_ {
						if typed_, ok2_ := obj_.(Counter); ok2_ {
							impl_ = typed_
						}
					}
					resVal_ = NewCounterHandleFrom(dstH_, impl_)
				}
			},
		)
		if callErr_ != nil {
			return nil, fmt.Errorf("wacogo/witgen: CallRaw failed: %w", callErr_)
		}
		if resErr_ != nil {
			return nil, resErr_
		}
	}
	return resVal_, nil
}
