// Code generated by wacogo-witgen from sumlist.wit. DO NOT EDIT.

// Package sumlist provides Go bindings for the example:demo/sumlist interface.
package sumlist

import (
	"context"
	"fmt"

	"github.com/partite-ai/wacogo"
	"github.com/partite-ai/wacogo/host"
)

// Factory builds host-side instances of the Sumlist interface
// from a Go implementation.
type Factory struct {
	engine *wacogo.Engine
	comp   *host.Component
}

type instanceState struct {
	impl Sumlist
}

// Deps groups the cross-component dependencies required to instantiate
// Sumlist. Pass a populated value via NewInstance.
type Deps struct {
}

// NewFactory creates a Factory bound to e. A single Factory may be
// reused to build multiple instances backed by different implementations.
func NewFactory(ctx context.Context, e *wacogo.Engine) (*Factory, error) {
	f_ := &Factory{engine: e}
	b_ := e.NewHostBuilder("example_demo_sumlist")

	b_.AddFunction("sum", &host.FuncType{
		Params:  []host.Param{{Name: "xs", Type: host.List{Elem: host.U32}}},
		Results: []host.ResultDecl{{Name: "", Type: host.U32}},
	}, wrapSum(f_))

	comp_, err_ := b_.Build(ctx)
	if err_ != nil {
		return nil, err_
	}
	f_.comp = comp_
	return f_, nil
}

// NewInstance creates a fresh component instance backed by impl. Pass
// inst.Core() to wacogo.WithInstanceImport to wire the instance into a
// composite world. deps may be nil only when Sumlist has no
// imports.
func (f *Factory) NewInstance(ctx context.Context, impl Sumlist, deps *Deps, opts ...host.InstantiateOption) (*host.ComponentInstance, error) {
	_ = deps
	state_ := &instanceState{impl: impl}
	opts = append(opts, host.WithUserState(state_))
	inst_, err_ := f.comp.Instantiate(ctx, opts...)
	if err_ != nil {
		return nil, err_
	}
	return inst_, nil
}

// Close releases resources shared by the Factory. Existing instances
// remain callable until each is closed individually.
func (f *Factory) Close(ctx context.Context) error { return f.comp.Close(ctx) }

func toGoFlatListU32(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, stack []uint64) ([]uint32, error) {
	lstT_ := ty.(wacogo.TypeList)
	_ = lstT_
	ptr_ := uint32(stack[0])
	ln_ := uint32(stack[1])
	out_ := make([]uint32, ln_)
	for i_ := uint32(0); i_ < ln_; i_++ {
		if tmp_, ok_ := cc.Memory().ReadUint32Le(ptr_ + i_*4); !ok_ {
			return nil, fmt.Errorf("wacogo/witgen: toGoFlatListU32: elem: bad memory read")
		} else {
			out_[i_] = tmp_
		}
	}
	return out_, nil
}

func toGoMemListU32(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, ptr uint32) ([]uint32, error) {
	lstT_ := ty.(wacogo.TypeList)
	_ = lstT_
	var lptr_ uint32
	if tmp_, ok_ := cc.Memory().ReadUint32Le(ptr); !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: toGoMemListU32: list ptr: bad memory read")
	} else {
		lptr_ = tmp_
	}
	var ln_ uint32
	if tmp_, ok_ := cc.Memory().ReadUint32Le(ptr + 4); !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: toGoMemListU32: list len: bad memory read")
	} else {
		ln_ = tmp_
	}
	out_ := make([]uint32, ln_)
	for i_ := uint32(0); i_ < ln_; i_++ {
		if tmp_, ok_ := cc.Memory().ReadUint32Le(lptr_ + i_*4); !ok_ {
			return nil, fmt.Errorf("wacogo/witgen: toGoMemListU32: list elem: bad memory read")
		} else {
			out_[i_] = tmp_
		}
	}
	return out_, nil
}

func fromGoFlatListU32(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, stack []uint64, v []uint32) error {
	ln_ := uint32(len(v))
	ptr_, err_ := cc.Realloc(ctx, 0, 0, 4, ln_*4)
	if err_ != nil {
		return fmt.Errorf("wacogo/witgen: fromGoFlatListU32: realloc failed: %w", err_)
	}
	for i_ := uint32(0); i_ < ln_; i_++ {
		if ok_ := cc.Memory().WriteUint32Le(ptr_+i_*4, v[i_]); !ok_ {
			return fmt.Errorf("wacogo/witgen: fromGoFlatListU32: list elem: bad memory write")
		}
	}
	stack[0] = uint64(ptr_)
	stack[1] = uint64(ln_)
	return nil
}

func fromGoMemListU32(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, ptr uint32, v []uint32) error {
	ln_ := uint32(len(v))
	lptr_, err_ := cc.Realloc(ctx, 0, 0, 4, ln_*4)
	if err_ != nil {
		return fmt.Errorf("wacogo/witgen: fromGoMemListU32: realloc failed: %w", err_)
	}
	for i_ := uint32(0); i_ < ln_; i_++ {
		if ok_ := cc.Memory().WriteUint32Le(lptr_+i_*4, v[i_]); !ok_ {
			return fmt.Errorf("wacogo/witgen: fromGoMemListU32: list elem: bad memory write")
		}
	}
	if ok_ := cc.Memory().WriteUint32Le(ptr, lptr_); !ok_ {
		return fmt.Errorf("wacogo/witgen: fromGoMemListU32: list ptr: bad memory write")
	}
	if ok_ := cc.Memory().WriteUint32Le(ptr+4, ln_); !ok_ {
		return fmt.Errorf("wacogo/witgen: fromGoMemListU32: list len: bad memory write")
	}
	return nil
}

func liftFlatListU32(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, stack []uint64) ([]uint32, error) {
	lstT_ := ty.(wacogo.TypeList)
	_ = lstT_
	ptr_ := uint32(stack[0])
	ln_ := uint32(stack[1])
	out_ := make([]uint32, ln_)
	for i_ := uint32(0); i_ < ln_; i_++ {
		if tmp_, ok_ := callee.Memory().ReadUint32Le(ptr_ + i_*4); !ok_ {
			return nil, fmt.Errorf("wacogo/witgen: liftFlatListU32: elem: bad memory read")
		} else {
			out_[i_] = tmp_
		}
	}
	return out_, nil
}

func liftMemListU32(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, ptr uint32) ([]uint32, error) {
	lstT_ := ty.(wacogo.TypeList)
	_ = lstT_
	var lptr_ uint32
	if tmp_, ok_ := callee.Memory().ReadUint32Le(ptr); !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: liftMemListU32: list ptr: bad memory read")
	} else {
		lptr_ = tmp_
	}
	var ln_ uint32
	if tmp_, ok_ := callee.Memory().ReadUint32Le(ptr + 4); !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: liftMemListU32: list len: bad memory read")
	} else {
		ln_ = tmp_
	}
	out_ := make([]uint32, ln_)
	for i_ := uint32(0); i_ < ln_; i_++ {
		if tmp_, ok_ := callee.Memory().ReadUint32Le(lptr_ + i_*4); !ok_ {
			return nil, fmt.Errorf("wacogo/witgen: liftMemListU32: list elem: bad memory read")
		} else {
			out_[i_] = tmp_
		}
	}
	return out_, nil
}

func lowerFlatListU32(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, stack []uint64, v []uint32) error {
	lstT_ := ty.(wacogo.TypeList)
	_ = lstT_
	ln_ := uint32(len(v))
	ptr_, err_ := callee.Realloc(ctx, 0, 0, 4, ln_*4)
	if err_ != nil {
		return fmt.Errorf("wacogo/witgen: lowerFlatListU32: realloc failed: %w", err_)
	}
	for i_ := uint32(0); i_ < ln_; i_++ {
		if ok_ := callee.Memory().WriteUint32Le(ptr_+i_*4, v[i_]); !ok_ {
			return fmt.Errorf("wacogo/witgen: lowerFlatListU32: list elem: bad memory write")
		}
	}
	stack[0] = uint64(ptr_)
	stack[1] = uint64(ln_)
	return nil
}

func lowerMemListU32(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, ptr uint32, v []uint32) error {
	lstT_ := ty.(wacogo.TypeList)
	_ = lstT_
	ln_ := uint32(len(v))
	lptr_, err_ := callee.Realloc(ctx, 0, 0, 4, ln_*4)
	if err_ != nil {
		return fmt.Errorf("wacogo/witgen: lowerMemListU32: realloc failed: %w", err_)
	}
	for i_ := uint32(0); i_ < ln_; i_++ {
		if ok_ := callee.Memory().WriteUint32Le(lptr_+i_*4, v[i_]); !ok_ {
			return fmt.Errorf("wacogo/witgen: lowerMemListU32: list elem: bad memory write")
		}
	}
	if ok_ := callee.Memory().WriteUint32Le(ptr, lptr_); !ok_ {
		return fmt.Errorf("wacogo/witgen: lowerMemListU32: list ptr: bad memory write")
	}
	if ok_ := callee.Memory().WriteUint32Le(ptr+4, ln_); !ok_ {
		return fmt.Errorf("wacogo/witgen: lowerMemListU32: list len: bad memory write")
	}
	return nil
}

func wrapSum(f *Factory) host.Func {
	return func(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, stack []uint64) error {
		state_ := h.UserState().(*instanceState)
		fnType_ := cc.Instance().ExportedFunc("sum").Type()
		_ = fnType_
		var xs []uint32
		{
			v_, err_ := toGoFlatListU32(ctx, cc, h, fnType_.Params[0].Type, stack[0:2])
			if err_ != nil {
				return err_
			}
			xs = v_
		}
		result_, implErr_ := state_.impl.Sum(ctx, xs)
		if implErr_ != nil {
			return fmt.Errorf("wacogo/witgen: sum: impl returned error: %w", implErr_)
		}
		stack[0] = uint64(result_)
		return nil
	}
}
