// Code generated by wacogo-witgen from sumlist.wit. DO NOT EDIT.

// Package sumlist provides Go bindings for the example:demo/sumlist interface.
package sumlist

import (
	"context"
)

// InterfaceName is the canonical WIT id of the interface this binding
// was generated from.
const InterfaceName = "example:demo/sumlist"

// Sumlist is the Go binding for the example:demo/sumlist interface.
// Implement it to provide a host-side component, or pass an exported wasm
// instance to WrapInstance to obtain a Sumlist that calls into wasm.
// Resource-typed parameters and results appear as *<R>Handle values that can
// be passed across component boundaries.
type Sumlist interface {
	Sum(ctx context.Context, xs []uint32) (uint32, error)
}
