// Code generated by wacogo-witgen from sumlist.wit. DO NOT EDIT.

// Package sumlist provides Go bindings for the example:demo/sumlist interface.
package sumlist

import (
	"context"
	"fmt"

	"github.com/partite-ai/wacogo"
	"github.com/partite-ai/wacogo/host"
)

// sumlistWrapper is the concrete type returned by WrapInstance
// as a Sumlist. Held internally; users hold it via the Sumlist
// interface.
type sumlistWrapper struct {
	callerInst *host.ComponentInstance
	fnSum      *host.ExportedFunc
}

// WrapInstance returns a Sumlist that forwards method calls to
// callee. caller is a Factory-built host instance whose state hosts any
// handles minted by callee during those calls.
func WrapInstance(caller *host.ComponentInstance, callee *wacogo.ComponentInstance) Sumlist {
	w_ := &sumlistWrapper{callerInst: caller}
	w_.fnSum = host.WrapExportedFunc(callee.ExportedFunc("sum"))
	return w_
}
func (w *sumlistWrapper) Sum(ctx context.Context, xs []uint32) (uint32, error) {
	var resVal_ uint32
	var resErr_ error
	arg0_ := xs
	{
		callErr_ := w.fnSum.CallRaw(ctx, w.callerInst,
			func(caller, callee *host.CallContext, stack []uint64) {
				if err_ := lowerFlatListU32(ctx, caller, callee, w.callerInst, w.fnSum.ParamType(0), stack[0:2], arg0_); err_ != nil {
					resErr_ = err_
					return
				}
			},
			func(caller, callee *host.CallContext, stack []uint64) {
				resVal_ = uint32(stack[0])
			},
		)
		if callErr_ != nil {
			return 0, fmt.Errorf("wacogo/witgen: CallRaw failed: %w", callErr_)
		}
		if resErr_ != nil {
			return 0, resErr_
		}
	}
	return resVal_, nil
}
