// Code generated by wacogo-witgen from midpoint.wit. DO NOT EDIT.

// Package midpoint provides Go bindings for the example:demo/midpoint interface.
package midpoint

import (
	"context"
	"fmt"

	"github.com/partite-ai/wacogo"
	"github.com/partite-ai/wacogo/host"
)

// midpointWrapper is the concrete type returned by WrapInstance
// as a Midpoint. Held internally; users hold it via the Midpoint
// interface.
type midpointWrapper struct {
	callerInst *host.ComponentInstance
	fnAvg      *host.ExportedFunc
}

// WrapInstance returns a Midpoint that forwards method calls to
// callee. caller is a Factory-built host instance whose state hosts any
// handles minted by callee during those calls.
func WrapInstance(caller *host.ComponentInstance, callee *wacogo.ComponentInstance) Midpoint {
	w_ := &midpointWrapper{callerInst: caller}
	w_.fnAvg = host.WrapExportedFunc(callee.ExportedFunc("avg"))
	return w_
}
func (w *midpointWrapper) Avg(ctx context.Context, a Point, b Point) (Point, error) {
	var resVal_ Point
	var resErr_ error
	arg0_ := a
	arg1_ := b
	{
		callErr_ := w.fnAvg.CallRaw(ctx, w.callerInst,
			func(caller, callee *host.CallContext, stack []uint64) {
				if err_ := lowerFlatPoint(ctx, caller, callee, w.callerInst, w.fnAvg.ParamType(0), stack[0:2], arg0_); err_ != nil {
					resErr_ = err_
					return
				}
				if err_ := lowerFlatPoint(ctx, caller, callee, w.callerInst, w.fnAvg.ParamType(1), stack[2:4], arg1_); err_ != nil {
					resErr_ = err_
					return
				}
			},
			func(caller, callee *host.CallContext, stack []uint64) {
				if v_, err_ := liftMemPoint(ctx, caller, callee, w.callerInst, w.fnAvg.ResultType(0), uint32(stack[0])); err_ != nil {
					resErr_ = err_
					return
				} else {
					resVal_ = v_
				}
			},
		)
		if callErr_ != nil {
			return Point{}, fmt.Errorf("wacogo/witgen: CallRaw failed: %w", callErr_)
		}
		if resErr_ != nil {
			return Point{}, resErr_
		}
	}
	return resVal_, nil
}
