// Code generated by wacogo-witgen from midpoint.wit. DO NOT EDIT.

// Package midpoint provides Go bindings for the example:demo/midpoint interface.
package midpoint

import (
	"context"
)

// InterfaceName is the canonical WIT id of the interface this binding
// was generated from.
const InterfaceName = "example:demo/midpoint"

// Midpoint is the Go binding for the example:demo/midpoint interface.
// Implement it to provide a host-side component, or pass an exported wasm
// instance to WrapInstance to obtain a Midpoint that calls into wasm.
// Resource-typed parameters and results appear as *<R>Handle values that can
// be passed across component boundaries.
type Midpoint interface {
	Avg(ctx context.Context, a Point, b Point) (Point, error)
}

// Point corresponds to the WIT record point.
type Point struct {
	X uint32
	Y uint32
}
