// Code generated by wacogo-witgen from midpoint.wit. DO NOT EDIT.

// Package midpoint provides Go bindings for the example:demo/midpoint interface.
package midpoint

import (
	"context"
	"fmt"

	"github.com/partite-ai/wacogo"
	"github.com/partite-ai/wacogo/host"
)

// Factory builds host-side instances of the Midpoint interface
// from a Go implementation.
type Factory struct {
	engine *wacogo.Engine
	comp   *host.Component
}

type instanceState struct {
	impl Midpoint
}

// Deps groups the cross-component dependencies required to instantiate
// Midpoint. Pass a populated value via NewInstance.
type Deps struct {
}

// NewFactory creates a Factory bound to e. A single Factory may be
// reused to build multiple instances backed by different implementations.
func NewFactory(ctx context.Context, e *wacogo.Engine) (*Factory, error) {
	f_ := &Factory{engine: e}
	b_ := e.NewHostBuilder("example_demo_midpoint")

	typPoint_ := b_.AddType("point", host.Record{Fields: []host.Field{{Name: "x", Type: host.U32}, {Name: "y", Type: host.U32}}})
	_ = typPoint_

	b_.AddFunction("avg", &host.FuncType{
		Params:  []host.Param{{Name: "a", Type: typPoint_}, {Name: "b", Type: typPoint_}},
		Results: []host.ResultDecl{{Name: "", Type: typPoint_}},
	}, wrapAvg(f_))

	comp_, err_ := b_.Build(ctx)
	if err_ != nil {
		return nil, err_
	}
	f_.comp = comp_
	return f_, nil
}

// NewInstance creates a fresh component instance backed by impl. Pass
// inst.Core() to wacogo.WithInstanceImport to wire the instance into a
// composite world. deps may be nil only when Midpoint has no
// imports.
func (f *Factory) NewInstance(ctx context.Context, impl Midpoint, deps *Deps, opts ...host.InstantiateOption) (*host.ComponentInstance, error) {
	_ = deps
	state_ := &instanceState{impl: impl}
	opts = append(opts, host.WithUserState(state_))
	inst_, err_ := f.comp.Instantiate(ctx, opts...)
	if err_ != nil {
		return nil, err_
	}
	return inst_, nil
}

// Close releases resources shared by the Factory. Existing instances
// remain callable until each is closed individually.
func (f *Factory) Close(ctx context.Context) error { return f.comp.Close(ctx) }

func toGoFlatPoint(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, stack []uint64) (Point, error) {
	var v_ Point
	recT_ := ty.(wacogo.TypeRecord)
	_ = recT_
	v_.X = uint32(stack[0])
	v_.Y = uint32(stack[1])
	return v_, nil
}

func toGoMemPoint(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, ptr uint32) (Point, error) {
	var v_ Point
	recT_ := ty.(wacogo.TypeRecord)
	_ = recT_
	if tmp_, ok_ := cc.Memory().ReadUint32Le(ptr); !ok_ {
		return Point{}, fmt.Errorf("wacogo/witgen: toGoMemPoint: field X: bad memory read")
	} else {
		v_.X = tmp_
	}
	if tmp_, ok_ := cc.Memory().ReadUint32Le(ptr + 4); !ok_ {
		return Point{}, fmt.Errorf("wacogo/witgen: toGoMemPoint: field Y: bad memory read")
	} else {
		v_.Y = tmp_
	}
	return v_, nil
}

func fromGoFlatPoint(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, stack []uint64, v Point) error {
	stack[0] = uint64(v.X)
	stack[1] = uint64(v.Y)
	return nil
}

func fromGoMemPoint(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, ptr uint32, v Point) error {
	if ok_ := cc.Memory().WriteUint32Le(ptr, v.X); !ok_ {
		return fmt.Errorf("wacogo/witgen: fromGoMemPoint: field X: bad memory write")
	}
	if ok_ := cc.Memory().WriteUint32Le(ptr+4, v.Y); !ok_ {
		return fmt.Errorf("wacogo/witgen: fromGoMemPoint: field Y: bad memory write")
	}
	return nil
}

func liftFlatPoint(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, stack []uint64) (Point, error) {
	var v_ Point
	recT_ := ty.(wacogo.TypeRecord)
	_ = recT_
	v_.X = uint32(stack[0])
	v_.Y = uint32(stack[1])
	return v_, nil
}

func liftMemPoint(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, ptr uint32) (Point, error) {
	var v_ Point
	recT_ := ty.(wacogo.TypeRecord)
	_ = recT_
	if tmp_, ok_ := callee.Memory().ReadUint32Le(ptr); !ok_ {
		return Point{}, fmt.Errorf("wacogo/witgen: liftMemPoint: field X: bad memory read")
	} else {
		v_.X = tmp_
	}
	if tmp_, ok_ := callee.Memory().ReadUint32Le(ptr + 4); !ok_ {
		return Point{}, fmt.Errorf("wacogo/witgen: liftMemPoint: field Y: bad memory read")
	} else {
		v_.Y = tmp_
	}
	return v_, nil
}

func lowerFlatPoint(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, stack []uint64, v Point) error {
	recT_ := ty.(wacogo.TypeRecord)
	_ = recT_
	stack[0] = uint64(v.X)
	stack[1] = uint64(v.Y)
	return nil
}

func lowerMemPoint(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, ptr uint32, v Point) error {
	recT_ := ty.(wacogo.TypeRecord)
	_ = recT_
	if ok_ := callee.Memory().WriteUint32Le(ptr, v.X); !ok_ {
		return fmt.Errorf("wacogo/witgen: lowerMemPoint: field X: bad memory write")
	}
	if ok_ := callee.Memory().WriteUint32Le(ptr+4, v.Y); !ok_ {
		return fmt.Errorf("wacogo/witgen: lowerMemPoint: field Y: bad memory write")
	}
	return nil
}

func wrapAvg(f *Factory) host.Func {
	return func(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, stack []uint64) error {
		state_ := h.UserState().(*instanceState)
		fnType_ := cc.Instance().ExportedFunc("avg").Type()
		_ = fnType_
		var a Point
		{
			v_, err_ := toGoFlatPoint(ctx, cc, h, fnType_.Params[0].Type, stack[0:2])
			if err_ != nil {
				return err_
			}
			a = v_
		}
		var b Point
		{
			v_, err_ := toGoFlatPoint(ctx, cc, h, fnType_.Params[1].Type, stack[2:4])
			if err_ != nil {
				return err_
			}
			b = v_
		}
		result_, implErr_ := state_.impl.Avg(ctx, a, b)
		if implErr_ != nil {
			return fmt.Errorf("wacogo/witgen: avg: impl returned error: %w", implErr_)
		}
		outPtr_, rerr_ := cc.Realloc(ctx, 0, 0, 4, 8)
		if rerr_ != nil {
			return fmt.Errorf("wacogo/witgen: avg: realloc failed: %w", rerr_)
		}
		if err_ := fromGoMemPoint(ctx, cc, h, outPtr_, result_); err_ != nil {
			return err_
		}
		stack[0] = uint64(outPtr_)
		return nil
	}
}
