// Code generated by wacogo-witgen from concat.wit. DO NOT EDIT.

// Package concat provides Go bindings for the example:demo/concat interface.
package concat

import (
	"context"
	"fmt"

	"github.com/partite-ai/wacogo"
	"github.com/partite-ai/wacogo/host"
)

// concatWrapper is the concrete type returned by WrapInstance
// as a Concat. Held internally; users hold it via the Concat
// interface.
type concatWrapper struct {
	callerInst *host.ComponentInstance
	fnJoin     *host.ExportedFunc
}

// WrapInstance returns a Concat that forwards method calls to
// callee. caller is a Factory-built host instance whose state hosts any
// handles minted by callee during those calls.
func WrapInstance(caller *host.ComponentInstance, callee *wacogo.ComponentInstance) Concat {
	w_ := &concatWrapper{callerInst: caller}
	w_.fnJoin = host.WrapExportedFunc(callee.ExportedFunc("join"))
	return w_
}
func (w *concatWrapper) Join(ctx context.Context, parts []string, sep string) (string, error) {
	var resVal_ string
	var resErr_ error
	arg0_ := parts
	arg1_ := sep
	{
		callErr_ := w.fnJoin.CallRaw(ctx, w.callerInst,
			func(caller, callee *host.CallContext, stack []uint64) {
				if err_ := lowerFlatListString(ctx, caller, callee, w.callerInst, w.fnJoin.ParamType(0), stack[0:2], arg0_); err_ != nil {
					resErr_ = err_
					return
				}
				if err_ := lowerFlatString(ctx, caller, callee, w.callerInst, w.fnJoin.ParamType(1), stack[2:4], arg1_); err_ != nil {
					resErr_ = err_
					return
				}
			},
			func(caller, callee *host.CallContext, stack []uint64) {
				if v_, err_ := liftMemString(ctx, caller, callee, w.callerInst, w.fnJoin.ResultType(0), uint32(stack[0])); err_ != nil {
					resErr_ = err_
					return
				} else {
					resVal_ = v_
				}
			},
		)
		if callErr_ != nil {
			return "", fmt.Errorf("wacogo/witgen: CallRaw failed: %w", callErr_)
		}
		if resErr_ != nil {
			return "", resErr_
		}
	}
	return resVal_, nil
}
