// Code generated by wacogo-witgen from concat.wit. DO NOT EDIT.

// Package concat provides Go bindings for the example:demo/concat interface.
package concat

import (
	"context"
)

// InterfaceName is the canonical WIT id of the interface this binding
// was generated from.
const InterfaceName = "example:demo/concat"

// Concat is the Go binding for the example:demo/concat interface.
// Implement it to provide a host-side component, or pass an exported wasm
// instance to WrapInstance to obtain a Concat that calls into wasm.
// Resource-typed parameters and results appear as *<R>Handle values that can
// be passed across component boundaries.
type Concat interface {
	Join(ctx context.Context, parts []string, sep string) (string, error)
}
