// Code generated by wacogo-witgen from compass.wit. DO NOT EDIT.

// Package compass provides Go bindings for the example:demo/compass interface.
package compass

import (
	"context"
	"fmt"

	"github.com/partite-ai/wacogo"
	"github.com/partite-ai/wacogo/host"
)

// compassWrapper is the concrete type returned by WrapInstance
// as a Compass. Held internally; users hold it via the Compass
// interface.
type compassWrapper struct {
	callerInst *host.ComponentInstance
	fnReverse  *host.ExportedFunc
}

// WrapInstance returns a Compass that forwards method calls to
// callee. caller is a Factory-built host instance whose state hosts any
// handles minted by callee during those calls.
func WrapInstance(caller *host.ComponentInstance, callee *wacogo.ComponentInstance) Compass {
	w_ := &compassWrapper{callerInst: caller}
	w_.fnReverse = host.WrapExportedFunc(callee.ExportedFunc("reverse"))
	return w_
}
func (w *compassWrapper) Reverse(ctx context.Context, d Direction) (Direction, error) {
	var resVal_ Direction
	arg0_ := d
	{
		callErr_ := w.fnReverse.CallRaw(ctx, w.callerInst,
			func(caller, callee *host.CallContext, stack []uint64) {
				stack[0] = uint64(arg0_)
			},
			func(caller, callee *host.CallContext, stack []uint64) {
				resVal_ = Direction(stack[0])
			},
		)
		if callErr_ != nil {
			return Direction(0), fmt.Errorf("wacogo/witgen: CallRaw failed: %w", callErr_)
		}
	}
	return resVal_, nil
}
