// Code generated by wacogo-witgen from compass.wit. DO NOT EDIT.

// Package compass provides Go bindings for the example:demo/compass interface.
package compass

import (
	"context"
	"fmt"

	"github.com/partite-ai/wacogo"
	"github.com/partite-ai/wacogo/host"
)

// Factory builds host-side instances of the Compass interface
// from a Go implementation.
type Factory struct {
	engine *wacogo.Engine
	comp   *host.Component
}

type instanceState struct {
	impl Compass
}

// Deps groups the cross-component dependencies required to instantiate
// Compass. Pass a populated value via NewInstance.
type Deps struct {
}

// NewFactory creates a Factory bound to e. A single Factory may be
// reused to build multiple instances backed by different implementations.
func NewFactory(ctx context.Context, e *wacogo.Engine) (*Factory, error) {
	f_ := &Factory{engine: e}
	b_ := e.NewHostBuilder("example_demo_compass")

	typDirection_ := b_.AddType("direction", host.Enum{Cases: []string{"north", "south", "east", "west"}})
	_ = typDirection_

	b_.AddFunction("reverse", &host.FuncType{
		Params:  []host.Param{{Name: "d", Type: typDirection_}},
		Results: []host.ResultDecl{{Name: "", Type: typDirection_}},
	}, wrapReverse(f_))

	comp_, err_ := b_.Build(ctx)
	if err_ != nil {
		return nil, err_
	}
	f_.comp = comp_
	return f_, nil
}

// NewInstance creates a fresh component instance backed by impl. Pass
// inst.Core() to wacogo.WithInstanceImport to wire the instance into a
// composite world. deps may be nil only when Compass has no
// imports.
func (f *Factory) NewInstance(ctx context.Context, impl Compass, deps *Deps, opts ...host.InstantiateOption) (*host.ComponentInstance, error) {
	_ = deps
	state_ := &instanceState{impl: impl}
	opts = append(opts, host.WithUserState(state_))
	inst_, err_ := f.comp.Instantiate(ctx, opts...)
	if err_ != nil {
		return nil, err_
	}
	return inst_, nil
}

// Close releases resources shared by the Factory. Existing instances
// remain callable until each is closed individually.
func (f *Factory) Close(ctx context.Context) error { return f.comp.Close(ctx) }

func wrapReverse(f *Factory) host.Func {
	return func(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, stack []uint64) error {
		state_ := h.UserState().(*instanceState)
		fnType_ := cc.Instance().ExportedFunc("reverse").Type()
		_ = fnType_
		d := Direction(stack[0])
		result_, implErr_ := state_.impl.Reverse(ctx, d)
		if implErr_ != nil {
			return fmt.Errorf("wacogo/witgen: reverse: impl returned error: %w", implErr_)
		}
		stack[0] = uint64(result_)
		return nil
	}
}
