// Code generated by wacogo-witgen from compass.wit. DO NOT EDIT.

// Package compass provides Go bindings for the example:demo/compass interface.
package compass

import (
	"context"
)

// InterfaceName is the canonical WIT id of the interface this binding
// was generated from.
const InterfaceName = "example:demo/compass"

// Compass is the Go binding for the example:demo/compass interface.
// Implement it to provide a host-side component, or pass an exported wasm
// instance to WrapInstance to obtain a Compass that calls into wasm.
// Resource-typed parameters and results appear as *<R>Handle values that can
// be passed across component boundaries.
type Compass interface {
	Reverse(ctx context.Context, d Direction) (Direction, error)
}

// Direction corresponds to the WIT enum direction.
type Direction uint8

const (
	DirectionNorth Direction = 0
	DirectionSouth Direction = 1
	DirectionEast  Direction = 2
	DirectionWest  Direction = 3
)

func (v Direction) String() string {
	switch v {
	case DirectionNorth:
		return "north"
	case DirectionSouth:
		return "south"
	case DirectionEast:
		return "east"
	case DirectionWest:
		return "west"
	}
	return "Direction(unknown)"
}
