// Code generated by wacogo-witgen from primlists.wit. DO NOT EDIT.

// One function per primitive element type, for the bulk list copy:
// each takes a list and returns it reversed.
package primlists

import (
	"context"
	"encoding/binary"
	"fmt"
	"math"

	"github.com/partite-ai/wacogo"
	"github.com/partite-ai/wacogo/host"
)

// Factory builds host-side instances of the Primlists interface
// from a Go implementation.
type Factory struct {
	engine *wacogo.Engine
	comp   *host.Component
}

type instanceState struct {
	impl Primlists
}

// Deps groups the cross-component dependencies required to instantiate
// Primlists. Pass a populated value via NewInstance.
type Deps struct {
}

// NewFactory creates a Factory bound to e. A single Factory may be
// reused to build multiple instances backed by different implementations.
func NewFactory(ctx context.Context, e *wacogo.Engine) (*Factory, error) {
	f_ := &Factory{engine: e}
	b_ := e.NewHostBuilder("example_demo_primlists")

	b_.AddFunction("rev-bool", &host.FuncType{
		Params:  []host.Param{{Name: "xs", Type: host.List{Elem: host.Bool}}},
		Results: []host.ResultDecl{{Name: "", Type: host.List{Elem: host.Bool}}},
	}, wrapRevBool(f_))

	b_.AddFunction("rev-char", &host.FuncType{
		Params:  []host.Param{{Name: "xs", Type: host.List{Elem: host.Char}}},
		Results: []host.ResultDecl{{Name: "", Type: host.List{Elem: host.Char}}},
	}, wrapRevChar(f_))

	b_.AddFunction("rev-f32", &host.FuncType{
		Params:  []host.Param{{Name: "xs", Type: host.List{Elem: host.F32}}},
		Results: []host.ResultDecl{{Name: "", Type: host.List{Elem: host.F32}}},
	}, wrapRevF32(f_))

	b_.AddFunction("rev-f64", &host.FuncType{
		Params:  []host.Param{{Name: "xs", Type: host.List{Elem: host.F64}}},
		Results: []host.ResultDecl{{Name: "", Type: host.List{Elem: host.F64}}},
	}, wrapRevF64(f_))

	b_.AddFunction("rev-s16", &host.FuncType{
		Params:  []host.Param{{Name: "xs", Type: host.List{Elem: host.S16}}},
		Results: []host.ResultDecl{{Name: "", Type: host.List{Elem: host.S16}}},
	}, wrapRevS16(f_))

	b_.AddFunction("rev-s32", &host.FuncType{
		Params:  []host.Param{{Name: "xs", Type: host.List{Elem: host.S32}}},
		Results: []host.ResultDecl{{Name: "", Type: host.List{Elem: host.S32}}},
	}, wrapRevS32(f_))

	b_.AddFunction("rev-s64", &host.FuncType{
		Params:  []host.Param{{Name: "xs", Type: host.List{Elem: host.S64}}},
		Results: []host.ResultDecl{{Name: "", Type: host.List{Elem: host.S64}}},
	}, wrapRevS64(f_))

	b_.AddFunction("rev-s8", &host.FuncType{
		Params:  []host.Param{{Name: "xs", Type: host.List{Elem: host.S8}}},
		Results: []host.ResultDecl{{Name: "", Type: host.List{Elem: host.S8}}},
	}, wrapRevS8(f_))

	b_.AddFunction("rev-u16", &host.FuncType{
		Params:  []host.Param{{Name: "xs", Type: host.List{Elem: host.U16}}},
		Results: []host.ResultDecl{{Name: "", Type: host.List{Elem: host.U16}}},
	}, wrapRevU16(f_))

	b_.AddFunction("rev-u32", &host.FuncType{
		Params:  []host.Param{{Name: "xs", Type: host.List{Elem: host.U32}}},
		Results: []host.ResultDecl{{Name: "", Type: host.List{Elem: host.U32}}},
	}, wrapRevU32(f_))

	b_.AddFunction("rev-u64", &host.FuncType{
		Params:  []host.Param{{Name: "xs", Type: host.List{Elem: host.U64}}},
		Results: []host.ResultDecl{{Name: "", Type: host.List{Elem: host.U64}}},
	}, wrapRevU64(f_))

	b_.AddFunction("rev-u8", &host.FuncType{
		Params:  []host.Param{{Name: "xs", Type: host.List{Elem: host.U8}}},
		Results: []host.ResultDecl{{Name: "", Type: host.List{Elem: host.U8}}},
	}, wrapRevU8(f_))

	comp_, err_ := b_.Build(ctx)
	if err_ != nil {
		return nil, err_
	}
	f_.comp = comp_
	return f_, nil
}

// NewInstance creates a fresh component instance backed by impl. Pass
// inst.Core() to wacogo.WithInstanceImport to wire the instance into a
// composite world. deps may be nil only when Primlists has no
// imports.
func (f *Factory) NewInstance(ctx context.Context, impl Primlists, deps *Deps, opts ...host.InstantiateOption) (*host.ComponentInstance, error) {
	_ = deps
	state_ := &instanceState{impl: impl}
	opts = append(opts, host.WithUserState(state_))
	inst_, err_ := f.comp.Instantiate(ctx, opts...)
	if err_ != nil {
		return nil, err_
	}
	return inst_, nil
}

// Close releases resources shared by the Factory. Existing instances
// remain callable until each is closed individually.
func (f *Factory) Close(ctx context.Context) error { return f.comp.Close(ctx) }

func toGoFlatListBool(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, stack []uint64) ([]bool, error) {
	lstT_ := ty.(wacogo.TypeList)
	_ = lstT_
	ptr_ := uint32(stack[0])
	ln_ := uint32(stack[1])
	out_ := make([]bool, ln_)
	n_ := uint64(ln_) * 1
	if n_ > math.MaxUint32 {
		return nil, fmt.Errorf("wacogo/witgen: toGoFlatListBool: elem: bad memory read")
	}
	buf_, ok_ := cc.Memory().Read(ptr_, uint32(n_))
	if !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: toGoFlatListBool: elem: bad memory read")
	}
	for i_ := range out_ {
		o_ := i_ * 1
		out_[i_] = buf_[o_] != 0
	}
	return out_, nil
}

func toGoMemListBool(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, ptr uint32) ([]bool, error) {
	lstT_ := ty.(wacogo.TypeList)
	_ = lstT_
	var lptr_ uint32
	if tmp_, ok_ := cc.Memory().ReadUint32Le(ptr); !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: toGoMemListBool: list ptr: bad memory read")
	} else {
		lptr_ = tmp_
	}
	var ln_ uint32
	if tmp_, ok_ := cc.Memory().ReadUint32Le(ptr + 4); !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: toGoMemListBool: list len: bad memory read")
	} else {
		ln_ = tmp_
	}
	out_ := make([]bool, ln_)
	n_ := uint64(ln_) * 1
	if n_ > math.MaxUint32 {
		return nil, fmt.Errorf("wacogo/witgen: toGoMemListBool: list elem: bad memory read")
	}
	buf_, ok_ := cc.Memory().Read(lptr_, uint32(n_))
	if !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: toGoMemListBool: list elem: bad memory read")
	}
	for i_ := range out_ {
		o_ := i_ * 1
		out_[i_] = buf_[o_] != 0
	}
	return out_, nil
}

func fromGoFlatListBool(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, stack []uint64, v []bool) error {
	ln_ := uint32(len(v))
	ptr_, err_ := cc.Realloc(ctx, 0, 0, 1, ln_*1)
	if err_ != nil {
		return fmt.Errorf("wacogo/witgen: fromGoFlatListBool: realloc failed: %w", err_)
	}
	n_ := uint64(ln_) * 1
	if n_ > math.MaxUint32 {
		return fmt.Errorf("wacogo/witgen: fromGoFlatListBool: list elem: bad memory write")
	}
	buf_, ok_ := cc.Memory().Read(ptr_, uint32(n_))
	if !ok_ {
		return fmt.Errorf("wacogo/witgen: fromGoFlatListBool: list elem: bad memory write")
	}
	for i_, e_ := range v {
		o_ := i_ * 1
		buf_[o_] = 0
		if e_ {
			buf_[o_] = 1
		}
	}
	stack[0] = uint64(ptr_)
	stack[1] = uint64(ln_)
	return nil
}

func fromGoMemListBool(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, ptr uint32, v []bool) error {
	ln_ := uint32(len(v))
	lptr_, err_ := cc.Realloc(ctx, 0, 0, 1, ln_*1)
	if err_ != nil {
		return fmt.Errorf("wacogo/witgen: fromGoMemListBool: realloc failed: %w", err_)
	}
	n_ := uint64(ln_) * 1
	if n_ > math.MaxUint32 {
		return fmt.Errorf("wacogo/witgen: fromGoMemListBool: list elem: bad memory write")
	}
	buf_, ok_ := cc.Memory().Read(lptr_, uint32(n_))
	if !ok_ {
		return fmt.Errorf("wacogo/witgen: fromGoMemListBool: list elem: bad memory write")
	}
	for i_, e_ := range v {
		o_ := i_ * 1
		buf_[o_] = 0
		if e_ {
			buf_[o_] = 1
		}
	}
	if ok_ := cc.Memory().WriteUint32Le(ptr, lptr_); !ok_ {
		return fmt.Errorf("wacogo/witgen: fromGoMemListBool: list ptr: bad memory write")
	}
	if ok_ := cc.Memory().WriteUint32Le(ptr+4, ln_); !ok_ {
		return fmt.Errorf("wacogo/witgen: fromGoMemListBool: list len: bad memory write")
	}
	return nil
}

func liftFlatListBool(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, stack []uint64) ([]bool, error) {
	lstT_ := ty.(wacogo.TypeList)
	_ = lstT_
	ptr_ := uint32(stack[0])
	ln_ := uint32(stack[1])
	out_ := make([]bool, ln_)
	n_ := uint64(ln_) * 1
	if n_ > math.MaxUint32 {
		return nil, fmt.Errorf("wacogo/witgen: liftFlatListBool: elem: bad memory read")
	}
	buf_, ok_ := callee.Memory().Read(ptr_, uint32(n_))
	if !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: liftFlatListBool: elem: bad memory read")
	}
	for i_ := range out_ {
		o_ := i_ * 1
		out_[i_] = buf_[o_] != 0
	}
	return out_, nil
}

func liftMemListBool(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, ptr uint32) ([]bool, error) {
	lstT_ := ty.(wacogo.TypeList)
	_ = lstT_
	var lptr_ uint32
	if tmp_, ok_ := callee.Memory().ReadUint32Le(ptr); !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: liftMemListBool: list ptr: bad memory read")
	} else {
		lptr_ = tmp_
	}
	var ln_ uint32
	if tmp_, ok_ := callee.Memory().ReadUint32Le(ptr + 4); !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: liftMemListBool: list len: bad memory read")
	} else {
		ln_ = tmp_
	}
	out_ := make([]bool, ln_)
	n_ := uint64(ln_) * 1
	if n_ > math.MaxUint32 {
		return nil, fmt.Errorf("wacogo/witgen: liftMemListBool: list elem: bad memory read")
	}
	buf_, ok_ := callee.Memory().Read(lptr_, uint32(n_))
	if !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: liftMemListBool: list elem: bad memory read")
	}
	for i_ := range out_ {
		o_ := i_ * 1
		out_[i_] = buf_[o_] != 0
	}
	return out_, nil
}

func lowerFlatListBool(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, stack []uint64, v []bool) error {
	lstT_ := ty.(wacogo.TypeList)
	_ = lstT_
	ln_ := uint32(len(v))
	ptr_, err_ := callee.Realloc(ctx, 0, 0, 1, ln_*1)
	if err_ != nil {
		return fmt.Errorf("wacogo/witgen: lowerFlatListBool: realloc failed: %w", err_)
	}
	n_ := uint64(ln_) * 1
	if n_ > math.MaxUint32 {
		return fmt.Errorf("wacogo/witgen: lowerFlatListBool: list elem: bad memory write")
	}
	buf_, ok_ := callee.Memory().Read(ptr_, uint32(n_))
	if !ok_ {
		return fmt.Errorf("wacogo/witgen: lowerFlatListBool: list elem: bad memory write")
	}
	for i_, e_ := range v {
		o_ := i_ * 1
		buf_[o_] = 0
		if e_ {
			buf_[o_] = 1
		}
	}
	stack[0] = uint64(ptr_)
	stack[1] = uint64(ln_)
	return nil
}

func lowerMemListBool(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, ptr uint32, v []bool) error {
	lstT_ := ty.(wacogo.TypeList)
	_ = lstT_
	ln_ := uint32(len(v))
	lptr_, err_ := callee.Realloc(ctx, 0, 0, 1, ln_*1)
	if err_ != nil {
		return fmt.Errorf("wacogo/witgen: lowerMemListBool: realloc failed: %w", err_)
	}
	n_ := uint64(ln_) * 1
	if n_ > math.MaxUint32 {
		return fmt.Errorf("wacogo/witgen: lowerMemListBool: list elem: bad memory write")
	}
	buf_, ok_ := callee.Memory().Read(lptr_, uint32(n_))
	if !ok_ {
		return fmt.Errorf("wacogo/witgen: lowerMemListBool: list elem: bad memory write")
	}
	for i_, e_ := range v {
		o_ := i_ * 1
		buf_[o_] = 0
		if e_ {
			buf_[o_] = 1
		}
	}
	if ok_ := callee.Memory().WriteUint32Le(ptr, lptr_); !ok_ {
		return fmt.Errorf("wacogo/witgen: lowerMemListBool: list ptr: bad memory write")
	}
	if ok_ := callee.Memory().WriteUint32Le(ptr+4, ln_); !ok_ {
		return fmt.Errorf("wacogo/witgen: lowerMemListBool: list len: bad memory write")
	}
	return nil
}

func toGoFlatListChar(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, stack []uint64) ([]rune, error) {
	lstT_ := ty.(wacogo.TypeList)
	_ = lstT_
	ptr_ := uint32(stack[0])
	ln_ := uint32(stack[1])
	out_ := make([]rune, ln_)
	n_ := uint64(ln_) * 4
	if n_ > math.MaxUint32 {
		return nil, fmt.Errorf("wacogo/witgen: toGoFlatListChar: elem: bad memory read")
	}
	buf_, ok_ := cc.Memory().Read(ptr_, uint32(n_))
	if !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: toGoFlatListChar: elem: bad memory read")
	}
	for i_ := range out_ {
		o_ := i_ * 4
		out_[i_] = rune(binary.LittleEndian.Uint32(buf_[o_:]))
	}
	return out_, nil
}

func toGoMemListChar(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, ptr uint32) ([]rune, error) {
	lstT_ := ty.(wacogo.TypeList)
	_ = lstT_
	var lptr_ uint32
	if tmp_, ok_ := cc.Memory().ReadUint32Le(ptr); !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: toGoMemListChar: list ptr: bad memory read")
	} else {
		lptr_ = tmp_
	}
	var ln_ uint32
	if tmp_, ok_ := cc.Memory().ReadUint32Le(ptr + 4); !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: toGoMemListChar: list len: bad memory read")
	} else {
		ln_ = tmp_
	}
	out_ := make([]rune, ln_)
	n_ := uint64(ln_) * 4
	if n_ > math.MaxUint32 {
		return nil, fmt.Errorf("wacogo/witgen: toGoMemListChar: list elem: bad memory read")
	}
	buf_, ok_ := cc.Memory().Read(lptr_, uint32(n_))
	if !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: toGoMemListChar: list elem: bad memory read")
	}
	for i_ := range out_ {
		o_ := i_ * 4
		out_[i_] = rune(binary.LittleEndian.Uint32(buf_[o_:]))
	}
	return out_, nil
}

func fromGoFlatListChar(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, stack []uint64, v []rune) error {
	ln_ := uint32(len(v))
	ptr_, err_ := cc.Realloc(ctx, 0, 0, 4, ln_*4)
	if err_ != nil {
		return fmt.Errorf("wacogo/witgen: fromGoFlatListChar: realloc failed: %w", err_)
	}
	n_ := uint64(ln_) * 4
	if n_ > math.MaxUint32 {
		return fmt.Errorf("wacogo/witgen: fromGoFlatListChar: list elem: bad memory write")
	}
	buf_, ok_ := cc.Memory().Read(ptr_, uint32(n_))
	if !ok_ {
		return fmt.Errorf("wacogo/witgen: fromGoFlatListChar: list elem: bad memory write")
	}
	for i_, e_ := range v {
		o_ := i_ * 4
		binary.LittleEndian.PutUint32(buf_[o_:], uint32(e_))
	}
	stack[0] = uint64(ptr_)
	stack[1] = uint64(ln_)
	return nil
}

func fromGoMemListChar(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, ptr uint32, v []rune) error {
	ln_ := uint32(len(v))
	lptr_, err_ := cc.Realloc(ctx, 0, 0, 4, ln_*4)
	if err_ != nil {
		return fmt.Errorf("wacogo/witgen: fromGoMemListChar: realloc failed: %w", err_)
	}
	n_ := uint64(ln_) * 4
	if n_ > math.MaxUint32 {
		return fmt.Errorf("wacogo/witgen: fromGoMemListChar: list elem: bad memory write")
	}
	buf_, ok_ := cc.Memory().Read(lptr_, uint32(n_))
	if !ok_ {
		return fmt.Errorf("wacogo/witgen: fromGoMemListChar: list elem: bad memory write")
	}
	for i_, e_ := range v {
		o_ := i_ * 4
		binary.LittleEndian.PutUint32(buf_[o_:], uint32(e_))
	}
	if ok_ := cc.Memory().WriteUint32Le(ptr, lptr_); !ok_ {
		return fmt.Errorf("wacogo/witgen: fromGoMemListChar: list ptr: bad memory write")
	}
	if ok_ := cc.Memory().WriteUint32Le(ptr+4, ln_); !ok_ {
		return fmt.Errorf("wacogo/witgen: fromGoMemListChar: list len: bad memory write")
	}
	return nil
}

func liftFlatListChar(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, stack []uint64) ([]rune, error) {
	lstT_ := ty.(wacogo.TypeList)
	_ = lstT_
	ptr_ := uint32(stack[0])
	ln_ := uint32(stack[1])
	out_ := make([]rune, ln_)
	n_ := uint64(ln_) * 4
	if n_ > math.MaxUint32 {
		return nil, fmt.Errorf("wacogo/witgen: liftFlatListChar: elem: bad memory read")
	}
	buf_, ok_ := callee.Memory().Read(ptr_, uint32(n_))
	if !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: liftFlatListChar: elem: bad memory read")
	}
	for i_ := range out_ {
		o_ := i_ * 4
		out_[i_] = rune(binary.LittleEndian.Uint32(buf_[o_:]))
	}
	return out_, nil
}

func liftMemListChar(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, ptr uint32) ([]rune, error) {
	lstT_ := ty.(wacogo.TypeList)
	_ = lstT_
	var lptr_ uint32
	if tmp_, ok_ := callee.Memory().ReadUint32Le(ptr); !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: liftMemListChar: list ptr: bad memory read")
	} else {
		lptr_ = tmp_
	}
	var ln_ uint32
	if tmp_, ok_ := callee.Memory().ReadUint32Le(ptr + 4); !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: liftMemListChar: list len: bad memory read")
	} else {
		ln_ = tmp_
	}
	out_ := make([]rune, ln_)
	n_ := uint64(ln_) * 4
	if n_ > math.MaxUint32 {
		return nil, fmt.Errorf("wacogo/witgen: liftMemListChar: list elem: bad memory read")
	}
	buf_, ok_ := callee.Memory().Read(lptr_, uint32(n_))
	if !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: liftMemListChar: list elem: bad memory read")
	}
	for i_ := range out_ {
		o_ := i_ * 4
		out_[i_] = rune(binary.LittleEndian.Uint32(buf_[o_:]))
	}
	return out_, nil
}

func lowerFlatListChar(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, stack []uint64, v []rune) error {
	lstT_ := ty.(wacogo.TypeList)
	_ = lstT_
	ln_ := uint32(len(v))
	ptr_, err_ := callee.Realloc(ctx, 0, 0, 4, ln_*4)
	if err_ != nil {
		return fmt.Errorf("wacogo/witgen: lowerFlatListChar: realloc failed: %w", err_)
	}
	n_ := uint64(ln_) * 4
	if n_ > math.MaxUint32 {
		return fmt.Errorf("wacogo/witgen: lowerFlatListChar: list elem: bad memory write")
	}
	buf_, ok_ := callee.Memory().Read(ptr_, uint32(n_))
	if !ok_ {
		return fmt.Errorf("wacogo/witgen: lowerFlatListChar: list elem: bad memory write")
	}
	for i_, e_ := range v {
		o_ := i_ * 4
		binary.LittleEndian.PutUint32(buf_[o_:], uint32(e_))
	}
	stack[0] = uint64(ptr_)
	stack[1] = uint64(ln_)
	return nil
}

func lowerMemListChar(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, ptr uint32, v []rune) error {
	lstT_ := ty.(wacogo.TypeList)
	_ = lstT_
	ln_ := uint32(len(v))
	lptr_, err_ := callee.Realloc(ctx, 0, 0, 4, ln_*4)
	if err_ != nil {
		return fmt.Errorf("wacogo/witgen: lowerMemListChar: realloc failed: %w", err_)
	}
	n_ := uint64(ln_) * 4
	if n_ > math.MaxUint32 {
		return fmt.Errorf("wacogo/witgen: lowerMemListChar: list elem: bad memory write")
	}
	buf_, ok_ := callee.Memory().Read(lptr_, uint32(n_))
	if !ok_ {
		return fmt.Errorf("wacogo/witgen: lowerMemListChar: list elem: bad memory write")
	}
	for i_, e_ := range v {
		o_ := i_ * 4
		binary.LittleEndian.PutUint32(buf_[o_:], uint32(e_))
	}
	if ok_ := callee.Memory().WriteUint32Le(ptr, lptr_); !ok_ {
		return fmt.Errorf("wacogo/witgen: lowerMemListChar: list ptr: bad memory write")
	}
	if ok_ := callee.Memory().WriteUint32Le(ptr+4, ln_); !ok_ {
		return fmt.Errorf("wacogo/witgen: lowerMemListChar: list len: bad memory write")
	}
	return nil
}

func toGoFlatListF32(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, stack []uint64) ([]float32, error) {
	lstT_ := ty.(wacogo.TypeList)
	_ = lstT_
	ptr_ := uint32(stack[0])
	ln_ := uint32(stack[1])
	out_ := make([]float32, ln_)
	n_ := uint64(ln_) * 4
	if n_ > math.MaxUint32 {
		return nil, fmt.Errorf("wacogo/witgen: toGoFlatListF32: elem: bad memory read")
	}
	buf_, ok_ := cc.Memory().Read(ptr_, uint32(n_))
	if !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: toGoFlatListF32: elem: bad memory read")
	}
	for i_ := range out_ {
		o_ := i_ * 4
		out_[i_] = math.Float32frombits(binary.LittleEndian.Uint32(buf_[o_:]))
	}
	return out_, nil
}

func toGoMemListF32(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, ptr uint32) ([]float32, error) {
	lstT_ := ty.(wacogo.TypeList)
	_ = lstT_
	var lptr_ uint32
	if tmp_, ok_ := cc.Memory().ReadUint32Le(ptr); !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: toGoMemListF32: list ptr: bad memory read")
	} else {
		lptr_ = tmp_
	}
	var ln_ uint32
	if tmp_, ok_ := cc.Memory().ReadUint32Le(ptr + 4); !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: toGoMemListF32: list len: bad memory read")
	} else {
		ln_ = tmp_
	}
	out_ := make([]float32, ln_)
	n_ := uint64(ln_) * 4
	if n_ > math.MaxUint32 {
		return nil, fmt.Errorf("wacogo/witgen: toGoMemListF32: list elem: bad memory read")
	}
	buf_, ok_ := cc.Memory().Read(lptr_, uint32(n_))
	if !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: toGoMemListF32: list elem: bad memory read")
	}
	for i_ := range out_ {
		o_ := i_ * 4
		out_[i_] = math.Float32frombits(binary.LittleEndian.Uint32(buf_[o_:]))
	}
	return out_, nil
}

func fromGoFlatListF32(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, stack []uint64, v []float32) error {
	ln_ := uint32(len(v))
	ptr_, err_ := cc.Realloc(ctx, 0, 0, 4, ln_*4)
	if err_ != nil {
		return fmt.Errorf("wacogo/witgen: fromGoFlatListF32: realloc failed: %w", err_)
	}
	n_ := uint64(ln_) * 4
	if n_ > math.MaxUint32 {
		return fmt.Errorf("wacogo/witgen: fromGoFlatListF32: list elem: bad memory write")
	}
	buf_, ok_ := cc.Memory().Read(ptr_, uint32(n_))
	if !ok_ {
		return fmt.Errorf("wacogo/witgen: fromGoFlatListF32: list elem: bad memory write")
	}
	for i_, e_ := range v {
		o_ := i_ * 4
		binary.LittleEndian.PutUint32(buf_[o_:], math.Float32bits(e_))
	}
	stack[0] = uint64(ptr_)
	stack[1] = uint64(ln_)
	return nil
}

func fromGoMemListF32(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, ptr uint32, v []float32) error {
	ln_ := uint32(len(v))
	lptr_, err_ := cc.Realloc(ctx, 0, 0, 4, ln_*4)
	if err_ != nil {
		return fmt.Errorf("wacogo/witgen: fromGoMemListF32: realloc failed: %w", err_)
	}
	n_ := uint64(ln_) * 4
	if n_ > math.MaxUint32 {
		return fmt.Errorf("wacogo/witgen: fromGoMemListF32: list elem: bad memory write")
	}
	buf_, ok_ := cc.Memory().Read(lptr_, uint32(n_))
	if !ok_ {
		return fmt.Errorf("wacogo/witgen: fromGoMemListF32: list elem: bad memory write")
	}
	for i_, e_ := range v {
		o_ := i_ * 4
		binary.LittleEndian.PutUint32(buf_[o_:], math.Float32bits(e_))
	}
	if ok_ := cc.Memory().WriteUint32Le(ptr, lptr_); !ok_ {
		return fmt.Errorf("wacogo/witgen: fromGoMemListF32: list ptr: bad memory write")
	}
	if ok_ := cc.Memory().WriteUint32Le(ptr+4, ln_); !ok_ {
		return fmt.Errorf("wacogo/witgen: fromGoMemListF32: list len: bad memory write")
	}
	return nil
}

func liftFlatListF32(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, stack []uint64) ([]float32, error) {
	lstT_ := ty.(wacogo.TypeList)
	_ = lstT_
	ptr_ := uint32(stack[0])
	ln_ := uint32(stack[1])
	out_ := make([]float32, ln_)
	n_ := uint64(ln_) * 4
	if n_ > math.MaxUint32 {
		return nil, fmt.Errorf("wacogo/witgen: liftFlatListF32: elem: bad memory read")
	}
	buf_, ok_ := callee.Memory().Read(ptr_, uint32(n_))
	if !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: liftFlatListF32: elem: bad memory read")
	}
	for i_ := range out_ {
		o_ := i_ * 4
		out_[i_] = math.Float32frombits(binary.LittleEndian.Uint32(buf_[o_:]))
	}
	return out_, nil
}

func liftMemListF32(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, ptr uint32) ([]float32, error) {
	lstT_ := ty.(wacogo.TypeList)
	_ = lstT_
	var lptr_ uint32
	if tmp_, ok_ := callee.Memory().ReadUint32Le(ptr); !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: liftMemListF32: list ptr: bad memory read")
	} else {
		lptr_ = tmp_
	}
	var ln_ uint32
	if tmp_, ok_ := callee.Memory().ReadUint32Le(ptr + 4); !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: liftMemListF32: list len: bad memory read")
	} else {
		ln_ = tmp_
	}
	out_ := make([]float32, ln_)
	n_ := uint64(ln_) * 4
	if n_ > math.MaxUint32 {
		return nil, fmt.Errorf("wacogo/witgen: liftMemListF32: list elem: bad memory read")
	}
	buf_, ok_ := callee.Memory().Read(lptr_, uint32(n_))
	if !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: liftMemListF32: list elem: bad memory read")
	}
	for i_ := range out_ {
		o_ := i_ * 4
		out_[i_] = math.Float32frombits(binary.LittleEndian.Uint32(buf_[o_:]))
	}
	return out_, nil
}

func lowerFlatListF32(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, stack []uint64, v []float32) error {
	lstT_ := ty.(wacogo.TypeList)
	_ = lstT_
	ln_ := uint32(len(v))
	ptr_, err_ := callee.Realloc(ctx, 0, 0, 4, ln_*4)
	if err_ != nil {
		return fmt.Errorf("wacogo/witgen: lowerFlatListF32: realloc failed: %w", err_)
	}
	n_ := uint64(ln_) * 4
	if n_ > math.MaxUint32 {
		return fmt.Errorf("wacogo/witgen: lowerFlatListF32: list elem: bad memory write")
	}
	buf_, ok_ := callee.Memory().Read(ptr_, uint32(n_))
	if !ok_ {
		return fmt.Errorf("wacogo/witgen: lowerFlatListF32: list elem: bad memory write")
	}
	for i_, e_ := range v {
		o_ := i_ * 4
		binary.LittleEndian.PutUint32(buf_[o_:], math.Float32bits(e_))
	}
	stack[0] = uint64(ptr_)
	stack[1] = uint64(ln_)
	return nil
}

func lowerMemListF32(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, ptr uint32, v []float32) error {
	lstT_ := ty.(wacogo.TypeList)
	_ = lstT_
	ln_ := uint32(len(v))
	lptr_, err_ := callee.Realloc(ctx, 0, 0, 4, ln_*4)
	if err_ != nil {
		return fmt.Errorf("wacogo/witgen: lowerMemListF32: realloc failed: %w", err_)
	}
	n_ := uint64(ln_) * 4
	if n_ > math.MaxUint32 {
		return fmt.Errorf("wacogo/witgen: lowerMemListF32: list elem: bad memory write")
	}
	buf_, ok_ := callee.Memory().Read(lptr_, uint32(n_))
	if !ok_ {
		return fmt.Errorf("wacogo/witgen: lowerMemListF32: list elem: bad memory write")
	}
	for i_, e_ := range v {
		o_ := i_ * 4
		binary.LittleEndian.PutUint32(buf_[o_:], math.Float32bits(e_))
	}
	if ok_ := callee.Memory().WriteUint32Le(ptr, lptr_); !ok_ {
		return fmt.Errorf("wacogo/witgen: lowerMemListF32: list ptr: bad memory write")
	}
	if ok_ := callee.Memory().WriteUint32Le(ptr+4, ln_); !ok_ {
		return fmt.Errorf("wacogo/witgen: lowerMemListF32: list len: bad memory write")
	}
	return nil
}

func toGoFlatListF64(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, stack []uint64) ([]float64, error) {
	lstT_ := ty.(wacogo.TypeList)
	_ = lstT_
	ptr_ := uint32(stack[0])
	ln_ := uint32(stack[1])
	out_ := make([]float64, ln_)
	n_ := uint64(ln_) * 8
	if n_ > math.MaxUint32 {
		return nil, fmt.Errorf("wacogo/witgen: toGoFlatListF64: elem: bad memory read")
	}
	buf_, ok_ := cc.Memory().Read(ptr_, uint32(n_))
	if !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: toGoFlatListF64: elem: bad memory read")
	}
	for i_ := range out_ {
		o_ := i_ * 8
		out_[i_] = math.Float64frombits(binary.LittleEndian.Uint64(buf_[o_:]))
	}
	return out_, nil
}

func toGoMemListF64(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, ptr uint32) ([]float64, error) {
	lstT_ := ty.(wacogo.TypeList)
	_ = lstT_
	var lptr_ uint32
	if tmp_, ok_ := cc.Memory().ReadUint32Le(ptr); !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: toGoMemListF64: list ptr: bad memory read")
	} else {
		lptr_ = tmp_
	}
	var ln_ uint32
	if tmp_, ok_ := cc.Memory().ReadUint32Le(ptr + 4); !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: toGoMemListF64: list len: bad memory read")
	} else {
		ln_ = tmp_
	}
	out_ := make([]float64, ln_)
	n_ := uint64(ln_) * 8
	if n_ > math.MaxUint32 {
		return nil, fmt.Errorf("wacogo/witgen: toGoMemListF64: list elem: bad memory read")
	}
	buf_, ok_ := cc.Memory().Read(lptr_, uint32(n_))
	if !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: toGoMemListF64: list elem: bad memory read")
	}
	for i_ := range out_ {
		o_ := i_ * 8
		out_[i_] = math.Float64frombits(binary.LittleEndian.Uint64(buf_[o_:]))
	}
	return out_, nil
}

func fromGoFlatListF64(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, stack []uint64, v []float64) error {
	ln_ := uint32(len(v))
	ptr_, err_ := cc.Realloc(ctx, 0, 0, 8, ln_*8)
	if err_ != nil {
		return fmt.Errorf("wacogo/witgen: fromGoFlatListF64: realloc failed: %w", err_)
	}
	n_ := uint64(ln_) * 8
	if n_ > math.MaxUint32 {
		return fmt.Errorf("wacogo/witgen: fromGoFlatListF64: list elem: bad memory write")
	}
	buf_, ok_ := cc.Memory().Read(ptr_, uint32(n_))
	if !ok_ {
		return fmt.Errorf("wacogo/witgen: fromGoFlatListF64: list elem: bad memory write")
	}
	for i_, e_ := range v {
		o_ := i_ * 8
		binary.LittleEndian.PutUint64(buf_[o_:], math.Float64bits(e_))
	}
	stack[0] = uint64(ptr_)
	stack[1] = uint64(ln_)
	return nil
}

func fromGoMemListF64(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, ptr uint32, v []float64) error {
	ln_ := uint32(len(v))
	lptr_, err_ := cc.Realloc(ctx, 0, 0, 8, ln_*8)
	if err_ != nil {
		return fmt.Errorf("wacogo/witgen: fromGoMemListF64: realloc failed: %w", err_)
	}
	n_ := uint64(ln_) * 8
	if n_ > math.MaxUint32 {
		return fmt.Errorf("wacogo/witgen: fromGoMemListF64: list elem: bad memory write")
	}
	buf_, ok_ := cc.Memory().Read(lptr_, uint32(n_))
	if !ok_ {
		return fmt.Errorf("wacogo/witgen: fromGoMemListF64: list elem: bad memory write")
	}
	for i_, e_ := range v {
		o_ := i_ * 8
		binary.LittleEndian.PutUint64(buf_[o_:], math.Float64bits(e_))
	}
	if ok_ := cc.Memory().WriteUint32Le(ptr, lptr_); !ok_ {
		return fmt.Errorf("wacogo/witgen: fromGoMemListF64: list ptr: bad memory write")
	}
	if ok_ := cc.Memory().WriteUint32Le(ptr+4, ln_); !ok_ {
		return fmt.Errorf("wacogo/witgen: fromGoMemListF64: list len: bad memory write")
	}
	return nil
}

func liftFlatListF64(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, stack []uint64) ([]float64, error) {
	lstT_ := ty.(wacogo.TypeList)
	_ = lstT_
	ptr_ := uint32(stack[0])
	ln_ := uint32(stack[1])
	out_ := make([]float64, ln_)
	n_ := uint64(ln_) * 8
	if n_ > math.MaxUint32 {
		return nil, fmt.Errorf("wacogo/witgen: liftFlatListF64: elem: bad memory read")
	}
	buf_, ok_ := callee.Memory().Read(ptr_, uint32(n_))
	if !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: liftFlatListF64: elem: bad memory read")
	}
	for i_ := range out_ {
		o_ := i_ * 8
		out_[i_] = math.Float64frombits(binary.LittleEndian.Uint64(buf_[o_:]))
	}
	return out_, nil
}

func liftMemListF64(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, ptr uint32) ([]float64, error) {
	lstT_ := ty.(wacogo.TypeList)
	_ = lstT_
	var lptr_ uint32
	if tmp_, ok_ := callee.Memory().ReadUint32Le(ptr); !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: liftMemListF64: list ptr: bad memory read")
	} else {
		lptr_ = tmp_
	}
	var ln_ uint32
	if tmp_, ok_ := callee.Memory().ReadUint32Le(ptr + 4); !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: liftMemListF64: list len: bad memory read")
	} else {
		ln_ = tmp_
	}
	out_ := make([]float64, ln_)
	n_ := uint64(ln_) * 8
	if n_ > math.MaxUint32 {
		return nil, fmt.Errorf("wacogo/witgen: liftMemListF64: list elem: bad memory read")
	}
	buf_, ok_ := callee.Memory().Read(lptr_, uint32(n_))
	if !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: liftMemListF64: list elem: bad memory read")
	}
	for i_ := range out_ {
		o_ := i_ * 8
		out_[i_] = math.Float64frombits(binary.LittleEndian.Uint64(buf_[o_:]))
	}
	return out_, nil
}

func lowerFlatListF64(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, stack []uint64, v []float64) error {
	lstT_ := ty.(wacogo.TypeList)
	_ = lstT_
	ln_ := uint32(len(v))
	ptr_, err_ := callee.Realloc(ctx, 0, 0, 8, ln_*8)
	if err_ != nil {
		return fmt.Errorf("wacogo/witgen: lowerFlatListF64: realloc failed: %w", err_)
	}
	n_ := uint64(ln_) * 8
	if n_ > math.MaxUint32 {
		return fmt.Errorf("wacogo/witgen: lowerFlatListF64: list elem: bad memory write")
	}
	buf_, ok_ := callee.Memory().Read(ptr_, uint32(n_))
	if !ok_ {
		return fmt.Errorf("wacogo/witgen: lowerFlatListF64: list elem: bad memory write")
	}
	for i_, e_ := range v {
		o_ := i_ * 8
		binary.LittleEndian.PutUint64(buf_[o_:], math.Float64bits(e_))
	}
	stack[0] = uint64(ptr_)
	stack[1] = uint64(ln_)
	return nil
}

func lowerMemListF64(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, ptr uint32, v []float64) error {
	lstT_ := ty.(wacogo.TypeList)
	_ = lstT_
	ln_ := uint32(len(v))
	lptr_, err_ := callee.Realloc(ctx, 0, 0, 8, ln_*8)
	if err_ != nil {
		return fmt.Errorf("wacogo/witgen: lowerMemListF64: realloc failed: %w", err_)
	}
	n_ := uint64(ln_) * 8
	if n_ > math.MaxUint32 {
		return fmt.Errorf("wacogo/witgen: lowerMemListF64: list elem: bad memory write")
	}
	buf_, ok_ := callee.Memory().Read(lptr_, uint32(n_))
	if !ok_ {
		return fmt.Errorf("wacogo/witgen: lowerMemListF64: list elem: bad memory write")
	}
	for i_, e_ := range v {
		o_ := i_ * 8
		binary.LittleEndian.PutUint64(buf_[o_:], math.Float64bits(e_))
	}
	if ok_ := callee.Memory().WriteUint32Le(ptr, lptr_); !ok_ {
		return fmt.Errorf("wacogo/witgen: lowerMemListF64: list ptr: bad memory write")
	}
	if ok_ := callee.Memory().WriteUint32Le(ptr+4, ln_); !ok_ {
		return fmt.Errorf("wacogo/witgen: lowerMemListF64: list len: bad memory write")
	}
	return nil
}

func toGoFlatListS16(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, stack []uint64) ([]int16, error) {
	lstT_ := ty.(wacogo.TypeList)
	_ = lstT_
	ptr_ := uint32(stack[0])
	ln_ := uint32(stack[1])
	out_ := make([]int16, ln_)
	n_ := uint64(ln_) * 2
	if n_ > math.MaxUint32 {
		return nil, fmt.Errorf("wacogo/witgen: toGoFlatListS16: elem: bad memory read")
	}
	buf_, ok_ := cc.Memory().Read(ptr_, uint32(n_))
	if !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: toGoFlatListS16: elem: bad memory read")
	}
	for i_ := range out_ {
		o_ := i_ * 2
		out_[i_] = int16(binary.LittleEndian.Uint16(buf_[o_:]))
	}
	return out_, nil
}

func toGoMemListS16(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, ptr uint32) ([]int16, error) {
	lstT_ := ty.(wacogo.TypeList)
	_ = lstT_
	var lptr_ uint32
	if tmp_, ok_ := cc.Memory().ReadUint32Le(ptr); !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: toGoMemListS16: list ptr: bad memory read")
	} else {
		lptr_ = tmp_
	}
	var ln_ uint32
	if tmp_, ok_ := cc.Memory().ReadUint32Le(ptr + 4); !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: toGoMemListS16: list len: bad memory read")
	} else {
		ln_ = tmp_
	}
	out_ := make([]int16, ln_)
	n_ := uint64(ln_) * 2
	if n_ > math.MaxUint32 {
		return nil, fmt.Errorf("wacogo/witgen: toGoMemListS16: list elem: bad memory read")
	}
	buf_, ok_ := cc.Memory().Read(lptr_, uint32(n_))
	if !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: toGoMemListS16: list elem: bad memory read")
	}
	for i_ := range out_ {
		o_ := i_ * 2
		out_[i_] = int16(binary.LittleEndian.Uint16(buf_[o_:]))
	}
	return out_, nil
}

func fromGoFlatListS16(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, stack []uint64, v []int16) error {
	ln_ := uint32(len(v))
	ptr_, err_ := cc.Realloc(ctx, 0, 0, 2, ln_*2)
	if err_ != nil {
		return fmt.Errorf("wacogo/witgen: fromGoFlatListS16: realloc failed: %w", err_)
	}
	n_ := uint64(ln_) * 2
	if n_ > math.MaxUint32 {
		return fmt.Errorf("wacogo/witgen: fromGoFlatListS16: list elem: bad memory write")
	}
	buf_, ok_ := cc.Memory().Read(ptr_, uint32(n_))
	if !ok_ {
		return fmt.Errorf("wacogo/witgen: fromGoFlatListS16: list elem: bad memory write")
	}
	for i_, e_ := range v {
		o_ := i_ * 2
		binary.LittleEndian.PutUint16(buf_[o_:], uint16(e_))
	}
	stack[0] = uint64(ptr_)
	stack[1] = uint64(ln_)
	return nil
}

func fromGoMemListS16(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, ptr uint32, v []int16) error {
	ln_ := uint32(len(v))
	lptr_, err_ := cc.Realloc(ctx, 0, 0, 2, ln_*2)
	if err_ != nil {
		return fmt.Errorf("wacogo/witgen: fromGoMemListS16: realloc failed: %w", err_)
	}
	n_ := uint64(ln_) * 2
	if n_ > math.MaxUint32 {
		return fmt.Errorf("wacogo/witgen: fromGoMemListS16: list elem: bad memory write")
	}
	buf_, ok_ := cc.Memory().Read(lptr_, uint32(n_))
	if !ok_ {
		return fmt.Errorf("wacogo/witgen: fromGoMemListS16: list elem: bad memory write")
	}
	for i_, e_ := range v {
		o_ := i_ * 2
		binary.LittleEndian.PutUint16(buf_[o_:], uint16(e_))
	}
	if ok_ := cc.Memory().WriteUint32Le(ptr, lptr_); !ok_ {
		return fmt.Errorf("wacogo/witgen: fromGoMemListS16: list ptr: bad memory write")
	}
	if ok_ := cc.Memory().WriteUint32Le(ptr+4, ln_); !ok_ {
		return fmt.Errorf("wacogo/witgen: fromGoMemListS16: list len: bad memory write")
	}
	return nil
}

func liftFlatListS16(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, stack []uint64) ([]int16, error) {
	lstT_ := ty.(wacogo.TypeList)
	_ = lstT_
	ptr_ := uint32(stack[0])
	ln_ := uint32(stack[1])
	out_ := make([]int16, ln_)
	n_ := uint64(ln_) * 2
	if n_ > math.MaxUint32 {
		return nil, fmt.Errorf("wacogo/witgen: liftFlatListS16: elem: bad memory read")
	}
	buf_, ok_ := callee.Memory().Read(ptr_, uint32(n_))
	if !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: liftFlatListS16: elem: bad memory read")
	}
	for i_ := range out_ {
		o_ := i_ * 2
		out_[i_] = int16(binary.LittleEndian.Uint16(buf_[o_:]))
	}
	return out_, nil
}

func liftMemListS16(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, ptr uint32) ([]int16, error) {
	lstT_ := ty.(wacogo.TypeList)
	_ = lstT_
	var lptr_ uint32
	if tmp_, ok_ := callee.Memory().ReadUint32Le(ptr); !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: liftMemListS16: list ptr: bad memory read")
	} else {
		lptr_ = tmp_
	}
	var ln_ uint32
	if tmp_, ok_ := callee.Memory().ReadUint32Le(ptr + 4); !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: liftMemListS16: list len: bad memory read")
	} else {
		ln_ = tmp_
	}
	out_ := make([]int16, ln_)
	n_ := uint64(ln_) * 2
	if n_ > math.MaxUint32 {
		return nil, fmt.Errorf("wacogo/witgen: liftMemListS16: list elem: bad memory read")
	}
	buf_, ok_ := callee.Memory().Read(lptr_, uint32(n_))
	if !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: liftMemListS16: list elem: bad memory read")
	}
	for i_ := range out_ {
		o_ := i_ * 2
		out_[i_] = int16(binary.LittleEndian.Uint16(buf_[o_:]))
	}
	return out_, nil
}

func lowerFlatListS16(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, stack []uint64, v []int16) error {
	lstT_ := ty.(wacogo.TypeList)
	_ = lstT_
	ln_ := uint32(len(v))
	ptr_, err_ := callee.Realloc(ctx, 0, 0, 2, ln_*2)
	if err_ != nil {
		return fmt.Errorf("wacogo/witgen: lowerFlatListS16: realloc failed: %w", err_)
	}
	n_ := uint64(ln_) * 2
	if n_ > math.MaxUint32 {
		return fmt.Errorf("wacogo/witgen: lowerFlatListS16: list elem: bad memory write")
	}
	buf_, ok_ := callee.Memory().Read(ptr_, uint32(n_))
	if !ok_ {
		return fmt.Errorf("wacogo/witgen: lowerFlatListS16: list elem: bad memory write")
	}
	for i_, e_ := range v {
		o_ := i_ * 2
		binary.LittleEndian.PutUint16(buf_[o_:], uint16(e_))
	}
	stack[0] = uint64(ptr_)
	stack[1] = uint64(ln_)
	return nil
}

func lowerMemListS16(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, ptr uint32, v []int16) error {
	lstT_ := ty.(wacogo.TypeList)
	_ = lstT_
	ln_ := uint32(len(v))
	lptr_, err_ := callee.Realloc(ctx, 0, 0, 2, ln_*2)
	if err_ != nil {
		return fmt.Errorf("wacogo/witgen: lowerMemListS16: realloc failed: %w", err_)
	}
	n_ := uint64(ln_) * 2
	if n_ > math.MaxUint32 {
		return fmt.Errorf("wacogo/witgen: lowerMemListS16: list elem: bad memory write")
	}
	buf_, ok_ := callee.Memory().Read(lptr_, uint32(n_))
	if !ok_ {
		return fmt.Errorf("wacogo/witgen: lowerMemListS16: list elem: bad memory write")
	}
	for i_, e_ := range v {
		o_ := i_ * 2
		binary.LittleEndian.PutUint16(buf_[o_:], uint16(e_))
	}
	if ok_ := callee.Memory().WriteUint32Le(ptr, lptr_); !ok_ {
		return fmt.Errorf("wacogo/witgen: lowerMemListS16: list ptr: bad memory write")
	}
	if ok_ := callee.Memory().WriteUint32Le(ptr+4, ln_); !ok_ {
		return fmt.Errorf("wacogo/witgen: lowerMemListS16: list len: bad memory write")
	}
	return nil
}

func toGoFlatListS32(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, stack []uint64) ([]int32, error) {
	lstT_ := ty.(wacogo.TypeList)
	_ = lstT_
	ptr_ := uint32(stack[0])
	ln_ := uint32(stack[1])
	out_ := make([]int32, ln_)
	n_ := uint64(ln_) * 4
	if n_ > math.MaxUint32 {
		return nil, fmt.Errorf("wacogo/witgen: toGoFlatListS32: elem: bad memory read")
	}
	buf_, ok_ := cc.Memory().Read(ptr_, uint32(n_))
	if !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: toGoFlatListS32: elem: bad memory read")
	}
	for i_ := range out_ {
		o_ := i_ * 4
		out_[i_] = int32(binary.LittleEndian.Uint32(buf_[o_:]))
	}
	return out_, nil
}

func toGoMemListS32(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, ptr uint32) ([]int32, error) {
	lstT_ := ty.(wacogo.TypeList)
	_ = lstT_
	var lptr_ uint32
	if tmp_, ok_ := cc.Memory().ReadUint32Le(ptr); !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: toGoMemListS32: list ptr: bad memory read")
	} else {
		lptr_ = tmp_
	}
	var ln_ uint32
	if tmp_, ok_ := cc.Memory().ReadUint32Le(ptr + 4); !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: toGoMemListS32: list len: bad memory read")
	} else {
		ln_ = tmp_
	}
	out_ := make([]int32, ln_)
	n_ := uint64(ln_) * 4
	if n_ > math.MaxUint32 {
		return nil, fmt.Errorf("wacogo/witgen: toGoMemListS32: list elem: bad memory read")
	}
	buf_, ok_ := cc.Memory().Read(lptr_, uint32(n_))
	if !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: toGoMemListS32: list elem: bad memory read")
	}
	for i_ := range out_ {
		o_ := i_ * 4
		out_[i_] = int32(binary.LittleEndian.Uint32(buf_[o_:]))
	}
	return out_, nil
}

func fromGoFlatListS32(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, stack []uint64, v []int32) error {
	ln_ := uint32(len(v))
	ptr_, err_ := cc.Realloc(ctx, 0, 0, 4, ln_*4)
	if err_ != nil {
		return fmt.Errorf("wacogo/witgen: fromGoFlatListS32: realloc failed: %w", err_)
	}
	n_ := uint64(ln_) * 4
	if n_ > math.MaxUint32 {
		return fmt.Errorf("wacogo/witgen: fromGoFlatListS32: list elem: bad memory write")
	}
	buf_, ok_ := cc.Memory().Read(ptr_, uint32(n_))
	if !ok_ {
		return fmt.Errorf("wacogo/witgen: fromGoFlatListS32: list elem: bad memory write")
	}
	for i_, e_ := range v {
		o_ := i_ * 4
		binary.LittleEndian.PutUint32(buf_[o_:], uint32(e_))
	}
	stack[0] = uint64(ptr_)
	stack[1] = uint64(ln_)
	return nil
}

func fromGoMemListS32(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, ptr uint32, v []int32) error {
	ln_ := uint32(len(v))
	lptr_, err_ := cc.Realloc(ctx, 0, 0, 4, ln_*4)
	if err_ != nil {
		return fmt.Errorf("wacogo/witgen: fromGoMemListS32: realloc failed: %w", err_)
	}
	n_ := uint64(ln_) * 4
	if n_ > math.MaxUint32 {
		return fmt.Errorf("wacogo/witgen: fromGoMemListS32: list elem: bad memory write")
	}
	buf_, ok_ := cc.Memory().Read(lptr_, uint32(n_))
	if !ok_ {
		return fmt.Errorf("wacogo/witgen: fromGoMemListS32: list elem: bad memory write")
	}
	for i_, e_ := range v {
		o_ := i_ * 4
		binary.LittleEndian.PutUint32(buf_[o_:], uint32(e_))
	}
	if ok_ := cc.Memory().WriteUint32Le(ptr, lptr_); !ok_ {
		return fmt.Errorf("wacogo/witgen: fromGoMemListS32: list ptr: bad memory write")
	}
	if ok_ := cc.Memory().WriteUint32Le(ptr+4, ln_); !ok_ {
		return fmt.Errorf("wacogo/witgen: fromGoMemListS32: list len: bad memory write")
	}
	return nil
}

func liftFlatListS32(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, stack []uint64) ([]int32, error) {
	lstT_ := ty.(wacogo.TypeList)
	_ = lstT_
	ptr_ := uint32(stack[0])
	ln_ := uint32(stack[1])
	out_ := make([]int32, ln_)
	n_ := uint64(ln_) * 4
	if n_ > math.MaxUint32 {
		return nil, fmt.Errorf("wacogo/witgen: liftFlatListS32: elem: bad memory read")
	}
	buf_, ok_ := callee.Memory().Read(ptr_, uint32(n_))
	if !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: liftFlatListS32: elem: bad memory read")
	}
	for i_ := range out_ {
		o_ := i_ * 4
		out_[i_] = int32(binary.LittleEndian.Uint32(buf_[o_:]))
	}
	return out_, nil
}

func liftMemListS32(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, ptr uint32) ([]int32, error) {
	lstT_ := ty.(wacogo.TypeList)
	_ = lstT_
	var lptr_ uint32
	if tmp_, ok_ := callee.Memory().ReadUint32Le(ptr); !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: liftMemListS32: list ptr: bad memory read")
	} else {
		lptr_ = tmp_
	}
	var ln_ uint32
	if tmp_, ok_ := callee.Memory().ReadUint32Le(ptr + 4); !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: liftMemListS32: list len: bad memory read")
	} else {
		ln_ = tmp_
	}
	out_ := make([]int32, ln_)
	n_ := uint64(ln_) * 4
	if n_ > math.MaxUint32 {
		return nil, fmt.Errorf("wacogo/witgen: liftMemListS32: list elem: bad memory read")
	}
	buf_, ok_ := callee.Memory().Read(lptr_, uint32(n_))
	if !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: liftMemListS32: list elem: bad memory read")
	}
	for i_ := range out_ {
		o_ := i_ * 4
		out_[i_] = int32(binary.LittleEndian.Uint32(buf_[o_:]))
	}
	return out_, nil
}

func lowerFlatListS32(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, stack []uint64, v []int32) error {
	lstT_ := ty.(wacogo.TypeList)
	_ = lstT_
	ln_ := uint32(len(v))
	ptr_, err_ := callee.Realloc(ctx, 0, 0, 4, ln_*4)
	if err_ != nil {
		return fmt.Errorf("wacogo/witgen: lowerFlatListS32: realloc failed: %w", err_)
	}
	n_ := uint64(ln_) * 4
	if n_ > math.MaxUint32 {
		return fmt.Errorf("wacogo/witgen: lowerFlatListS32: list elem: bad memory write")
	}
	buf_, ok_ := callee.Memory().Read(ptr_, uint32(n_))
	if !ok_ {
		return fmt.Errorf("wacogo/witgen: lowerFlatListS32: list elem: bad memory write")
	}
	for i_, e_ := range v {
		o_ := i_ * 4
		binary.LittleEndian.PutUint32(buf_[o_:], uint32(e_))
	}
	stack[0] = uint64(ptr_)
	stack[1] = uint64(ln_)
	return nil
}

func lowerMemListS32(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, ptr uint32, v []int32) error {
	lstT_ := ty.(wacogo.TypeList)
	_ = lstT_
	ln_ := uint32(len(v))
	lptr_, err_ := callee.Realloc(ctx, 0, 0, 4, ln_*4)
	if err_ != nil {
		return fmt.Errorf("wacogo/witgen: lowerMemListS32: realloc failed: %w", err_)
	}
	n_ := uint64(ln_) * 4
	if n_ > math.MaxUint32 {
		return fmt.Errorf("wacogo/witgen: lowerMemListS32: list elem: bad memory write")
	}
	buf_, ok_ := callee.Memory().Read(lptr_, uint32(n_))
	if !ok_ {
		return fmt.Errorf("wacogo/witgen: lowerMemListS32: list elem: bad memory write")
	}
	for i_, e_ := range v {
		o_ := i_ * 4
		binary.LittleEndian.PutUint32(buf_[o_:], uint32(e_))
	}
	if ok_ := callee.Memory().WriteUint32Le(ptr, lptr_); !ok_ {
		return fmt.Errorf("wacogo/witgen: lowerMemListS32: list ptr: bad memory write")
	}
	if ok_ := callee.Memory().WriteUint32Le(ptr+4, ln_); !ok_ {
		return fmt.Errorf("wacogo/witgen: lowerMemListS32: list len: bad memory write")
	}
	return nil
}

func toGoFlatListS64(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, stack []uint64) ([]int64, error) {
	lstT_ := ty.(wacogo.TypeList)
	_ = lstT_
	ptr_ := uint32(stack[0])
	ln_ := uint32(stack[1])
	out_ := make([]int64, ln_)
	n_ := uint64(ln_) * 8
	if n_ > math.MaxUint32 {
		return nil, fmt.Errorf("wacogo/witgen: toGoFlatListS64: elem: bad memory read")
	}
	buf_, ok_ := cc.Memory().Read(ptr_, uint32(n_))
	if !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: toGoFlatListS64: elem: bad memory read")
	}
	for i_ := range out_ {
		o_ := i_ * 8
		out_[i_] = int64(binary.LittleEndian.Uint64(buf_[o_:]))
	}
	return out_, nil
}

func toGoMemListS64(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, ptr uint32) ([]int64, error) {
	lstT_ := ty.(wacogo.TypeList)
	_ = lstT_
	var lptr_ uint32
	if tmp_, ok_ := cc.Memory().ReadUint32Le(ptr); !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: toGoMemListS64: list ptr: bad memory read")
	} else {
		lptr_ = tmp_
	}
	var ln_ uint32
	if tmp_, ok_ := cc.Memory().ReadUint32Le(ptr + 4); !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: toGoMemListS64: list len: bad memory read")
	} else {
		ln_ = tmp_
	}
	out_ := make([]int64, ln_)
	n_ := uint64(ln_) * 8
	if n_ > math.MaxUint32 {
		return nil, fmt.Errorf("wacogo/witgen: toGoMemListS64: list elem: bad memory read")
	}
	buf_, ok_ := cc.Memory().Read(lptr_, uint32(n_))
	if !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: toGoMemListS64: list elem: bad memory read")
	}
	for i_ := range out_ {
		o_ := i_ * 8
		out_[i_] = int64(binary.LittleEndian.Uint64(buf_[o_:]))
	}
	return out_, nil
}

func fromGoFlatListS64(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, stack []uint64, v []int64) error {
	ln_ := uint32(len(v))
	ptr_, err_ := cc.Realloc(ctx, 0, 0, 8, ln_*8)
	if err_ != nil {
		return fmt.Errorf("wacogo/witgen: fromGoFlatListS64: realloc failed: %w", err_)
	}
	n_ := uint64(ln_) * 8
	if n_ > math.MaxUint32 {
		return fmt.Errorf("wacogo/witgen: fromGoFlatListS64: list elem: bad memory write")
	}
	buf_, ok_ := cc.Memory().Read(ptr_, uint32(n_))
	if !ok_ {
		return fmt.Errorf("wacogo/witgen: fromGoFlatListS64: list elem: bad memory write")
	}
	for i_, e_ := range v {
		o_ := i_ * 8
		binary.LittleEndian.PutUint64(buf_[o_:], uint64(e_))
	}
	stack[0] = uint64(ptr_)
	stack[1] = uint64(ln_)
	return nil
}

func fromGoMemListS64(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, ptr uint32, v []int64) error {
	ln_ := uint32(len(v))
	lptr_, err_ := cc.Realloc(ctx, 0, 0, 8, ln_*8)
	if err_ != nil {
		return fmt.Errorf("wacogo/witgen: fromGoMemListS64: realloc failed: %w", err_)
	}
	n_ := uint64(ln_) * 8
	if n_ > math.MaxUint32 {
		return fmt.Errorf("wacogo/witgen: fromGoMemListS64: list elem: bad memory write")
	}
	buf_, ok_ := cc.Memory().Read(lptr_, uint32(n_))
	if !ok_ {
		return fmt.Errorf("wacogo/witgen: fromGoMemListS64: list elem: bad memory write")
	}
	for i_, e_ := range v {
		o_ := i_ * 8
		binary.LittleEndian.PutUint64(buf_[o_:], uint64(e_))
	}
	if ok_ := cc.Memory().WriteUint32Le(ptr, lptr_); !ok_ {
		return fmt.Errorf("wacogo/witgen: fromGoMemListS64: list ptr: bad memory write")
	}
	if ok_ := cc.Memory().WriteUint32Le(ptr+4, ln_); !ok_ {
		return fmt.Errorf("wacogo/witgen: fromGoMemListS64: list len: bad memory write")
	}
	return nil
}

func liftFlatListS64(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, stack []uint64) ([]int64, error) {
	lstT_ := ty.(wacogo.TypeList)
	_ = lstT_
	ptr_ := uint32(stack[0])
	ln_ := uint32(stack[1])
	out_ := make([]int64, ln_)
	n_ := uint64(ln_) * 8
	if n_ > math.MaxUint32 {
		return nil, fmt.Errorf("wacogo/witgen: liftFlatListS64: elem: bad memory read")
	}
	buf_, ok_ := callee.Memory().Read(ptr_, uint32(n_))
	if !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: liftFlatListS64: elem: bad memory read")
	}
	for i_ := range out_ {
		o_ := i_ * 8
		out_[i_] = int64(binary.LittleEndian.Uint64(buf_[o_:]))
	}
	return out_, nil
}

func liftMemListS64(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, ptr uint32) ([]int64, error) {
	lstT_ := ty.(wacogo.TypeList)
	_ = lstT_
	var lptr_ uint32
	if tmp_, ok_ := callee.Memory().ReadUint32Le(ptr); !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: liftMemListS64: list ptr: bad memory read")
	} else {
		lptr_ = tmp_
	}
	var ln_ uint32
	if tmp_, ok_ := callee.Memory().ReadUint32Le(ptr + 4); !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: liftMemListS64: list len: bad memory read")
	} else {
		ln_ = tmp_
	}
	out_ := make([]int64, ln_)
	n_ := uint64(ln_) * 8
	if n_ > math.MaxUint32 {
		return nil, fmt.Errorf("wacogo/witgen: liftMemListS64: list elem: bad memory read")
	}
	buf_, ok_ := callee.Memory().Read(lptr_, uint32(n_))
	if !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: liftMemListS64: list elem: bad memory read")
	}
	for i_ := range out_ {
		o_ := i_ * 8
		out_[i_] = int64(binary.LittleEndian.Uint64(buf_[o_:]))
	}
	return out_, nil
}

func lowerFlatListS64(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, stack []uint64, v []int64) error {
	lstT_ := ty.(wacogo.TypeList)
	_ = lstT_
	ln_ := uint32(len(v))
	ptr_, err_ := callee.Realloc(ctx, 0, 0, 8, ln_*8)
	if err_ != nil {
		return fmt.Errorf("wacogo/witgen: lowerFlatListS64: realloc failed: %w", err_)
	}
	n_ := uint64(ln_) * 8
	if n_ > math.MaxUint32 {
		return fmt.Errorf("wacogo/witgen: lowerFlatListS64: list elem: bad memory write")
	}
	buf_, ok_ := callee.Memory().Read(ptr_, uint32(n_))
	if !ok_ {
		return fmt.Errorf("wacogo/witgen: lowerFlatListS64: list elem: bad memory write")
	}
	for i_, e_ := range v {
		o_ := i_ * 8
		binary.LittleEndian.PutUint64(buf_[o_:], uint64(e_))
	}
	stack[0] = uint64(ptr_)
	stack[1] = uint64(ln_)
	return nil
}

func lowerMemListS64(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, ptr uint32, v []int64) error {
	lstT_ := ty.(wacogo.TypeList)
	_ = lstT_
	ln_ := uint32(len(v))
	lptr_, err_ := callee.Realloc(ctx, 0, 0, 8, ln_*8)
	if err_ != nil {
		return fmt.Errorf("wacogo/witgen: lowerMemListS64: realloc failed: %w", err_)
	}
	n_ := uint64(ln_) * 8
	if n_ > math.MaxUint32 {
		return fmt.Errorf("wacogo/witgen: lowerMemListS64: list elem: bad memory write")
	}
	buf_, ok_ := callee.Memory().Read(lptr_, uint32(n_))
	if !ok_ {
		return fmt.Errorf("wacogo/witgen: lowerMemListS64: list elem: bad memory write")
	}
	for i_, e_ := range v {
		o_ := i_ * 8
		binary.LittleEndian.PutUint64(buf_[o_:], uint64(e_))
	}
	if ok_ := callee.Memory().WriteUint32Le(ptr, lptr_); !ok_ {
		return fmt.Errorf("wacogo/witgen: lowerMemListS64: list ptr: bad memory write")
	}
	if ok_ := callee.Memory().WriteUint32Le(ptr+4, ln_); !ok_ {
		return fmt.Errorf("wacogo/witgen: lowerMemListS64: list len: bad memory write")
	}
	return nil
}

func toGoFlatListS8(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, stack []uint64) ([]int8, error) {
	lstT_ := ty.(wacogo.TypeList)
	_ = lstT_
	ptr_ := uint32(stack[0])
	ln_ := uint32(stack[1])
	out_ := make([]int8, ln_)
	n_ := uint64(ln_) * 1
	if n_ > math.MaxUint32 {
		return nil, fmt.Errorf("wacogo/witgen: toGoFlatListS8: elem: bad memory read")
	}
	buf_, ok_ := cc.Memory().Read(ptr_, uint32(n_))
	if !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: toGoFlatListS8: elem: bad memory read")
	}
	for i_ := range out_ {
		o_ := i_ * 1
		out_[i_] = int8(buf_[o_])
	}
	return out_, nil
}

func toGoMemListS8(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, ptr uint32) ([]int8, error) {
	lstT_ := ty.(wacogo.TypeList)
	_ = lstT_
	var lptr_ uint32
	if tmp_, ok_ := cc.Memory().ReadUint32Le(ptr); !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: toGoMemListS8: list ptr: bad memory read")
	} else {
		lptr_ = tmp_
	}
	var ln_ uint32
	if tmp_, ok_ := cc.Memory().ReadUint32Le(ptr + 4); !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: toGoMemListS8: list len: bad memory read")
	} else {
		ln_ = tmp_
	}
	out_ := make([]int8, ln_)
	n_ := uint64(ln_) * 1
	if n_ > math.MaxUint32 {
		return nil, fmt.Errorf("wacogo/witgen: toGoMemListS8: list elem: bad memory read")
	}
	buf_, ok_ := cc.Memory().Read(lptr_, uint32(n_))
	if !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: toGoMemListS8: list elem: bad memory read")
	}
	for i_ := range out_ {
		o_ := i_ * 1
		out_[i_] = int8(buf_[o_])
	}
	return out_, nil
}

func fromGoFlatListS8(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, stack []uint64, v []int8) error {
	ln_ := uint32(len(v))
	ptr_, err_ := cc.Realloc(ctx, 0, 0, 1, ln_*1)
	if err_ != nil {
		return fmt.Errorf("wacogo/witgen: fromGoFlatListS8: realloc failed: %w", err_)
	}
	n_ := uint64(ln_) * 1
	if n_ > math.MaxUint32 {
		return fmt.Errorf("wacogo/witgen: fromGoFlatListS8: list elem: bad memory write")
	}
	buf_, ok_ := cc.Memory().Read(ptr_, uint32(n_))
	if !ok_ {
		return fmt.Errorf("wacogo/witgen: fromGoFlatListS8: list elem: bad memory write")
	}
	for i_, e_ := range v {
		o_ := i_ * 1
		buf_[o_] = byte(e_)
	}
	stack[0] = uint64(ptr_)
	stack[1] = uint64(ln_)
	return nil
}

func fromGoMemListS8(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, ptr uint32, v []int8) error {
	ln_ := uint32(len(v))
	lptr_, err_ := cc.Realloc(ctx, 0, 0, 1, ln_*1)
	if err_ != nil {
		return fmt.Errorf("wacogo/witgen: fromGoMemListS8: realloc failed: %w", err_)
	}
	n_ := uint64(ln_) * 1
	if n_ > math.MaxUint32 {
		return fmt.Errorf("wacogo/witgen: fromGoMemListS8: list elem: bad memory write")
	}
	buf_, ok_ := cc.Memory().Read(lptr_, uint32(n_))
	if !ok_ {
		return fmt.Errorf("wacogo/witgen: fromGoMemListS8: list elem: bad memory write")
	}
	for i_, e_ := range v {
		o_ := i_ * 1
		buf_[o_] = byte(e_)
	}
	if ok_ := cc.Memory().WriteUint32Le(ptr, lptr_); !ok_ {
		return fmt.Errorf("wacogo/witgen: fromGoMemListS8: list ptr: bad memory write")
	}
	if ok_ := cc.Memory().WriteUint32Le(ptr+4, ln_); !ok_ {
		return fmt.Errorf("wacogo/witgen: fromGoMemListS8: list len: bad memory write")
	}
	return nil
}

func liftFlatListS8(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, stack []uint64) ([]int8, error) {
	lstT_ := ty.(wacogo.TypeList)
	_ = lstT_
	ptr_ := uint32(stack[0])
	ln_ := uint32(stack[1])
	out_ := make([]int8, ln_)
	n_ := uint64(ln_) * 1
	if n_ > math.MaxUint32 {
		return nil, fmt.Errorf("wacogo/witgen: liftFlatListS8: elem: bad memory read")
	}
	buf_, ok_ := callee.Memory().Read(ptr_, uint32(n_))
	if !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: liftFlatListS8: elem: bad memory read")
	}
	for i_ := range out_ {
		o_ := i_ * 1
		out_[i_] = int8(buf_[o_])
	}
	return out_, nil
}

func liftMemListS8(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, ptr uint32) ([]int8, error) {
	lstT_ := ty.(wacogo.TypeList)
	_ = lstT_
	var lptr_ uint32
	if tmp_, ok_ := callee.Memory().ReadUint32Le(ptr); !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: liftMemListS8: list ptr: bad memory read")
	} else {
		lptr_ = tmp_
	}
	var ln_ uint32
	if tmp_, ok_ := callee.Memory().ReadUint32Le(ptr + 4); !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: liftMemListS8: list len: bad memory read")
	} else {
		ln_ = tmp_
	}
	out_ := make([]int8, ln_)
	n_ := uint64(ln_) * 1
	if n_ > math.MaxUint32 {
		return nil, fmt.Errorf("wacogo/witgen: liftMemListS8: list elem: bad memory read")
	}
	buf_, ok_ := callee.Memory().Read(lptr_, uint32(n_))
	if !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: liftMemListS8: list elem: bad memory read")
	}
	for i_ := range out_ {
		o_ := i_ * 1
		out_[i_] = int8(buf_[o_])
	}
	return out_, nil
}

func lowerFlatListS8(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, stack []uint64, v []int8) error {
	lstT_ := ty.(wacogo.TypeList)
	_ = lstT_
	ln_ := uint32(len(v))
	ptr_, err_ := callee.Realloc(ctx, 0, 0, 1, ln_*1)
	if err_ != nil {
		return fmt.Errorf("wacogo/witgen: lowerFlatListS8: realloc failed: %w", err_)
	}
	n_ := uint64(ln_) * 1
	if n_ > math.MaxUint32 {
		return fmt.Errorf("wacogo/witgen: lowerFlatListS8: list elem: bad memory write")
	}
	buf_, ok_ := callee.Memory().Read(ptr_, uint32(n_))
	if !ok_ {
		return fmt.Errorf("wacogo/witgen: lowerFlatListS8: list elem: bad memory write")
	}
	for i_, e_ := range v {
		o_ := i_ * 1
		buf_[o_] = byte(e_)
	}
	stack[0] = uint64(ptr_)
	stack[1] = uint64(ln_)
	return nil
}

func lowerMemListS8(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, ptr uint32, v []int8) error {
	lstT_ := ty.(wacogo.TypeList)
	_ = lstT_
	ln_ := uint32(len(v))
	lptr_, err_ := callee.Realloc(ctx, 0, 0, 1, ln_*1)
	if err_ != nil {
		return fmt.Errorf("wacogo/witgen: lowerMemListS8: realloc failed: %w", err_)
	}
	n_ := uint64(ln_) * 1
	if n_ > math.MaxUint32 {
		return fmt.Errorf("wacogo/witgen: lowerMemListS8: list elem: bad memory write")
	}
	buf_, ok_ := callee.Memory().Read(lptr_, uint32(n_))
	if !ok_ {
		return fmt.Errorf("wacogo/witgen: lowerMemListS8: list elem: bad memory write")
	}
	for i_, e_ := range v {
		o_ := i_ * 1
		buf_[o_] = byte(e_)
	}
	if ok_ := callee.Memory().WriteUint32Le(ptr, lptr_); !ok_ {
		return fmt.Errorf("wacogo/witgen: lowerMemListS8: list ptr: bad memory write")
	}
	if ok_ := callee.Memory().WriteUint32Le(ptr+4, ln_); !ok_ {
		return fmt.Errorf("wacogo/witgen: lowerMemListS8: list len: bad memory write")
	}
	return nil
}

func toGoFlatListU16(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, stack []uint64) ([]uint16, error) {
	lstT_ := ty.(wacogo.TypeList)
	_ = lstT_
	ptr_ := uint32(stack[0])
	ln_ := uint32(stack[1])
	out_ := make([]uint16, ln_)
	n_ := uint64(ln_) * 2
	if n_ > math.MaxUint32 {
		return nil, fmt.Errorf("wacogo/witgen: toGoFlatListU16: elem: bad memory read")
	}
	buf_, ok_ := cc.Memory().Read(ptr_, uint32(n_))
	if !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: toGoFlatListU16: elem: bad memory read")
	}
	for i_ := range out_ {
		o_ := i_ * 2
		out_[i_] = binary.LittleEndian.Uint16(buf_[o_:])
	}
	return out_, nil
}

func toGoMemListU16(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, ptr uint32) ([]uint16, error) {
	lstT_ := ty.(wacogo.TypeList)
	_ = lstT_
	var lptr_ uint32
	if tmp_, ok_ := cc.Memory().ReadUint32Le(ptr); !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: toGoMemListU16: list ptr: bad memory read")
	} else {
		lptr_ = tmp_
	}
	var ln_ uint32
	if tmp_, ok_ := cc.Memory().ReadUint32Le(ptr + 4); !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: toGoMemListU16: list len: bad memory read")
	} else {
		ln_ = tmp_
	}
	out_ := make([]uint16, ln_)
	n_ := uint64(ln_) * 2
	if n_ > math.MaxUint32 {
		return nil, fmt.Errorf("wacogo/witgen: toGoMemListU16: list elem: bad memory read")
	}
	buf_, ok_ := cc.Memory().Read(lptr_, uint32(n_))
	if !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: toGoMemListU16: list elem: bad memory read")
	}
	for i_ := range out_ {
		o_ := i_ * 2
		out_[i_] = binary.LittleEndian.Uint16(buf_[o_:])
	}
	return out_, nil
}

func fromGoFlatListU16(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, stack []uint64, v []uint16) error {
	ln_ := uint32(len(v))
	ptr_, err_ := cc.Realloc(ctx, 0, 0, 2, ln_*2)
	if err_ != nil {
		return fmt.Errorf("wacogo/witgen: fromGoFlatListU16: realloc failed: %w", err_)
	}
	n_ := uint64(ln_) * 2
	if n_ > math.MaxUint32 {
		return fmt.Errorf("wacogo/witgen: fromGoFlatListU16: list elem: bad memory write")
	}
	buf_, ok_ := cc.Memory().Read(ptr_, uint32(n_))
	if !ok_ {
		return fmt.Errorf("wacogo/witgen: fromGoFlatListU16: list elem: bad memory write")
	}
	for i_, e_ := range v {
		o_ := i_ * 2
		binary.LittleEndian.PutUint16(buf_[o_:], e_)
	}
	stack[0] = uint64(ptr_)
	stack[1] = uint64(ln_)
	return nil
}

func fromGoMemListU16(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, ptr uint32, v []uint16) error {
	ln_ := uint32(len(v))
	lptr_, err_ := cc.Realloc(ctx, 0, 0, 2, ln_*2)
	if err_ != nil {
		return fmt.Errorf("wacogo/witgen: fromGoMemListU16: realloc failed: %w", err_)
	}
	n_ := uint64(ln_) * 2
	if n_ > math.MaxUint32 {
		return fmt.Errorf("wacogo/witgen: fromGoMemListU16: list elem: bad memory write")
	}
	buf_, ok_ := cc.Memory().Read(lptr_, uint32(n_))
	if !ok_ {
		return fmt.Errorf("wacogo/witgen: fromGoMemListU16: list elem: bad memory write")
	}
	for i_, e_ := range v {
		o_ := i_ * 2
		binary.LittleEndian.PutUint16(buf_[o_:], e_)
	}
	if ok_ := cc.Memory().WriteUint32Le(ptr, lptr_); !ok_ {
		return fmt.Errorf("wacogo/witgen: fromGoMemListU16: list ptr: bad memory write")
	}
	if ok_ := cc.Memory().WriteUint32Le(ptr+4, ln_); !ok_ {
		return fmt.Errorf("wacogo/witgen: fromGoMemListU16: list len: bad memory write")
	}
	return nil
}

func liftFlatListU16(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, stack []uint64) ([]uint16, error) {
	lstT_ := ty.(wacogo.TypeList)
	_ = lstT_
	ptr_ := uint32(stack[0])
	ln_ := uint32(stack[1])
	out_ := make([]uint16, ln_)
	n_ := uint64(ln_) * 2
	if n_ > math.MaxUint32 {
		return nil, fmt.Errorf("wacogo/witgen: liftFlatListU16: elem: bad memory read")
	}
	buf_, ok_ := callee.Memory().Read(ptr_, uint32(n_))
	if !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: liftFlatListU16: elem: bad memory read")
	}
	for i_ := range out_ {
		o_ := i_ * 2
		out_[i_] = binary.LittleEndian.Uint16(buf_[o_:])
	}
	return out_, nil
}

func liftMemListU16(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, ptr uint32) ([]uint16, error) {
	lstT_ := ty.(wacogo.TypeList)
	_ = lstT_
	var lptr_ uint32
	if tmp_, ok_ := callee.Memory().ReadUint32Le(ptr); !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: liftMemListU16: list ptr: bad memory read")
	} else {
		lptr_ = tmp_
	}
	var ln_ uint32
	if tmp_, ok_ := callee.Memory().ReadUint32Le(ptr + 4); !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: liftMemListU16: list len: bad memory read")
	} else {
		ln_ = tmp_
	}
	out_ := make([]uint16, ln_)
	n_ := uint64(ln_) * 2
	if n_ > math.MaxUint32 {
		return nil, fmt.Errorf("wacogo/witgen: liftMemListU16: list elem: bad memory read")
	}
	buf_, ok_ := callee.Memory().Read(lptr_, uint32(n_))
	if !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: liftMemListU16: list elem: bad memory read")
	}
	for i_ := range out_ {
		o_ := i_ * 2
		out_[i_] = binary.LittleEndian.Uint16(buf_[o_:])
	}
	return out_, nil
}

func lowerFlatListU16(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, stack []uint64, v []uint16) error {
	lstT_ := ty.(wacogo.TypeList)
	_ = lstT_
	ln_ := uint32(len(v))
	ptr_, err_ := callee.Realloc(ctx, 0, 0, 2, ln_*2)
	if err_ != nil {
		return fmt.Errorf("wacogo/witgen: lowerFlatListU16: realloc failed: %w", err_)
	}
	n_ := uint64(ln_) * 2
	if n_ > math.MaxUint32 {
		return fmt.Errorf("wacogo/witgen: lowerFlatListU16: list elem: bad memory write")
	}
	buf_, ok_ := callee.Memory().Read(ptr_, uint32(n_))
	if !ok_ {
		return fmt.Errorf("wacogo/witgen: lowerFlatListU16: list elem: bad memory write")
	}
	for i_, e_ := range v {
		o_ := i_ * 2
		binary.LittleEndian.PutUint16(buf_[o_:], e_)
	}
	stack[0] = uint64(ptr_)
	stack[1] = uint64(ln_)
	return nil
}

func lowerMemListU16(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, ptr uint32, v []uint16) error {
	lstT_ := ty.(wacogo.TypeList)
	_ = lstT_
	ln_ := uint32(len(v))
	lptr_, err_ := callee.Realloc(ctx, 0, 0, 2, ln_*2)
	if err_ != nil {
		return fmt.Errorf("wacogo/witgen: lowerMemListU16: realloc failed: %w", err_)
	}
	n_ := uint64(ln_) * 2
	if n_ > math.MaxUint32 {
		return fmt.Errorf("wacogo/witgen: lowerMemListU16: list elem: bad memory write")
	}
	buf_, ok_ := callee.Memory().Read(lptr_, uint32(n_))
	if !ok_ {
		return fmt.Errorf("wacogo/witgen: lowerMemListU16: list elem: bad memory write")
	}
	for i_, e_ := range v {
		o_ := i_ * 2
		binary.LittleEndian.PutUint16(buf_[o_:], e_)
	}
	if ok_ := callee.Memory().WriteUint32Le(ptr, lptr_); !ok_ {
		return fmt.Errorf("wacogo/witgen: lowerMemListU16: list ptr: bad memory write")
	}
	if ok_ := callee.Memory().WriteUint32Le(ptr+4, ln_); !ok_ {
		return fmt.Errorf("wacogo/witgen: lowerMemListU16: list len: bad memory write")
	}
	return nil
}

func toGoFlatListU32(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, stack []uint64) ([]uint32, error) {
	lstT_ := ty.(wacogo.TypeList)
	_ = lstT_
	ptr_ := uint32(stack[0])
	ln_ := uint32(stack[1])
	out_ := make([]uint32, ln_)
	n_ := uint64(ln_) * 4
	if n_ > math.MaxUint32 {
		return nil, fmt.Errorf("wacogo/witgen: toGoFlatListU32: elem: bad memory read")
	}
	buf_, ok_ := cc.Memory().Read(ptr_, uint32(n_))
	if !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: toGoFlatListU32: elem: bad memory read")
	}
	for i_ := range out_ {
		o_ := i_ * 4
		out_[i_] = binary.LittleEndian.Uint32(buf_[o_:])
	}
	return out_, nil
}

func toGoMemListU32(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, ptr uint32) ([]uint32, error) {
	lstT_ := ty.(wacogo.TypeList)
	_ = lstT_
	var lptr_ uint32
	if tmp_, ok_ := cc.Memory().ReadUint32Le(ptr); !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: toGoMemListU32: list ptr: bad memory read")
	} else {
		lptr_ = tmp_
	}
	var ln_ uint32
	if tmp_, ok_ := cc.Memory().ReadUint32Le(ptr + 4); !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: toGoMemListU32: list len: bad memory read")
	} else {
		ln_ = tmp_
	}
	out_ := make([]uint32, ln_)
	n_ := uint64(ln_) * 4
	if n_ > math.MaxUint32 {
		return nil, fmt.Errorf("wacogo/witgen: toGoMemListU32: list elem: bad memory read")
	}
	buf_, ok_ := cc.Memory().Read(lptr_, uint32(n_))
	if !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: toGoMemListU32: list elem: bad memory read")
	}
	for i_ := range out_ {
		o_ := i_ * 4
		out_[i_] = binary.LittleEndian.Uint32(buf_[o_:])
	}
	return out_, nil
}

func fromGoFlatListU32(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, stack []uint64, v []uint32) error {
	ln_ := uint32(len(v))
	ptr_, err_ := cc.Realloc(ctx, 0, 0, 4, ln_*4)
	if err_ != nil {
		return fmt.Errorf("wacogo/witgen: fromGoFlatListU32: realloc failed: %w", err_)
	}
	n_ := uint64(ln_) * 4
	if n_ > math.MaxUint32 {
		return fmt.Errorf("wacogo/witgen: fromGoFlatListU32: list elem: bad memory write")
	}
	buf_, ok_ := cc.Memory().Read(ptr_, uint32(n_))
	if !ok_ {
		return fmt.Errorf("wacogo/witgen: fromGoFlatListU32: list elem: bad memory write")
	}
	for i_, e_ := range v {
		o_ := i_ * 4
		binary.LittleEndian.PutUint32(buf_[o_:], e_)
	}
	stack[0] = uint64(ptr_)
	stack[1] = uint64(ln_)
	return nil
}

func fromGoMemListU32(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, ptr uint32, v []uint32) error {
	ln_ := uint32(len(v))
	lptr_, err_ := cc.Realloc(ctx, 0, 0, 4, ln_*4)
	if err_ != nil {
		return fmt.Errorf("wacogo/witgen: fromGoMemListU32: realloc failed: %w", err_)
	}
	n_ := uint64(ln_) * 4
	if n_ > math.MaxUint32 {
		return fmt.Errorf("wacogo/witgen: fromGoMemListU32: list elem: bad memory write")
	}
	buf_, ok_ := cc.Memory().Read(lptr_, uint32(n_))
	if !ok_ {
		return fmt.Errorf("wacogo/witgen: fromGoMemListU32: list elem: bad memory write")
	}
	for i_, e_ := range v {
		o_ := i_ * 4
		binary.LittleEndian.PutUint32(buf_[o_:], e_)
	}
	if ok_ := cc.Memory().WriteUint32Le(ptr, lptr_); !ok_ {
		return fmt.Errorf("wacogo/witgen: fromGoMemListU32: list ptr: bad memory write")
	}
	if ok_ := cc.Memory().WriteUint32Le(ptr+4, ln_); !ok_ {
		return fmt.Errorf("wacogo/witgen: fromGoMemListU32: list len: bad memory write")
	}
	return nil
}

func liftFlatListU32(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, stack []uint64) ([]uint32, error) {
	lstT_ := ty.(wacogo.TypeList)
	_ = lstT_
	ptr_ := uint32(stack[0])
	ln_ := uint32(stack[1])
	out_ := make([]uint32, ln_)
	n_ := uint64(ln_) * 4
	if n_ > math.MaxUint32 {
		return nil, fmt.Errorf("wacogo/witgen: liftFlatListU32: elem: bad memory read")
	}
	buf_, ok_ := callee.Memory().Read(ptr_, uint32(n_))
	if !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: liftFlatListU32: elem: bad memory read")
	}
	for i_ := range out_ {
		o_ := i_ * 4
		out_[i_] = binary.LittleEndian.Uint32(buf_[o_:])
	}
	return out_, nil
}

func liftMemListU32(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, ptr uint32) ([]uint32, error) {
	lstT_ := ty.(wacogo.TypeList)
	_ = lstT_
	var lptr_ uint32
	if tmp_, ok_ := callee.Memory().ReadUint32Le(ptr); !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: liftMemListU32: list ptr: bad memory read")
	} else {
		lptr_ = tmp_
	}
	var ln_ uint32
	if tmp_, ok_ := callee.Memory().ReadUint32Le(ptr + 4); !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: liftMemListU32: list len: bad memory read")
	} else {
		ln_ = tmp_
	}
	out_ := make([]uint32, ln_)
	n_ := uint64(ln_) * 4
	if n_ > math.MaxUint32 {
		return nil, fmt.Errorf("wacogo/witgen: liftMemListU32: list elem: bad memory read")
	}
	buf_, ok_ := callee.Memory().Read(lptr_, uint32(n_))
	if !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: liftMemListU32: list elem: bad memory read")
	}
	for i_ := range out_ {
		o_ := i_ * 4
		out_[i_] = binary.LittleEndian.Uint32(buf_[o_:])
	}
	return out_, nil
}

func lowerFlatListU32(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, stack []uint64, v []uint32) error {
	lstT_ := ty.(wacogo.TypeList)
	_ = lstT_
	ln_ := uint32(len(v))
	ptr_, err_ := callee.Realloc(ctx, 0, 0, 4, ln_*4)
	if err_ != nil {
		return fmt.Errorf("wacogo/witgen: lowerFlatListU32: realloc failed: %w", err_)
	}
	n_ := uint64(ln_) * 4
	if n_ > math.MaxUint32 {
		return fmt.Errorf("wacogo/witgen: lowerFlatListU32: list elem: bad memory write")
	}
	buf_, ok_ := callee.Memory().Read(ptr_, uint32(n_))
	if !ok_ {
		return fmt.Errorf("wacogo/witgen: lowerFlatListU32: list elem: bad memory write")
	}
	for i_, e_ := range v {
		o_ := i_ * 4
		binary.LittleEndian.PutUint32(buf_[o_:], e_)
	}
	stack[0] = uint64(ptr_)
	stack[1] = uint64(ln_)
	return nil
}

func lowerMemListU32(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, ptr uint32, v []uint32) error {
	lstT_ := ty.(wacogo.TypeList)
	_ = lstT_
	ln_ := uint32(len(v))
	lptr_, err_ := callee.Realloc(ctx, 0, 0, 4, ln_*4)
	if err_ != nil {
		return fmt.Errorf("wacogo/witgen: lowerMemListU32: realloc failed: %w", err_)
	}
	n_ := uint64(ln_) * 4
	if n_ > math.MaxUint32 {
		return fmt.Errorf("wacogo/witgen: lowerMemListU32: list elem: bad memory write")
	}
	buf_, ok_ := callee.Memory().Read(lptr_, uint32(n_))
	if !ok_ {
		return fmt.Errorf("wacogo/witgen: lowerMemListU32: list elem: bad memory write")
	}
	for i_, e_ := range v {
		o_ := i_ * 4
		binary.LittleEndian.PutUint32(buf_[o_:], e_)
	}
	if ok_ := callee.Memory().WriteUint32Le(ptr, lptr_); !ok_ {
		return fmt.Errorf("wacogo/witgen: lowerMemListU32: list ptr: bad memory write")
	}
	if ok_ := callee.Memory().WriteUint32Le(ptr+4, ln_); !ok_ {
		return fmt.Errorf("wacogo/witgen: lowerMemListU32: list len: bad memory write")
	}
	return nil
}

func toGoFlatListU64(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, stack []uint64) ([]uint64, error) {
	lstT_ := ty.(wacogo.TypeList)
	_ = lstT_
	ptr_ := uint32(stack[0])
	ln_ := uint32(stack[1])
	out_ := make([]uint64, ln_)
	n_ := uint64(ln_) * 8
	if n_ > math.MaxUint32 {
		return nil, fmt.Errorf("wacogo/witgen: toGoFlatListU64: elem: bad memory read")
	}
	buf_, ok_ := cc.Memory().Read(ptr_, uint32(n_))
	if !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: toGoFlatListU64: elem: bad memory read")
	}
	for i_ := range out_ {
		o_ := i_ * 8
		out_[i_] = binary.LittleEndian.Uint64(buf_[o_:])
	}
	return out_, nil
}

func toGoMemListU64(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, ptr uint32) ([]uint64, error) {
	lstT_ := ty.(wacogo.TypeList)
	_ = lstT_
	var lptr_ uint32
	if tmp_, ok_ := cc.Memory().ReadUint32Le(ptr); !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: toGoMemListU64: list ptr: bad memory read")
	} else {
		lptr_ = tmp_
	}
	var ln_ uint32
	if tmp_, ok_ := cc.Memory().ReadUint32Le(ptr + 4); !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: toGoMemListU64: list len: bad memory read")
	} else {
		ln_ = tmp_
	}
	out_ := make([]uint64, ln_)
	n_ := uint64(ln_) * 8
	if n_ > math.MaxUint32 {
		return nil, fmt.Errorf("wacogo/witgen: toGoMemListU64: list elem: bad memory read")
	}
	buf_, ok_ := cc.Memory().Read(lptr_, uint32(n_))
	if !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: toGoMemListU64: list elem: bad memory read")
	}
	for i_ := range out_ {
		o_ := i_ * 8
		out_[i_] = binary.LittleEndian.Uint64(buf_[o_:])
	}
	return out_, nil
}

func fromGoFlatListU64(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, stack []uint64, v []uint64) error {
	ln_ := uint32(len(v))
	ptr_, err_ := cc.Realloc(ctx, 0, 0, 8, ln_*8)
	if err_ != nil {
		return fmt.Errorf("wacogo/witgen: fromGoFlatListU64: realloc failed: %w", err_)
	}
	n_ := uint64(ln_) * 8
	if n_ > math.MaxUint32 {
		return fmt.Errorf("wacogo/witgen: fromGoFlatListU64: list elem: bad memory write")
	}
	buf_, ok_ := cc.Memory().Read(ptr_, uint32(n_))
	if !ok_ {
		return fmt.Errorf("wacogo/witgen: fromGoFlatListU64: list elem: bad memory write")
	}
	for i_, e_ := range v {
		o_ := i_ * 8
		binary.LittleEndian.PutUint64(buf_[o_:], e_)
	}
	stack[0] = uint64(ptr_)
	stack[1] = uint64(ln_)
	return nil
}

func fromGoMemListU64(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, ptr uint32, v []uint64) error {
	ln_ := uint32(len(v))
	lptr_, err_ := cc.Realloc(ctx, 0, 0, 8, ln_*8)
	if err_ != nil {
		return fmt.Errorf("wacogo/witgen: fromGoMemListU64: realloc failed: %w", err_)
	}
	n_ := uint64(ln_) * 8
	if n_ > math.MaxUint32 {
		return fmt.Errorf("wacogo/witgen: fromGoMemListU64: list elem: bad memory write")
	}
	buf_, ok_ := cc.Memory().Read(lptr_, uint32(n_))
	if !ok_ {
		return fmt.Errorf("wacogo/witgen: fromGoMemListU64: list elem: bad memory write")
	}
	for i_, e_ := range v {
		o_ := i_ * 8
		binary.LittleEndian.PutUint64(buf_[o_:], e_)
	}
	if ok_ := cc.Memory().WriteUint32Le(ptr, lptr_); !ok_ {
		return fmt.Errorf("wacogo/witgen: fromGoMemListU64: list ptr: bad memory write")
	}
	if ok_ := cc.Memory().WriteUint32Le(ptr+4, ln_); !ok_ {
		return fmt.Errorf("wacogo/witgen: fromGoMemListU64: list len: bad memory write")
	}
	return nil
}

func liftFlatListU64(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, stack []uint64) ([]uint64, error) {
	lstT_ := ty.(wacogo.TypeList)
	_ = lstT_
	ptr_ := uint32(stack[0])
	ln_ := uint32(stack[1])
	out_ := make([]uint64, ln_)
	n_ := uint64(ln_) * 8
	if n_ > math.MaxUint32 {
		return nil, fmt.Errorf("wacogo/witgen: liftFlatListU64: elem: bad memory read")
	}
	buf_, ok_ := callee.Memory().Read(ptr_, uint32(n_))
	if !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: liftFlatListU64: elem: bad memory read")
	}
	for i_ := range out_ {
		o_ := i_ * 8
		out_[i_] = binary.LittleEndian.Uint64(buf_[o_:])
	}
	return out_, nil
}

func liftMemListU64(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, ptr uint32) ([]uint64, error) {
	lstT_ := ty.(wacogo.TypeList)
	_ = lstT_
	var lptr_ uint32
	if tmp_, ok_ := callee.Memory().ReadUint32Le(ptr); !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: liftMemListU64: list ptr: bad memory read")
	} else {
		lptr_ = tmp_
	}
	var ln_ uint32
	if tmp_, ok_ := callee.Memory().ReadUint32Le(ptr + 4); !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: liftMemListU64: list len: bad memory read")
	} else {
		ln_ = tmp_
	}
	out_ := make([]uint64, ln_)
	n_ := uint64(ln_) * 8
	if n_ > math.MaxUint32 {
		return nil, fmt.Errorf("wacogo/witgen: liftMemListU64: list elem: bad memory read")
	}
	buf_, ok_ := callee.Memory().Read(lptr_, uint32(n_))
	if !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: liftMemListU64: list elem: bad memory read")
	}
	for i_ := range out_ {
		o_ := i_ * 8
		out_[i_] = binary.LittleEndian.Uint64(buf_[o_:])
	}
	return out_, nil
}

func lowerFlatListU64(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, stack []uint64, v []uint64) error {
	lstT_ := ty.(wacogo.TypeList)
	_ = lstT_
	ln_ := uint32(len(v))
	ptr_, err_ := callee.Realloc(ctx, 0, 0, 8, ln_*8)
	if err_ != nil {
		return fmt.Errorf("wacogo/witgen: lowerFlatListU64: realloc failed: %w", err_)
	}
	n_ := uint64(ln_) * 8
	if n_ > math.MaxUint32 {
		return fmt.Errorf("wacogo/witgen: lowerFlatListU64: list elem: bad memory write")
	}
	buf_, ok_ := callee.Memory().Read(ptr_, uint32(n_))
	if !ok_ {
		return fmt.Errorf("wacogo/witgen: lowerFlatListU64: list elem: bad memory write")
	}
	for i_, e_ := range v {
		o_ := i_ * 8
		binary.LittleEndian.PutUint64(buf_[o_:], e_)
	}
	stack[0] = uint64(ptr_)
	stack[1] = uint64(ln_)
	return nil
}

func lowerMemListU64(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, ptr uint32, v []uint64) error {
	lstT_ := ty.(wacogo.TypeList)
	_ = lstT_
	ln_ := uint32(len(v))
	lptr_, err_ := callee.Realloc(ctx, 0, 0, 8, ln_*8)
	if err_ != nil {
		return fmt.Errorf("wacogo/witgen: lowerMemListU64: realloc failed: %w", err_)
	}
	n_ := uint64(ln_) * 8
	if n_ > math.MaxUint32 {
		return fmt.Errorf("wacogo/witgen: lowerMemListU64: list elem: bad memory write")
	}
	buf_, ok_ := callee.Memory().Read(lptr_, uint32(n_))
	if !ok_ {
		return fmt.Errorf("wacogo/witgen: lowerMemListU64: list elem: bad memory write")
	}
	for i_, e_ := range v {
		o_ := i_ * 8
		binary.LittleEndian.PutUint64(buf_[o_:], e_)
	}
	if ok_ := callee.Memory().WriteUint32Le(ptr, lptr_); !ok_ {
		return fmt.Errorf("wacogo/witgen: lowerMemListU64: list ptr: bad memory write")
	}
	if ok_ := callee.Memory().WriteUint32Le(ptr+4, ln_); !ok_ {
		return fmt.Errorf("wacogo/witgen: lowerMemListU64: list len: bad memory write")
	}
	return nil
}

func toGoFlatListU8(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, stack []uint64) ([]uint8, error) {
	lstT_ := ty.(wacogo.TypeList)
	_ = lstT_
	ptr_ := uint32(stack[0])
	ln_ := uint32(stack[1])
	out_ := make([]uint8, ln_)
	n_ := uint64(ln_) * 1
	if n_ > math.MaxUint32 {
		return nil, fmt.Errorf("wacogo/witgen: toGoFlatListU8: elem: bad memory read")
	}
	buf_, ok_ := cc.Memory().Read(ptr_, uint32(n_))
	if !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: toGoFlatListU8: elem: bad memory read")
	}
	copy(out_, buf_)
	return out_, nil
}

func toGoMemListU8(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, ptr uint32) ([]uint8, error) {
	lstT_ := ty.(wacogo.TypeList)
	_ = lstT_
	var lptr_ uint32
	if tmp_, ok_ := cc.Memory().ReadUint32Le(ptr); !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: toGoMemListU8: list ptr: bad memory read")
	} else {
		lptr_ = tmp_
	}
	var ln_ uint32
	if tmp_, ok_ := cc.Memory().ReadUint32Le(ptr + 4); !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: toGoMemListU8: list len: bad memory read")
	} else {
		ln_ = tmp_
	}
	out_ := make([]uint8, ln_)
	n_ := uint64(ln_) * 1
	if n_ > math.MaxUint32 {
		return nil, fmt.Errorf("wacogo/witgen: toGoMemListU8: list elem: bad memory read")
	}
	buf_, ok_ := cc.Memory().Read(lptr_, uint32(n_))
	if !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: toGoMemListU8: list elem: bad memory read")
	}
	copy(out_, buf_)
	return out_, nil
}

func fromGoFlatListU8(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, stack []uint64, v []uint8) error {
	ln_ := uint32(len(v))
	ptr_, err_ := cc.Realloc(ctx, 0, 0, 1, ln_*1)
	if err_ != nil {
		return fmt.Errorf("wacogo/witgen: fromGoFlatListU8: realloc failed: %w", err_)
	}
	n_ := uint64(ln_) * 1
	if n_ > math.MaxUint32 {
		return fmt.Errorf("wacogo/witgen: fromGoFlatListU8: list elem: bad memory write")
	}
	buf_, ok_ := cc.Memory().Read(ptr_, uint32(n_))
	if !ok_ {
		return fmt.Errorf("wacogo/witgen: fromGoFlatListU8: list elem: bad memory write")
	}
	copy(buf_, v)
	stack[0] = uint64(ptr_)
	stack[1] = uint64(ln_)
	return nil
}

func fromGoMemListU8(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, ptr uint32, v []uint8) error {
	ln_ := uint32(len(v))
	lptr_, err_ := cc.Realloc(ctx, 0, 0, 1, ln_*1)
	if err_ != nil {
		return fmt.Errorf("wacogo/witgen: fromGoMemListU8: realloc failed: %w", err_)
	}
	n_ := uint64(ln_) * 1
	if n_ > math.MaxUint32 {
		return fmt.Errorf("wacogo/witgen: fromGoMemListU8: list elem: bad memory write")
	}
	buf_, ok_ := cc.Memory().Read(lptr_, uint32(n_))
	if !ok_ {
		return fmt.Errorf("wacogo/witgen: fromGoMemListU8: list elem: bad memory write")
	}
	copy(buf_, v)
	if ok_ := cc.Memory().WriteUint32Le(ptr, lptr_); !ok_ {
		return fmt.Errorf("wacogo/witgen: fromGoMemListU8: list ptr: bad memory write")
	}
	if ok_ := cc.Memory().WriteUint32Le(ptr+4, ln_); !ok_ {
		return fmt.Errorf("wacogo/witgen: fromGoMemListU8: list len: bad memory write")
	}
	return nil
}

func liftFlatListU8(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, stack []uint64) ([]uint8, error) {
	lstT_ := ty.(wacogo.TypeList)
	_ = lstT_
	ptr_ := uint32(stack[0])
	ln_ := uint32(stack[1])
	out_ := make([]uint8, ln_)
	n_ := uint64(ln_) * 1
	if n_ > math.MaxUint32 {
		return nil, fmt.Errorf("wacogo/witgen: liftFlatListU8: elem: bad memory read")
	}
	buf_, ok_ := callee.Memory().Read(ptr_, uint32(n_))
	if !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: liftFlatListU8: elem: bad memory read")
	}
	copy(out_, buf_)
	return out_, nil
}

func liftMemListU8(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, ptr uint32) ([]uint8, error) {
	lstT_ := ty.(wacogo.TypeList)
	_ = lstT_
	var lptr_ uint32
	if tmp_, ok_ := callee.Memory().ReadUint32Le(ptr); !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: liftMemListU8: list ptr: bad memory read")
	} else {
		lptr_ = tmp_
	}
	var ln_ uint32
	if tmp_, ok_ := callee.Memory().ReadUint32Le(ptr + 4); !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: liftMemListU8: list len: bad memory read")
	} else {
		ln_ = tmp_
	}
	out_ := make([]uint8, ln_)
	n_ := uint64(ln_) * 1
	if n_ > math.MaxUint32 {
		return nil, fmt.Errorf("wacogo/witgen: liftMemListU8: list elem: bad memory read")
	}
	buf_, ok_ := callee.Memory().Read(lptr_, uint32(n_))
	if !ok_ {
		return nil, fmt.Errorf("wacogo/witgen: liftMemListU8: list elem: bad memory read")
	}
	copy(out_, buf_)
	return out_, nil
}

func lowerFlatListU8(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, stack []uint64, v []uint8) error {
	lstT_ := ty.(wacogo.TypeList)
	_ = lstT_
	ln_ := uint32(len(v))
	ptr_, err_ := callee.Realloc(ctx, 0, 0, 1, ln_*1)
	if err_ != nil {
		return fmt.Errorf("wacogo/witgen: lowerFlatListU8: realloc failed: %w", err_)
	}
	n_ := uint64(ln_) * 1
	if n_ > math.MaxUint32 {
		return fmt.Errorf("wacogo/witgen: lowerFlatListU8: list elem: bad memory write")
	}
	buf_, ok_ := callee.Memory().Read(ptr_, uint32(n_))
	if !ok_ {
		return fmt.Errorf("wacogo/witgen: lowerFlatListU8: list elem: bad memory write")
	}
	copy(buf_, v)
	stack[0] = uint64(ptr_)
	stack[1] = uint64(ln_)
	return nil
}

func lowerMemListU8(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, ptr uint32, v []uint8) error {
	lstT_ := ty.(wacogo.TypeList)
	_ = lstT_
	ln_ := uint32(len(v))
	lptr_, err_ := callee.Realloc(ctx, 0, 0, 1, ln_*1)
	if err_ != nil {
		return fmt.Errorf("wacogo/witgen: lowerMemListU8: realloc failed: %w", err_)
	}
	n_ := uint64(ln_) * 1
	if n_ > math.MaxUint32 {
		return fmt.Errorf("wacogo/witgen: lowerMemListU8: list elem: bad memory write")
	}
	buf_, ok_ := callee.Memory().Read(lptr_, uint32(n_))
	if !ok_ {
		return fmt.Errorf("wacogo/witgen: lowerMemListU8: list elem: bad memory write")
	}
	copy(buf_, v)
	if ok_ := callee.Memory().WriteUint32Le(ptr, lptr_); !ok_ {
		return fmt.Errorf("wacogo/witgen: lowerMemListU8: list ptr: bad memory write")
	}
	if ok_ := callee.Memory().WriteUint32Le(ptr+4, ln_); !ok_ {
		return fmt.Errorf("wacogo/witgen: lowerMemListU8: list len: bad memory write")
	}
	return nil
}

func wrapRevBool(f *Factory) host.Func {
	return func(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, stack []uint64) error {
		state_ := h.UserState().(*instanceState)
		fnType_ := cc.Instance().ExportedFunc("rev-bool").Type()
		_ = fnType_
		var xs []bool
		{
			v_, err_ := toGoFlatListBool(ctx, cc, h, fnType_.Params[0].Type, stack[0:2])
			if err_ != nil {
				return err_
			}
			xs = v_
		}
		result_, implErr_ := state_.impl.RevBool(ctx, xs)
		if implErr_ != nil {
			return fmt.Errorf("wacogo/witgen: rev-bool: impl returned error: %w", implErr_)
		}
		outPtr_, rerr_ := cc.Realloc(ctx, 0, 0, 4, 8)
		if rerr_ != nil {
			return fmt.Errorf("wacogo/witgen: rev-bool: realloc failed: %w", rerr_)
		}
		if err_ := fromGoMemListBool(ctx, cc, h, outPtr_, result_); err_ != nil {
			return err_
		}
		stack[0] = uint64(outPtr_)
		return nil
	}
}

func wrapRevChar(f *Factory) host.Func {
	return func(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, stack []uint64) error {
		state_ := h.UserState().(*instanceState)
		fnType_ := cc.Instance().ExportedFunc("rev-char").Type()
		_ = fnType_
		var xs []rune
		{
			v_, err_ := toGoFlatListChar(ctx, cc, h, fnType_.Params[0].Type, stack[0:2])
			if err_ != nil {
				return err_
			}
			xs = v_
		}
		result_, implErr_ := state_.impl.RevChar(ctx, xs)
		if implErr_ != nil {
			return fmt.Errorf("wacogo/witgen: rev-char: impl returned error: %w", implErr_)
		}
		outPtr_, rerr_ := cc.Realloc(ctx, 0, 0, 4, 8)
		if rerr_ != nil {
			return fmt.Errorf("wacogo/witgen: rev-char: realloc failed: %w", rerr_)
		}
		if err_ := fromGoMemListChar(ctx, cc, h, outPtr_, result_); err_ != nil {
			return err_
		}
		stack[0] = uint64(outPtr_)
		return nil
	}
}

func wrapRevF32(f *Factory) host.Func {
	return func(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, stack []uint64) error {
		state_ := h.UserState().(*instanceState)
		fnType_ := cc.Instance().ExportedFunc("rev-f32").Type()
		_ = fnType_
		var xs []float32
		{
			v_, err_ := toGoFlatListF32(ctx, cc, h, fnType_.Params[0].Type, stack[0:2])
			if err_ != nil {
				return err_
			}
			xs = v_
		}
		result_, implErr_ := state_.impl.RevF32(ctx, xs)
		if implErr_ != nil {
			return fmt.Errorf("wacogo/witgen: rev-f32: impl returned error: %w", implErr_)
		}
		outPtr_, rerr_ := cc.Realloc(ctx, 0, 0, 4, 8)
		if rerr_ != nil {
			return fmt.Errorf("wacogo/witgen: rev-f32: realloc failed: %w", rerr_)
		}
		if err_ := fromGoMemListF32(ctx, cc, h, outPtr_, result_); err_ != nil {
			return err_
		}
		stack[0] = uint64(outPtr_)
		return nil
	}
}

func wrapRevF64(f *Factory) host.Func {
	return func(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, stack []uint64) error {
		state_ := h.UserState().(*instanceState)
		fnType_ := cc.Instance().ExportedFunc("rev-f64").Type()
		_ = fnType_
		var xs []float64
		{
			v_, err_ := toGoFlatListF64(ctx, cc, h, fnType_.Params[0].Type, stack[0:2])
			if err_ != nil {
				return err_
			}
			xs = v_
		}
		result_, implErr_ := state_.impl.RevF64(ctx, xs)
		if implErr_ != nil {
			return fmt.Errorf("wacogo/witgen: rev-f64: impl returned error: %w", implErr_)
		}
		outPtr_, rerr_ := cc.Realloc(ctx, 0, 0, 4, 8)
		if rerr_ != nil {
			return fmt.Errorf("wacogo/witgen: rev-f64: realloc failed: %w", rerr_)
		}
		if err_ := fromGoMemListF64(ctx, cc, h, outPtr_, result_); err_ != nil {
			return err_
		}
		stack[0] = uint64(outPtr_)
		return nil
	}
}

func wrapRevS16(f *Factory) host.Func {
	return func(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, stack []uint64) error {
		state_ := h.UserState().(*instanceState)
		fnType_ := cc.Instance().ExportedFunc("rev-s16").Type()
		_ = fnType_
		var xs []int16
		{
			v_, err_ := toGoFlatListS16(ctx, cc, h, fnType_.Params[0].Type, stack[0:2])
			if err_ != nil {
				return err_
			}
			xs = v_
		}
		result_, implErr_ := state_.impl.RevS16(ctx, xs)
		if implErr_ != nil {
			return fmt.Errorf("wacogo/witgen: rev-s16: impl returned error: %w", implErr_)
		}
		outPtr_, rerr_ := cc.Realloc(ctx, 0, 0, 4, 8)
		if rerr_ != nil {
			return fmt.Errorf("wacogo/witgen: rev-s16: realloc failed: %w", rerr_)
		}
		if err_ := fromGoMemListS16(ctx, cc, h, outPtr_, result_); err_ != nil {
			return err_
		}
		stack[0] = uint64(outPtr_)
		return nil
	}
}

func wrapRevS32(f *Factory) host.Func {
	return func(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, stack []uint64) error {
		state_ := h.UserState().(*instanceState)
		fnType_ := cc.Instance().ExportedFunc("rev-s32").Type()
		_ = fnType_
		var xs []int32
		{
			v_, err_ := toGoFlatListS32(ctx, cc, h, fnType_.Params[0].Type, stack[0:2])
			if err_ != nil {
				return err_
			}
			xs = v_
		}
		result_, implErr_ := state_.impl.RevS32(ctx, xs)
		if implErr_ != nil {
			return fmt.Errorf("wacogo/witgen: rev-s32: impl returned error: %w", implErr_)
		}
		outPtr_, rerr_ := cc.Realloc(ctx, 0, 0, 4, 8)
		if rerr_ != nil {
			return fmt.Errorf("wacogo/witgen: rev-s32: realloc failed: %w", rerr_)
		}
		if err_ := fromGoMemListS32(ctx, cc, h, outPtr_, result_); err_ != nil {
			return err_
		}
		stack[0] = uint64(outPtr_)
		return nil
	}
}

func wrapRevS64(f *Factory) host.Func {
	return func(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, stack []uint64) error {
		state_ := h.UserState().(*instanceState)
		fnType_ := cc.Instance().ExportedFunc("rev-s64").Type()
		_ = fnType_
		var xs []int64
		{
			v_, err_ := toGoFlatListS64(ctx, cc, h, fnType_.Params[0].Type, stack[0:2])
			if err_ != nil {
				return err_
			}
			xs = v_
		}
		result_, implErr_ := state_.impl.RevS64(ctx, xs)
		if implErr_ != nil {
			return fmt.Errorf("wacogo/witgen: rev-s64: impl returned error: %w", implErr_)
		}
		outPtr_, rerr_ := cc.Realloc(ctx, 0, 0, 4, 8)
		if rerr_ != nil {
			return fmt.Errorf("wacogo/witgen: rev-s64: realloc failed: %w", rerr_)
		}
		if err_ := fromGoMemListS64(ctx, cc, h, outPtr_, result_); err_ != nil {
			return err_
		}
		stack[0] = uint64(outPtr_)
		return nil
	}
}

func wrapRevS8(f *Factory) host.Func {
	return func(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, stack []uint64) error {
		state_ := h.UserState().(*instanceState)
		fnType_ := cc.Instance().ExportedFunc("rev-s8").Type()
		_ = fnType_
		var xs []int8
		{
			v_, err_ := toGoFlatListS8(ctx, cc, h, fnType_.Params[0].Type, stack[0:2])
			if err_ != nil {
				return err_
			}
			xs = v_
		}
		result_, implErr_ := state_.impl.RevS8(ctx, xs)
		if implErr_ != nil {
			return fmt.Errorf("wacogo/witgen: rev-s8: impl returned error: %w", implErr_)
		}
		outPtr_, rerr_ := cc.Realloc(ctx, 0, 0, 4, 8)
		if rerr_ != nil {
			return fmt.Errorf("wacogo/witgen: rev-s8: realloc failed: %w", rerr_)
		}
		if err_ := fromGoMemListS8(ctx, cc, h, outPtr_, result_); err_ != nil {
			return err_
		}
		stack[0] = uint64(outPtr_)
		return nil
	}
}

func wrapRevU16(f *Factory) host.Func {
	return func(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, stack []uint64) error {
		state_ := h.UserState().(*instanceState)
		fnType_ := cc.Instance().ExportedFunc("rev-u16").Type()
		_ = fnType_
		var xs []uint16
		{
			v_, err_ := toGoFlatListU16(ctx, cc, h, fnType_.Params[0].Type, stack[0:2])
			if err_ != nil {
				return err_
			}
			xs = v_
		}
		result_, implErr_ := state_.impl.RevU16(ctx, xs)
		if implErr_ != nil {
			return fmt.Errorf("wacogo/witgen: rev-u16: impl returned error: %w", implErr_)
		}
		outPtr_, rerr_ := cc.Realloc(ctx, 0, 0, 4, 8)
		if rerr_ != nil {
			return fmt.Errorf("wacogo/witgen: rev-u16: realloc failed: %w", rerr_)
		}
		if err_ := fromGoMemListU16(ctx, cc, h, outPtr_, result_); err_ != nil {
			return err_
		}
		stack[0] = uint64(outPtr_)
		return nil
	}
}

func wrapRevU32(f *Factory) host.Func {
	return func(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, stack []uint64) error {
		state_ := h.UserState().(*instanceState)
		fnType_ := cc.Instance().ExportedFunc("rev-u32").Type()
		_ = fnType_
		var xs []uint32
		{
			v_, err_ := toGoFlatListU32(ctx, cc, h, fnType_.Params[0].Type, stack[0:2])
			if err_ != nil {
				return err_
			}
			xs = v_
		}
		result_, implErr_ := state_.impl.RevU32(ctx, xs)
		if implErr_ != nil {
			return fmt.Errorf("wacogo/witgen: rev-u32: impl returned error: %w", implErr_)
		}
		outPtr_, rerr_ := cc.Realloc(ctx, 0, 0, 4, 8)
		if rerr_ != nil {
			return fmt.Errorf("wacogo/witgen: rev-u32: realloc failed: %w", rerr_)
		}
		if err_ := fromGoMemListU32(ctx, cc, h, outPtr_, result_); err_ != nil {
			return err_
		}
		stack[0] = uint64(outPtr_)
		return nil
	}
}

func wrapRevU64(f *Factory) host.Func {
	return func(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, stack []uint64) error {
		state_ := h.UserState().(*instanceState)
		fnType_ := cc.Instance().ExportedFunc("rev-u64").Type()
		_ = fnType_
		var xs []uint64
		{
			v_, err_ := toGoFlatListU64(ctx, cc, h, fnType_.Params[0].Type, stack[0:2])
			if err_ != nil {
				return err_
			}
			xs = v_
		}
		result_, implErr_ := state_.impl.RevU64(ctx, xs)
		if implErr_ != nil {
			return fmt.Errorf("wacogo/witgen: rev-u64: impl returned error: %w", implErr_)
		}
		outPtr_, rerr_ := cc.Realloc(ctx, 0, 0, 4, 8)
		if rerr_ != nil {
			return fmt.Errorf("wacogo/witgen: rev-u64: realloc failed: %w", rerr_)
		}
		if err_ := fromGoMemListU64(ctx, cc, h, outPtr_, result_); err_ != nil {
			return err_
		}
		stack[0] = uint64(outPtr_)
		return nil
	}
}

func wrapRevU8(f *Factory) host.Func {
	return func(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, stack []uint64) error {
		state_ := h.UserState().(*instanceState)
		fnType_ := cc.Instance().ExportedFunc("rev-u8").Type()
		_ = fnType_
		var xs []uint8
		{
			v_, err_ := toGoFlatListU8(ctx, cc, h, fnType_.Params[0].Type, stack[0:2])
			if err_ != nil {
				return err_
			}
			xs = v_
		}
		result_, implErr_ := state_.impl.RevU8(ctx, xs)
		if implErr_ != nil {
			return fmt.Errorf("wacogo/witgen: rev-u8: impl returned error: %w", implErr_)
		}
		outPtr_, rerr_ := cc.Realloc(ctx, 0, 0, 4, 8)
		if rerr_ != nil {
			return fmt.Errorf("wacogo/witgen: rev-u8: realloc failed: %w", rerr_)
		}
		if err_ := fromGoMemListU8(ctx, cc, h, outPtr_, result_); err_ != nil {
			return err_
		}
		stack[0] = uint64(outPtr_)
		return nil
	}
}
