// Code generated by wacogo-witgen from primlists.wit. DO NOT EDIT.

// One function per primitive element type, for the bulk list copy:
// each takes a list and returns it reversed.
package primlists

import (
	"context"
)

// InterfaceName is the canonical WIT id of the interface this binding
// was generated from.
const InterfaceName = "example:demo/primlists"

// One function per primitive element type, for the bulk list copy:
// each takes a list and returns it reversed.
type Primlists interface {
	RevBool(ctx context.Context, xs []bool) ([]bool, error)
	RevChar(ctx context.Context, xs []rune) ([]rune, error)
	RevF32(ctx context.Context, xs []float32) ([]float32, error)
	RevF64(ctx context.Context, xs []float64) ([]float64, error)
	RevS16(ctx context.Context, xs []int16) ([]int16, error)
	RevS32(ctx context.Context, xs []int32) ([]int32, error)
	RevS64(ctx context.Context, xs []int64) ([]int64, error)
	RevS8(ctx context.Context, xs []int8) ([]int8, error)
	RevU16(ctx context.Context, xs []uint16) ([]uint16, error)
	RevU32(ctx context.Context, xs []uint32) ([]uint32, error)
	RevU64(ctx context.Context, xs []uint64) ([]uint64, error)
	RevU8(ctx context.Context, xs []uint8) ([]uint8, error)
}
