// Code generated by wacogo-witgen from greet.wit. DO NOT EDIT.

// Package echo provides Go bindings for the example:demo/echo interface.
package echo

import (
	"context"
	"fmt"

	"github.com/partite-ai/wacogo"
	"github.com/partite-ai/wacogo/host"
)

// echoWrapper is the concrete type returned by WrapInstance
// as a Echo. Held internally; users hold it via the Echo
// interface.
type echoWrapper struct {
	callerInst *host.ComponentInstance
	fnGreet    *host.ExportedFunc
}

// WrapInstance returns a Echo that forwards method calls to
// callee. caller is a Factory-built host instance whose state hosts any
// handles minted by callee during those calls.
func WrapInstance(caller *host.ComponentInstance, callee *wacogo.ComponentInstance) Echo {
	w_ := &echoWrapper{callerInst: caller}
	w_.fnGreet = host.WrapExportedFunc(callee.ExportedFunc("greet"))
	return w_
}
func (w *echoWrapper) Greet(ctx context.Context, name string) (string, error) {
	var resVal_ string
	var resErr_ error
	arg0_ := name
	{
		callErr_ := w.fnGreet.CallRaw(ctx, w.callerInst,
			func(caller, callee *host.CallContext, stack []uint64) {
				if err_ := lowerFlatString(ctx, caller, callee, w.callerInst, w.fnGreet.ParamType(0), stack[0:2], arg0_); err_ != nil {
					resErr_ = err_
					return
				}
			},
			func(caller, callee *host.CallContext, stack []uint64) {
				if v_, err_ := liftMemString(ctx, caller, callee, w.callerInst, w.fnGreet.ResultType(0), uint32(stack[0])); err_ != nil {
					resErr_ = err_
					return
				} else {
					resVal_ = v_
				}
			},
		)
		if callErr_ != nil {
			return "", fmt.Errorf("wacogo/witgen: CallRaw failed: %w", callErr_)
		}
		if resErr_ != nil {
			return "", resErr_
		}
	}
	return resVal_, nil
}
