// Code generated by wacogo-witgen from greet.wit. DO NOT EDIT.

// Package echo provides Go bindings for the example:demo/echo interface.
package echo

import (
	"context"
)

// InterfaceName is the canonical WIT id of the interface this binding
// was generated from.
const InterfaceName = "example:demo/echo"

// Echo is the Go binding for the example:demo/echo interface.
// Implement it to provide a host-side component, or pass an exported wasm
// instance to WrapInstance to obtain a Echo that calls into wasm.
// Resource-typed parameters and results appear as *<R>Handle values that can
// be passed across component boundaries.
type Echo interface {
	Greet(ctx context.Context, name string) (string, error)
}
