// Code generated by wacogo-witgen from greet.wit. DO NOT EDIT.

// Package echo provides Go bindings for the example:demo/echo interface.
package echo

import (
	"context"
	"fmt"

	"github.com/partite-ai/wacogo"
	"github.com/partite-ai/wacogo/host"
)

// Factory builds host-side instances of the Echo interface
// from a Go implementation.
type Factory struct {
	engine *wacogo.Engine
	comp   *host.Component
}

type instanceState struct {
	impl Echo
}

// Deps groups the cross-component dependencies required to instantiate
// Echo. Pass a populated value via NewInstance.
type Deps struct {
}

// NewFactory creates a Factory bound to e. A single Factory may be
// reused to build multiple instances backed by different implementations.
func NewFactory(ctx context.Context, e *wacogo.Engine) (*Factory, error) {
	f_ := &Factory{engine: e}
	b_ := e.NewHostBuilder("example_demo_echo")

	b_.AddFunction("greet", &host.FuncType{
		Params:  []host.Param{{Name: "name", Type: host.String}},
		Results: []host.ResultDecl{{Name: "", Type: host.String}},
	}, wrapGreet(f_))

	comp_, err_ := b_.Build(ctx)
	if err_ != nil {
		return nil, err_
	}
	f_.comp = comp_
	return f_, nil
}

// NewInstance creates a fresh component instance backed by impl. Pass
// inst.Core() to wacogo.WithInstanceImport to wire the instance into a
// composite world. deps may be nil only when Echo has no
// imports.
func (f *Factory) NewInstance(ctx context.Context, impl Echo, deps *Deps, opts ...host.InstantiateOption) (*host.ComponentInstance, error) {
	_ = deps
	state_ := &instanceState{impl: impl}
	opts = append(opts, host.WithUserState(state_))
	inst_, err_ := f.comp.Instantiate(ctx, opts...)
	if err_ != nil {
		return nil, err_
	}
	return inst_, nil
}

// Close releases resources shared by the Factory. Existing instances
// remain callable until each is closed individually.
func (f *Factory) Close(ctx context.Context) error { return f.comp.Close(ctx) }

func toGoFlatString(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, stack []uint64) (string, error) {
	_ = ty
	ptr_ := uint32(stack[0])
	ln_ := uint32(stack[1])
	bs_, ok_ := cc.Memory().Read(ptr_, ln_)
	if !ok_ {
		return "", fmt.Errorf("wacogo/witgen: toGoFlatString: bad memory read")
	}
	return string(bs_), nil
}

func toGoMemString(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, ptr uint32) (string, error) {
	_ = ty
	var sptr_ uint32
	if tmp_, ok_ := cc.Memory().ReadUint32Le(ptr); !ok_ {
		return "", fmt.Errorf("wacogo/witgen: toGoMemString: string ptr: bad memory read")
	} else {
		sptr_ = tmp_
	}
	var ln_ uint32
	if tmp_, ok_ := cc.Memory().ReadUint32Le(ptr + 4); !ok_ {
		return "", fmt.Errorf("wacogo/witgen: toGoMemString: string len: bad memory read")
	} else {
		ln_ = tmp_
	}
	bs_, ok_ := cc.Memory().Read(sptr_, ln_)
	if !ok_ {
		return "", fmt.Errorf("wacogo/witgen: toGoMemString: bad memory read")
	}
	return string(bs_), nil
}

func fromGoFlatString(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, stack []uint64, v string) error {
	bs_ := []byte(v)
	ptr_, err_ := cc.Realloc(ctx, 0, 0, 1, uint32(len(bs_)))
	if err_ != nil {
		return fmt.Errorf("wacogo/witgen: fromGoFlatString: realloc failed: %w", err_)
	}
	if ok_ := cc.Memory().Write(ptr_, bs_); !ok_ {
		return fmt.Errorf("wacogo/witgen: fromGoFlatString: bad memory write")
	}
	stack[0] = uint64(ptr_)
	stack[1] = uint64(len(bs_))
	return nil
}

func fromGoMemString(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, ptr uint32, v string) error {
	bs_ := []byte(v)
	sptr_, err_ := cc.Realloc(ctx, 0, 0, 1, uint32(len(bs_)))
	if err_ != nil {
		return fmt.Errorf("wacogo/witgen: fromGoMemString: realloc failed: %w", err_)
	}
	if ok_ := cc.Memory().Write(sptr_, bs_); !ok_ {
		return fmt.Errorf("wacogo/witgen: fromGoMemString: bad memory write")
	}
	if ok_ := cc.Memory().WriteUint32Le(ptr, sptr_); !ok_ {
		return fmt.Errorf("wacogo/witgen: fromGoMemString: string ptr: bad memory write")
	}
	if ok_ := cc.Memory().WriteUint32Le(ptr+4, uint32(len(bs_))); !ok_ {
		return fmt.Errorf("wacogo/witgen: fromGoMemString: string len: bad memory write")
	}
	return nil
}

func liftFlatString(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, stack []uint64) (string, error) {
	ptr_ := uint32(stack[0])
	ln_ := uint32(stack[1])
	bs_, ok_ := callee.Memory().Read(ptr_, ln_)
	if !ok_ {
		return "", fmt.Errorf("wacogo/witgen: liftFlatString: bad memory read")
	}
	return string(bs_), nil
}

func liftMemString(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, ptr uint32) (string, error) {
	var sptr_ uint32
	if tmp_, ok_ := callee.Memory().ReadUint32Le(ptr); !ok_ {
		return "", fmt.Errorf("wacogo/witgen: liftMemString: string ptr: bad memory read")
	} else {
		sptr_ = tmp_
	}
	var ln_ uint32
	if tmp_, ok_ := callee.Memory().ReadUint32Le(ptr + 4); !ok_ {
		return "", fmt.Errorf("wacogo/witgen: liftMemString: string len: bad memory read")
	} else {
		ln_ = tmp_
	}
	bs_, ok_ := callee.Memory().Read(sptr_, ln_)
	if !ok_ {
		return "", fmt.Errorf("wacogo/witgen: liftMemString: bad memory read")
	}
	return string(bs_), nil
}

func lowerFlatString(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, stack []uint64, v string) error {
	bs_ := []byte(v)
	ptr_, err_ := callee.Realloc(ctx, 0, 0, 1, uint32(len(bs_)))
	if err_ != nil {
		return fmt.Errorf("wacogo/witgen: lowerFlatString: realloc failed: %w", err_)
	}
	if ok_ := callee.Memory().Write(ptr_, bs_); !ok_ {
		return fmt.Errorf("wacogo/witgen: lowerFlatString: bad memory write")
	}
	stack[0] = uint64(ptr_)
	stack[1] = uint64(len(bs_))
	return nil
}

func lowerMemString(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, ptr uint32, v string) error {
	bs_ := []byte(v)
	sptr_, err_ := callee.Realloc(ctx, 0, 0, 1, uint32(len(bs_)))
	if err_ != nil {
		return fmt.Errorf("wacogo/witgen: lowerMemString: realloc failed: %w", err_)
	}
	if ok_ := callee.Memory().Write(sptr_, bs_); !ok_ {
		return fmt.Errorf("wacogo/witgen: lowerMemString: bad memory write")
	}
	if ok_ := callee.Memory().WriteUint32Le(ptr, sptr_); !ok_ {
		return fmt.Errorf("wacogo/witgen: lowerMemString: string ptr: bad memory write")
	}
	if ok_ := callee.Memory().WriteUint32Le(ptr+4, uint32(len(bs_))); !ok_ {
		return fmt.Errorf("wacogo/witgen: lowerMemString: string len: bad memory write")
	}
	return nil
}

func wrapGreet(f *Factory) host.Func {
	return func(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, stack []uint64) error {
		state_ := h.UserState().(*instanceState)
		fnType_ := cc.Instance().ExportedFunc("greet").Type()
		_ = fnType_
		var name string
		{
			v_, err_ := toGoFlatString(ctx, cc, h, fnType_.Params[0].Type, stack[0:2])
			if err_ != nil {
				return err_
			}
			name = v_
		}
		result_, implErr_ := state_.impl.Greet(ctx, name)
		if implErr_ != nil {
			return fmt.Errorf("wacogo/witgen: greet: impl returned error: %w", implErr_)
		}
		outPtr_, rerr_ := cc.Realloc(ctx, 0, 0, 4, 8)
		if rerr_ != nil {
			return fmt.Errorf("wacogo/witgen: greet: realloc failed: %w", rerr_)
		}
		if err_ := fromGoMemString(ctx, cc, h, outPtr_, result_); err_ != nil {
			return err_
		}
		stack[0] = uint64(outPtr_)
		return nil
	}
}
