// Code generated by wacogo-witgen from cross_resource.wit. DO NOT EDIT.

// Package filesystem provides Go bindings for the example:demo/filesystem interface.
package filesystem

import (
	"context"

	streams "github.com/partite-ai/wacogo/internal/witgen/testdata/genfixtures/example/demo/streams"
)

// InterfaceName is the canonical WIT id of the interface this binding
// was generated from.
const InterfaceName = "example:demo/filesystem"

// Filesystem is the Go binding for the example:demo/filesystem interface.
// Implement it to provide a host-side component, or pass an exported wasm
// instance to WrapInstance to obtain a Filesystem that calls into wasm.
// Resource-typed parameters and results appear as *<R>Handle values that can
// be passed across component boundaries.
type Filesystem interface {
	Open(ctx context.Context) (*streams.HandleHandle, error)
}
