// Code generated by wacogo-witgen from cross_resource.wit. DO NOT EDIT.

// Package filesystem provides Go bindings for the example:demo/filesystem interface.
package filesystem

import (
	"context"
	"fmt"

	"github.com/partite-ai/wacogo"
	"github.com/partite-ai/wacogo/host"
	streams "github.com/partite-ai/wacogo/internal/witgen/testdata/genfixtures/example/demo/streams"
)

// Factory builds host-side instances of the Filesystem interface
// from a Go implementation.
type Factory struct {
	engine    *wacogo.Engine
	comp      *host.Component
	handleRef *host.ResourceTypeRef
}

type instanceState struct {
	impl                Filesystem
	streams             *wacogo.ComponentInstance
	streamsHandleFwdFns *streamsHandleFwdFns
}

// Deps groups the cross-component dependencies required to instantiate
// Filesystem. Pass a populated value via NewInstance.
type Deps struct {
	Streams *wacogo.ComponentInstance
}

// NewFactory creates a Factory bound to e. A single Factory may be
// reused to build multiple instances backed by different implementations.
func NewFactory(ctx context.Context, e *wacogo.Engine) (*Factory, error) {
	f_ := &Factory{engine: e}
	b_ := e.NewHostBuilder("example_demo_filesystem")

	f_.handleRef = b_.AddResourceRef("handle")

	b_.AddFunction("open", &host.FuncType{
		Params:  []host.Param{},
		Results: []host.ResultDecl{{Name: "", Type: f_.handleRef.Own()}},
	}, wrapOpen(f_))

	comp_, err_ := b_.Build(ctx)
	if err_ != nil {
		return nil, err_
	}
	f_.comp = comp_
	return f_, nil
}

// NewInstance creates a fresh component instance backed by impl. Pass
// inst.Core() to wacogo.WithInstanceImport to wire the instance into a
// composite world. deps may be nil only when Filesystem has no
// imports.
func (f *Factory) NewInstance(ctx context.Context, impl Filesystem, deps *Deps, opts ...host.InstantiateOption) (*host.ComponentInstance, error) {
	if deps == nil {
		panic("filesystem.NewInstance: deps is nil")
	}
	var missing_ []string
	if deps.Streams == nil {
		missing_ = append(missing_, "Streams")
	}
	if len(missing_) > 0 {
		panic(fmt.Sprintf("filesystem.NewInstance: deps missing fields: %v", missing_))
	}
	opts = append(opts, host.WithResourceFrom(f.handleRef, deps.Streams, "handle"))
	state_ := &instanceState{impl: impl, streams: deps.Streams}
	state_.streamsHandleFwdFns = &streamsHandleFwdFns{
		fnRead: host.WrapExportedFunc(deps.Streams.ExportedFunc("[method]handle.read")),
	}

	opts = append(opts, host.WithUserState(state_))
	inst_, err_ := f.comp.Instantiate(ctx, opts...)
	if err_ != nil {
		return nil, err_
	}
	return inst_, nil
}

// Close releases resources shared by the Factory. Existing instances
// remain callable until each is closed individually.
func (f *Factory) Close(ctx context.Context) error { return f.comp.Close(ctx) }

func wrapOpen(f *Factory) host.Func {
	return func(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, stack []uint64) error {
		state_ := h.UserState().(*instanceState)
		fnType_ := cc.Instance().ExportedFunc("open").Type()
		_ = fnType_
		result_, implErr_ := state_.impl.Open(ctx)
		if implErr_ != nil {
			return fmt.Errorf("wacogo/witgen: open: impl returned error: %w", implErr_)
		}
		{
			oh_, err_ := streams.HandleValueFor(cc, h, result_)
			if err_ != nil {
				return fmt.Errorf("wacogo/witgen: own-result bind failed: %w", err_)
			}
			result_.Invalidate()
			stack[0] = uint64(oh_)
		}
		return nil
	}
}

// streamsHandleFwdFns holds precomputed *host.ExportedFunc per method of streams.Handle,
// resolved against the lender instance at NewInstance time. Shared by
// every streamsHandleForwarder constructed under this importer instance.
type streamsHandleFwdFns struct {
	fnRead *host.ExportedFunc
}

// streamsHandleForwarder satisfies streams.Handle by forwarding each method to the lender
// instance via the precomputed fns table.
type streamsHandleForwarder struct {
	caller *host.ComponentInstance
	rh     wacogo.ResourceHandle
	fns    *streamsHandleFwdFns
}

func (f *streamsHandleForwarder) Read(ctx context.Context) (uint32, error) {
	var resVal_ uint32
	{
		callErr_ := f.fns.fnRead.CallRaw(ctx, f.caller,
			func(caller, callee *host.CallContext, stack []uint64) {
				stack[0] = uint64(f.rh.HandleID())
			},
			func(caller, callee *host.CallContext, stack []uint64) {
				resVal_ = uint32(stack[0])
			},
		)
		if callErr_ != nil {
			return 0, fmt.Errorf("wacogo/witgen: CallRaw failed: %w", callErr_)
		}
	}
	return resVal_, nil
}
