// Code generated by wacogo-witgen from acl.wit. DO NOT EDIT.

// Package acl provides Go bindings for the example:demo/acl interface.
package acl

import (
	"context"
	"fmt"

	"github.com/partite-ai/wacogo"
	"github.com/partite-ai/wacogo/host"
)

// Factory builds host-side instances of the Acl interface
// from a Go implementation.
type Factory struct {
	engine *wacogo.Engine
	comp   *host.Component
}

type instanceState struct {
	impl Acl
}

// Deps groups the cross-component dependencies required to instantiate
// Acl. Pass a populated value via NewInstance.
type Deps struct {
}

// NewFactory creates a Factory bound to e. A single Factory may be
// reused to build multiple instances backed by different implementations.
func NewFactory(ctx context.Context, e *wacogo.Engine) (*Factory, error) {
	f_ := &Factory{engine: e}
	b_ := e.NewHostBuilder("example_demo_acl")

	typPerms_ := b_.AddType("perms", host.Flags{Names: []string{"read", "write", "exec"}})
	_ = typPerms_

	b_.AddFunction("grant", &host.FuncType{
		Params:  []host.Param{{Name: "p", Type: typPerms_}},
		Results: []host.ResultDecl{{Name: "", Type: typPerms_}},
	}, wrapGrant(f_))

	comp_, err_ := b_.Build(ctx)
	if err_ != nil {
		return nil, err_
	}
	f_.comp = comp_
	return f_, nil
}

// NewInstance creates a fresh component instance backed by impl. Pass
// inst.Core() to wacogo.WithInstanceImport to wire the instance into a
// composite world. deps may be nil only when Acl has no
// imports.
func (f *Factory) NewInstance(ctx context.Context, impl Acl, deps *Deps, opts ...host.InstantiateOption) (*host.ComponentInstance, error) {
	_ = deps
	state_ := &instanceState{impl: impl}
	opts = append(opts, host.WithUserState(state_))
	inst_, err_ := f.comp.Instantiate(ctx, opts...)
	if err_ != nil {
		return nil, err_
	}
	return inst_, nil
}

// Close releases resources shared by the Factory. Existing instances
// remain callable until each is closed individually.
func (f *Factory) Close(ctx context.Context) error { return f.comp.Close(ctx) }

func wrapGrant(f *Factory) host.Func {
	return func(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, stack []uint64) error {
		state_ := h.UserState().(*instanceState)
		fnType_ := cc.Instance().ExportedFunc("grant").Type()
		_ = fnType_
		p := Perms(stack[0])
		result_, implErr_ := state_.impl.Grant(ctx, p)
		if implErr_ != nil {
			return fmt.Errorf("wacogo/witgen: grant: impl returned error: %w", implErr_)
		}
		stack[0] = uint64(result_)
		return nil
	}
}
