// Code generated by wacogo-witgen from acl.wit. DO NOT EDIT.

// Package acl provides Go bindings for the example:demo/acl interface.
package acl

import (
	"context"
)

// InterfaceName is the canonical WIT id of the interface this binding
// was generated from.
const InterfaceName = "example:demo/acl"

// Acl is the Go binding for the example:demo/acl interface.
// Implement it to provide a host-side component, or pass an exported wasm
// instance to WrapInstance to obtain a Acl that calls into wasm.
// Resource-typed parameters and results appear as *<R>Handle values that can
// be passed across component boundaries.
type Acl interface {
	Grant(ctx context.Context, p Perms) (Perms, error)
}

// Perms corresponds to the WIT flags perms.
type Perms uint32

const (
	PermsRead  Perms = 1 << 0
	PermsWrite Perms = 1 << 1
	PermsExec  Perms = 1 << 2
)
