// Code generated by wacogo-witgen from acl.wit. DO NOT EDIT.

// Package acl provides Go bindings for the example:demo/acl interface.
package acl

import (
	"context"
	"fmt"

	"github.com/partite-ai/wacogo"
	"github.com/partite-ai/wacogo/host"
)

// aclWrapper is the concrete type returned by WrapInstance
// as a Acl. Held internally; users hold it via the Acl
// interface.
type aclWrapper struct {
	callerInst *host.ComponentInstance
	fnGrant    *host.ExportedFunc
}

// WrapInstance returns a Acl that forwards method calls to
// callee. caller is a Factory-built host instance whose state hosts any
// handles minted by callee during those calls.
func WrapInstance(caller *host.ComponentInstance, callee *wacogo.ComponentInstance) Acl {
	w_ := &aclWrapper{callerInst: caller}
	w_.fnGrant = host.WrapExportedFunc(callee.ExportedFunc("grant"))
	return w_
}
func (w *aclWrapper) Grant(ctx context.Context, p Perms) (Perms, error) {
	var resVal_ Perms
	arg0_ := p
	{
		callErr_ := w.fnGrant.CallRaw(ctx, w.callerInst,
			func(caller, callee *host.CallContext, stack []uint64) {
				stack[0] = uint64(arg0_)
			},
			func(caller, callee *host.CallContext, stack []uint64) {
				resVal_ = Perms(stack[0])
			},
		)
		if callErr_ != nil {
			return Perms(0), fmt.Errorf("wacogo/witgen: CallRaw failed: %w", callErr_)
		}
	}
	return resVal_, nil
}
