// Code generated by wacogo-witgen from pair.wit. DO NOT EDIT.

// Package pair provides Go bindings for the example:demo/pair interface.
package pair

import (
	"context"
	"fmt"

	"github.com/partite-ai/wacogo"
	"github.com/partite-ai/wacogo/host"
)

// Factory builds host-side instances of the Pair interface
// from a Go implementation.
type Factory struct {
	engine *wacogo.Engine
	comp   *host.Component
}

type instanceState struct {
	impl Pair
}

// Deps groups the cross-component dependencies required to instantiate
// Pair. Pass a populated value via NewInstance.
type Deps struct {
}

// NewFactory creates a Factory bound to e. A single Factory may be
// reused to build multiple instances backed by different implementations.
func NewFactory(ctx context.Context, e *wacogo.Engine) (*Factory, error) {
	f_ := &Factory{engine: e}
	b_ := e.NewHostBuilder("example_demo_pair")

	b_.AddFunction("swap", &host.FuncType{
		Params:  []host.Param{{Name: "p", Type: host.Tuple{Types: []host.TypeExpr{host.U32, host.U32}}}},
		Results: []host.ResultDecl{{Name: "", Type: host.Tuple{Types: []host.TypeExpr{host.U32, host.U32}}}},
	}, wrapSwap(f_))

	comp_, err_ := b_.Build(ctx)
	if err_ != nil {
		return nil, err_
	}
	f_.comp = comp_
	return f_, nil
}

// NewInstance creates a fresh component instance backed by impl. Pass
// inst.Core() to wacogo.WithInstanceImport to wire the instance into a
// composite world. deps may be nil only when Pair has no
// imports.
func (f *Factory) NewInstance(ctx context.Context, impl Pair, deps *Deps, opts ...host.InstantiateOption) (*host.ComponentInstance, error) {
	_ = deps
	state_ := &instanceState{impl: impl}
	opts = append(opts, host.WithUserState(state_))
	inst_, err_ := f.comp.Instantiate(ctx, opts...)
	if err_ != nil {
		return nil, err_
	}
	return inst_, nil
}

// Close releases resources shared by the Factory. Existing instances
// remain callable until each is closed individually.
func (f *Factory) Close(ctx context.Context) error { return f.comp.Close(ctx) }

func toGoFlatTupleU32U32(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, stack []uint64) (TupleU32U32, error) {
	var v_ TupleU32U32
	tupT_ := ty.(wacogo.TypeTuple)
	_ = tupT_
	v_.F0 = uint32(stack[0])
	v_.F1 = uint32(stack[1])
	return v_, nil
}

func toGoMemTupleU32U32(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, ptr uint32) (TupleU32U32, error) {
	var v_ TupleU32U32
	tupT_ := ty.(wacogo.TypeTuple)
	_ = tupT_
	if tmp_, ok_ := cc.Memory().ReadUint32Le(ptr); !ok_ {
		return TupleU32U32{}, fmt.Errorf("wacogo/witgen: toGoMemTupleU32U32: field F0: bad memory read")
	} else {
		v_.F0 = tmp_
	}
	if tmp_, ok_ := cc.Memory().ReadUint32Le(ptr + 4); !ok_ {
		return TupleU32U32{}, fmt.Errorf("wacogo/witgen: toGoMemTupleU32U32: field F1: bad memory read")
	} else {
		v_.F1 = tmp_
	}
	return v_, nil
}

func fromGoFlatTupleU32U32(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, stack []uint64, v TupleU32U32) error {
	stack[0] = uint64(v.F0)
	stack[1] = uint64(v.F1)
	return nil
}

func fromGoMemTupleU32U32(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, ptr uint32, v TupleU32U32) error {
	if ok_ := cc.Memory().WriteUint32Le(ptr, v.F0); !ok_ {
		return fmt.Errorf("wacogo/witgen: fromGoMemTupleU32U32: field F0: bad memory write")
	}
	if ok_ := cc.Memory().WriteUint32Le(ptr+4, v.F1); !ok_ {
		return fmt.Errorf("wacogo/witgen: fromGoMemTupleU32U32: field F1: bad memory write")
	}
	return nil
}

func liftFlatTupleU32U32(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, stack []uint64) (TupleU32U32, error) {
	var v_ TupleU32U32
	tupT_ := ty.(wacogo.TypeTuple)
	_ = tupT_
	v_.F0 = uint32(stack[0])
	v_.F1 = uint32(stack[1])
	return v_, nil
}

func liftMemTupleU32U32(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, ptr uint32) (TupleU32U32, error) {
	var v_ TupleU32U32
	tupT_ := ty.(wacogo.TypeTuple)
	_ = tupT_
	if tmp_, ok_ := callee.Memory().ReadUint32Le(ptr); !ok_ {
		return TupleU32U32{}, fmt.Errorf("wacogo/witgen: liftMemTupleU32U32: field F0: bad memory read")
	} else {
		v_.F0 = tmp_
	}
	if tmp_, ok_ := callee.Memory().ReadUint32Le(ptr + 4); !ok_ {
		return TupleU32U32{}, fmt.Errorf("wacogo/witgen: liftMemTupleU32U32: field F1: bad memory read")
	} else {
		v_.F1 = tmp_
	}
	return v_, nil
}

func lowerFlatTupleU32U32(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, stack []uint64, v TupleU32U32) error {
	tupT_ := ty.(wacogo.TypeTuple)
	_ = tupT_
	stack[0] = uint64(v.F0)
	stack[1] = uint64(v.F1)
	return nil
}

func lowerMemTupleU32U32(ctx context.Context, caller, callee *host.CallContext, h *host.ComponentInstance, ty wacogo.Type, ptr uint32, v TupleU32U32) error {
	tupT_ := ty.(wacogo.TypeTuple)
	_ = tupT_
	if ok_ := callee.Memory().WriteUint32Le(ptr, v.F0); !ok_ {
		return fmt.Errorf("wacogo/witgen: lowerMemTupleU32U32: field F0: bad memory write")
	}
	if ok_ := callee.Memory().WriteUint32Le(ptr+4, v.F1); !ok_ {
		return fmt.Errorf("wacogo/witgen: lowerMemTupleU32U32: field F1: bad memory write")
	}
	return nil
}

func wrapSwap(f *Factory) host.Func {
	return func(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, stack []uint64) error {
		state_ := h.UserState().(*instanceState)
		fnType_ := cc.Instance().ExportedFunc("swap").Type()
		_ = fnType_
		var p TupleU32U32
		{
			v_, err_ := toGoFlatTupleU32U32(ctx, cc, h, fnType_.Params[0].Type, stack[0:2])
			if err_ != nil {
				return err_
			}
			p = v_
		}
		result_, implErr_ := state_.impl.Swap(ctx, p)
		if implErr_ != nil {
			return fmt.Errorf("wacogo/witgen: swap: impl returned error: %w", implErr_)
		}
		outPtr_, rerr_ := cc.Realloc(ctx, 0, 0, 4, 8)
		if rerr_ != nil {
			return fmt.Errorf("wacogo/witgen: swap: realloc failed: %w", rerr_)
		}
		if err_ := fromGoMemTupleU32U32(ctx, cc, h, outPtr_, result_); err_ != nil {
			return err_
		}
		stack[0] = uint64(outPtr_)
		return nil
	}
}
