// Code generated by wacogo-witgen from pair.wit. DO NOT EDIT.

// Package pair provides Go bindings for the example:demo/pair interface.
package pair

import (
	"context"
)

// InterfaceName is the canonical WIT id of the interface this binding
// was generated from.
const InterfaceName = "example:demo/pair"

// Pair is the Go binding for the example:demo/pair interface.
// Implement it to provide a host-side component, or pass an exported wasm
// instance to WrapInstance to obtain a Pair that calls into wasm.
// Resource-typed parameters and results appear as *<R>Handle values that can
// be passed across component boundaries.
type Pair interface {
	Swap(ctx context.Context, p TupleU32U32) (TupleU32U32, error)
}

// TupleU32U32 corresponds to a WIT tuple type.
type TupleU32U32 struct {
	F0 uint32
	F1 uint32
}
