// Code generated by wacogo-witgen from pair.wit. DO NOT EDIT.

// Package pair provides Go bindings for the example:demo/pair interface.
package pair

import (
	"context"
	"fmt"

	"github.com/partite-ai/wacogo"
	"github.com/partite-ai/wacogo/host"
)

// pairWrapper is the concrete type returned by WrapInstance
// as a Pair. Held internally; users hold it via the Pair
// interface.
type pairWrapper struct {
	callerInst *host.ComponentInstance
	fnSwap     *host.ExportedFunc
}

// WrapInstance returns a Pair that forwards method calls to
// callee. caller is a Factory-built host instance whose state hosts any
// handles minted by callee during those calls.
func WrapInstance(caller *host.ComponentInstance, callee *wacogo.ComponentInstance) Pair {
	w_ := &pairWrapper{callerInst: caller}
	w_.fnSwap = host.WrapExportedFunc(callee.ExportedFunc("swap"))
	return w_
}
func (w *pairWrapper) Swap(ctx context.Context, p TupleU32U32) (TupleU32U32, error) {
	var resVal_ TupleU32U32
	var resErr_ error
	arg0_ := p
	{
		callErr_ := w.fnSwap.CallRaw(ctx, w.callerInst,
			func(caller, callee *host.CallContext, stack []uint64) {
				if err_ := lowerFlatTupleU32U32(ctx, caller, callee, w.callerInst, w.fnSwap.ParamType(0), stack[0:2], arg0_); err_ != nil {
					resErr_ = err_
					return
				}
			},
			func(caller, callee *host.CallContext, stack []uint64) {
				if v_, err_ := liftMemTupleU32U32(ctx, caller, callee, w.callerInst, w.fnSwap.ResultType(0), uint32(stack[0])); err_ != nil {
					resErr_ = err_
					return
				} else {
					resVal_ = v_
				}
			},
		)
		if callErr_ != nil {
			return TupleU32U32{}, fmt.Errorf("wacogo/witgen: CallRaw failed: %w", callErr_)
		}
		if resErr_ != nil {
			return TupleU32U32{}, resErr_
		}
	}
	return resVal_, nil
}
