// Code generated by wacogo-witgen from add.wit. DO NOT EDIT.

// Package calc provides Go bindings for the example:demo/calc interface.
package calc

import (
	"context"
	"fmt"

	"github.com/partite-ai/wacogo"
	"github.com/partite-ai/wacogo/host"
)

// Factory builds host-side instances of the Calc interface
// from a Go implementation.
type Factory struct {
	engine *wacogo.Engine
	comp   *host.Component
}

type instanceState struct {
	impl Calc
}

// Deps groups the cross-component dependencies required to instantiate
// Calc. Pass a populated value via NewInstance.
type Deps struct {
}

// NewFactory creates a Factory bound to e. A single Factory may be
// reused to build multiple instances backed by different implementations.
func NewFactory(ctx context.Context, e *wacogo.Engine) (*Factory, error) {
	f_ := &Factory{engine: e}
	b_ := e.NewHostBuilder("example_demo_calc")

	b_.AddFunction("add", &host.FuncType{
		Params:  []host.Param{{Name: "a", Type: host.U32}, {Name: "b", Type: host.U32}},
		Results: []host.ResultDecl{{Name: "", Type: host.U32}},
	}, wrapAdd(f_))

	comp_, err_ := b_.Build(ctx)
	if err_ != nil {
		return nil, err_
	}
	f_.comp = comp_
	return f_, nil
}

// NewInstance creates a fresh component instance backed by impl. Pass
// inst.Core() to wacogo.WithInstanceImport to wire the instance into a
// composite world. deps may be nil only when Calc has no
// imports.
func (f *Factory) NewInstance(ctx context.Context, impl Calc, deps *Deps, opts ...host.InstantiateOption) (*host.ComponentInstance, error) {
	_ = deps
	state_ := &instanceState{impl: impl}
	opts = append(opts, host.WithUserState(state_))
	inst_, err_ := f.comp.Instantiate(ctx, opts...)
	if err_ != nil {
		return nil, err_
	}
	return inst_, nil
}

// Close releases resources shared by the Factory. Existing instances
// remain callable until each is closed individually.
func (f *Factory) Close(ctx context.Context) error { return f.comp.Close(ctx) }

func wrapAdd(f *Factory) host.Func {
	return func(ctx context.Context, cc *host.CallContext, h *host.ComponentInstance, stack []uint64) error {
		state_ := h.UserState().(*instanceState)
		fnType_ := cc.Instance().ExportedFunc("add").Type()
		_ = fnType_
		a := uint32(stack[0])
		b := uint32(stack[1])
		result_, implErr_ := state_.impl.Add(ctx, a, b)
		if implErr_ != nil {
			return fmt.Errorf("wacogo/witgen: add: impl returned error: %w", implErr_)
		}
		stack[0] = uint64(result_)
		return nil
	}
}
