// Code generated by wacogo-witgen from add.wit. DO NOT EDIT.

// Package calc provides Go bindings for the example:demo/calc interface.
package calc

import (
	"context"
)

// InterfaceName is the canonical WIT id of the interface this binding
// was generated from.
const InterfaceName = "example:demo/calc"

// Calc is the Go binding for the example:demo/calc interface.
// Implement it to provide a host-side component, or pass an exported wasm
// instance to WrapInstance to obtain a Calc that calls into wasm.
// Resource-typed parameters and results appear as *<R>Handle values that can
// be passed across component boundaries.
type Calc interface {
	Add(ctx context.Context, a uint32, b uint32) (uint32, error)
}
